import { z } from "zod";
import { ApiError,jsonError } from "@/lib/api/errors";
import { auditEvent,enforceRateLimit } from "@/lib/automation/control-plane";
import { requireLiveAgencyProject } from "@/lib/auth/live-tenant";
import { loadSuiteConnection,publishBusinessReviewReply,suiteAccess,updateBusinessLocation } from "@/lib/google/suite";

const schema=z.discriminatedUnion("action",[
  z.object({action:z.literal("draft_profile_change"),projectId:z.string().uuid(),profileId:z.string().uuid(),changeType:z.enum(["hours","special_hours","phone","website","service_area","categories","attributes"]),updateMask:z.enum(["regularHours","specialHours","phoneNumbers","websiteUri","serviceArea","categories","attributes"]),proposedValue:z.record(z.string(),z.unknown()),rationale:z.string().trim().min(10).max(2000),evidence:z.record(z.string(),z.unknown()).optional(),idempotencyKey:z.string().min(8).max(300)}),
  z.object({action:z.literal("approve_profile_change"),projectId:z.string().uuid(),changeId:z.string().uuid()}),
  z.object({action:z.literal("publish_profile_change"),projectId:z.string().uuid(),changeId:z.string().uuid(),confirm:z.literal(true)}),
  z.object({action:z.literal("draft_review_reply"),projectId:z.string().uuid(),reviewId:z.string().uuid(),replyText:z.string().trim().min(2).max(4000)}),
  z.object({action:z.literal("approve_review_reply"),projectId:z.string().uuid(),reviewId:z.string().uuid()}),
  z.object({action:z.literal("publish_review_reply"),projectId:z.string().uuid(),reviewId:z.string().uuid(),confirm:z.literal(true)})
]);
const now=()=>new Date().toISOString();
export async function POST(request:Request){try{const input=schema.parse(await request.json()),publishing=input.action.startsWith("publish_")||input.action.startsWith("approve_"),context=await requireLiveAgencyProject({projectId:input.projectId,permission:publishing?"execution.approve":"seo.write"});await enforceRateLimit(`local-actions:${context.agencyId}:${context.project.id}`,input.action,30,300);let result:unknown;
  if(input.action==="draft_profile_change"){const profile=await context.db.from("local_business_profiles").select("id,regular_hours,special_hours,phone,website_url,service_area,additional_categories,attributes").eq("id",input.profileId).eq("project_id",context.project.id).maybeSingle();if(!profile.data)throw new ApiError("Business Profile location not found.",404,"NOT_FOUND");const currentMap:Record<string,unknown>={regularHours:profile.data.regular_hours,specialHours:profile.data.special_hours,phoneNumbers:{primaryPhone:profile.data.phone},websiteUri:profile.data.website_url,serviceArea:profile.data.service_area,categories:profile.data.additional_categories,attributes:profile.data.attributes};const saved=await context.db.from("local_profile_change_requests").upsert({agency_id:context.agencyId,client_organization_id:context.clientId,project_id:context.project.id,profile_id:input.profileId,change_type:input.changeType,current_value:currentMap[input.updateMask]??null,proposed_value:input.proposedValue,update_mask:input.updateMask,rationale:input.rationale,evidence:input.evidence??{},risk_level:"high",status:"awaiting_approval",idempotency_key:input.idempotencyKey,requested_by:context.userId},{onConflict:"agency_id,idempotency_key"}).select("id,status").single();if(saved.error)throw new ApiError("The profile change could not be drafted.",500,"DATABASE_BINDING_FAILED");result=saved.data;}
  else if(input.action==="approve_profile_change"){const saved=await context.db.from("local_profile_change_requests").update({status:"approved",approved_by:context.userId,approved_at:now(),updated_at:now()}).eq("id",input.changeId).eq("project_id",context.project.id).eq("status","awaiting_approval").select("id,status").maybeSingle();if(!saved.data)throw new ApiError("The profile change is not awaiting approval.",409,"CONFLICT");result=saved.data;}
  else if(input.action==="publish_profile_change"){const change=await context.db.from("local_profile_change_requests").select("*,local_business_profiles!inner(external_location_id)").eq("id",input.changeId).eq("project_id",context.project.id).eq("status","approved").maybeSingle();if(!change.data)throw new ApiError("Approve the profile change before publishing.",409,"CONFLICT");const connection=await loadSuiteConnection(context.db,{agencyId:context.agencyId,clientId:context.clientId,projectId:context.project.id,provider:"google_business_profile"}),access=await suiteAccess(context.db,connection),location=(change.data.local_business_profiles as unknown as {external_location_id:string}).external_location_id;await context.db.from("local_profile_change_requests").update({status:"publishing",updated_at:now()}).eq("id",input.changeId);try{const provider=await updateBusinessLocation(access,location,change.data.update_mask,{name:location,[change.data.update_mask]:change.data.proposed_value});await context.db.from("local_profile_change_requests").update({status:"published",provider_response:provider,published_at:now(),updated_at:now()}).eq("id",input.changeId);result={id:input.changeId,status:"published"};}catch(error){await context.db.from("local_profile_change_requests").update({status:"failed",updated_at:now()}).eq("id",input.changeId);throw error;}}
  else if(input.action==="draft_review_reply"){const saved=await context.db.from("local_reviews").update({reply_text:input.replyText,response_status:"drafted",updated_at:now()}).eq("id",input.reviewId).eq("project_id",context.project.id).select("id,response_status").maybeSingle();if(!saved.data)throw new ApiError("Review not found.",404,"NOT_FOUND");result=saved.data;}
  else if(input.action==="approve_review_reply"){const saved=await context.db.from("local_reviews").update({response_status:"approved",updated_at:now()}).eq("id",input.reviewId).eq("project_id",context.project.id).eq("response_status","drafted").select("id,response_status").maybeSingle();if(!saved.data)throw new ApiError("Draft the review reply before approval.",409,"CONFLICT");result=saved.data;}
  else{const review=await context.db.from("local_reviews").select("id,external_review_id,reply_text,profile_id,local_business_profiles!inner(external_location_id,external_account_id)").eq("id",input.reviewId).eq("project_id",context.project.id).eq("response_status","approved").maybeSingle();if(!review.data?.reply_text)throw new ApiError("Approve the review reply before publishing.",409,"CONFLICT");const profile=review.data.local_business_profiles as unknown as {external_location_id:string;external_account_id:string},connection=await loadSuiteConnection(context.db,{agencyId:context.agencyId,clientId:context.clientId,projectId:context.project.id,provider:"google_business_profile"}),access=await suiteAccess(context.db,connection);await publishBusinessReviewReply(access,profile.external_account_id,profile.external_location_id,review.data.external_review_id,review.data.reply_text);await context.db.from("local_reviews").update({response_status:"published",replied_at:now(),updated_at:now()}).eq("id",input.reviewId);result={id:input.reviewId,status:"published"};}
  await auditEvent({agencyId:context.agencyId,actorUserId:context.userId,action:`local.${input.action}`,resourceType:"seo_project",resourceId:context.project.id,afterState:result,request});return Response.json({ok:true,result});
}catch(error){if(error instanceof z.ZodError)return jsonError(new ApiError(error.issues[0]?.message??"Invalid local SEO action.",400,"VALIDATION_ERROR"));return jsonError(error)}}
