import { createHash,createHmac,timingSafeEqual } from "node:crypto";
import { ApiError,jsonError,logServerError } from "@/lib/api/errors";
import { env } from "@/lib/config/env";
import { getLiveAdminClient } from "@/lib/live/identity";
import { sanitizeWebhookPayload } from "@/lib/security/webhook-payload";
import { ingestLead } from "@/lib/outcomes/service";

function verify(raw:string,signature:string|null,timestamp:string|null){if(!env.ATTRIBUTION_WEBHOOK_SECRET)throw new ApiError("Attribution webhooks are not configured.",503,"NOT_CONFIGURED");if(!signature||!timestamp)throw new ApiError("Webhook signature or timestamp is missing.",401,"INVALID_WEBHOOK_SIGNATURE");const time=Number(timestamp);if(!Number.isFinite(time)||Math.abs(Date.now()-time)>300_000)throw new ApiError("Webhook timestamp is outside the replay window.",401,"WEBHOOK_REPLAY_REJECTED");const expected=createHmac("sha256",env.ATTRIBUTION_WEBHOOK_SECRET).update(`${timestamp}.${raw}`).digest("hex"),actual=Buffer.from(signature.replace(/^sha256=/,""),"hex"),target=Buffer.from(expected,"hex");if(actual.length!==target.length||!timingSafeEqual(actual,target))throw new ApiError("Webhook signature is invalid.",401,"INVALID_WEBHOOK_SIGNATURE")}
const text=(value:unknown)=>typeof value==="string"?value:undefined,num=(value:unknown)=>value==null?undefined:Number(value)||0;
function normalize(provider:string,payload:Record<string,unknown>){const data=(payload.data&&typeof payload.data==="object"?payload.data:payload) as Record<string,unknown>,properties=(data.properties&&typeof data.properties==="object"?data.properties:{}) as Record<string,unknown>,call=(data.call&&typeof data.call==="object"?data.call:data) as Record<string,unknown>;if(provider==="hubspot")return{externalId:String(data.objectId??data.id??properties.hs_object_id??crypto.randomUUID()),source:"hubspot",leadType:"form",status:text(properties.lifecyclestage)??"new",qualified:["salesqualifiedlead","opportunity","customer"].includes(text(properties.lifecyclestage)??""),revenue:num(properties.amount),occurredAt:new Date(Number(data.occurredAt??Date.now())).toISOString(),landingPageUrl:text(properties.hs_analytics_first_url),metadata:sanitizeWebhookPayload(payload) as Record<string,unknown>};if(provider==="callrail")return{externalId:String(call.id??call.call_id??crypto.randomUUID()),source:"callrail",leadType:"call",status:text(call.customer_status)??"completed",qualified:call.qualified===true||call.qualified==="true",occurredAt:text(call.start_time)??new Date().toISOString(),landingPageUrl:text(call.landing_page_url),query:text(call.keywords),metadata:sanitizeWebhookPayload(payload) as Record<string,unknown>};return{externalId:String(data.externalId??data.id??crypto.randomUUID()),source:provider,leadType:text(data.leadType)??"other",status:text(data.status)??"new",qualified:typeof data.qualified==="boolean"?data.qualified:undefined,revenue:num(data.revenue),grossProfit:num(data.grossProfit),occurredAt:text(data.occurredAt)??new Date().toISOString(),landingPageUrl:text(data.landingPageUrl),query:text(data.query),metadata:sanitizeWebhookPayload(payload) as Record<string,unknown>}}

export async function POST(request:Request,context:{params:Promise<{provider:string}>}){const referenceId=crypto.randomUUID();try{const{provider}=await context.params;if(!["callrail","hubspot","crm"].includes(provider))throw new ApiError("Attribution provider is not supported.",404,"NOT_FOUND");const raw=await request.text();verify(raw,request.headers.get("x-hdseo-signature"),request.headers.get("x-hdseo-timestamp"));const url=new URL(request.url),projectId=url.searchParams.get("projectId");if(!projectId)throw new ApiError("Webhook project binding is missing.",400,"VALIDATION_ERROR");let payload:Record<string,unknown>;try{payload=JSON.parse(raw) as Record<string,unknown>}catch{throw new ApiError("Webhook JSON is invalid.",400,"VALIDATION_ERROR")}const db=getLiveAdminClient(),project=await db.from("seo_projects").select("agency_id,client_organization_id,id").eq("id",projectId).eq("status","active").maybeSingle();if(!project.data)throw new ApiError("Webhook project binding is invalid.",404,"NOT_FOUND");const payloadHash=createHash("sha256").update(raw).digest("hex"),eventId=request.headers.get("x-webhook-id")??request.headers.get("x-request-id")??`${provider}:${payloadHash}`;const prior=await db.from("webhook_events").select("id,status").eq("provider",provider).eq("delivery_id",eventId).maybeSingle();if(prior.data)return Response.json({ok:true,duplicate:true});const event=await db.from("webhook_events").insert({provider,delivery_id:eventId,event_type:String(payload.type??payload.subscriptionType??"lead.updated"),agency_id:project.data.agency_id,payload_hash:payloadHash,payload:sanitizeWebhookPayload(payload),signature_valid:true,status:"processing",attempt_count:1,received_at:new Date().toISOString()}).select("id").single();const lead=normalize(provider,payload),saved=await ingestLead(db,{agencyId:project.data.agency_id,clientId:project.data.client_organization_id,projectId,userId:null},lead);await db.from("webhook_events").update({status:"processed",processed_at:new Date().toISOString()}).eq("id",event.data?.id);return Response.json({ok:true,leadId:saved.id});}catch(error){logServerError("attribution_webhook_failed",error,{referenceId,provider:"attribution",operation:"webhook"});return jsonError(error)}}
