import"server-only";
/* Supabase types are regenerated after production migration 0021. */
/* eslint-disable @typescript-eslint/no-explicit-any */
import type{SupabaseClient}from"@supabase/supabase-js";
import{ApiError}from"@/lib/api/errors";
import{isSafeAuthorityOpportunity,normalizeBuyerQuestion,phaseForSequence,semanticOverlap}from"@/lib/growth/core";

export type GrowthTenant={agencyId:string;clientId:string;projectId:string;userId:string|null};
const now=()=>new Date().toISOString();
const scope=(query:any,tenant:Omit<GrowthTenant,"userId">)=>query.eq("agency_id",tenant.agencyId).eq("client_organization_id",tenant.clientId).eq("project_id",tenant.projectId);
const must=<T=any>(result:{data:unknown;error:unknown},message:string):T=>{if(result.error||result.data==null)throw new ApiError(message,500,"DATABASE_BINDING_FAILED");return result.data as T};
const record=(value:unknown):Record<string,any>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,any>:{};
const number=(value:unknown,fallback=0)=>typeof value==="number"&&Number.isFinite(value)?value:fallback;
const text=(value:unknown,fallback="")=>typeof value==="string"?value:fallback;

export async function growthWorkspaceSnapshot(db:SupabaseClient,tenant:Omit<GrowthTenant,"userId">){
  const[brand,plans,links,refresh,prompts,snapshots,authority,tools,caseStudies,services,locations]=await Promise.all([
    scope(db.from("brand_profiles").select("*"),tenant).maybeSingle(),scope(db.from("growth_plans").select("*"),tenant).order("version",{ascending:false}).limit(5),scope(db.from("internal_link_edges").select("*"),tenant).order("relevance_score",{ascending:false}).limit(150),scope(db.from("content_refresh_candidates").select("*"),tenant).order("priority_score",{ascending:false}).limit(100),scope(db.from("ai_visibility_prompts").select("*"),tenant).eq("active",true).order("created_at",{ascending:false}),scope(db.from("ai_visibility_snapshots").select("*"),tenant).order("captured_at",{ascending:false}).limit(250),scope(db.from("authority_opportunities").select("*"),tenant).order("relevance_score",{ascending:false}).limit(100),scope(db.from("growth_tool_specs").select("*"),tenant).order("created_at",{ascending:false}),scope(db.from("case_study_snapshots").select("*"),tenant).order("period_end",{ascending:false}),scope(db.from("seo_services").select("id,name,status"),tenant).eq("status","active"),scope(db.from("seo_locations").select("id,name,city,state,country_code,status"),tenant).eq("status","active")
  ]);
  for(const result of[brand,plans,links,refresh,prompts,snapshots,authority,tools,caseStudies])if(result.error)throw new ApiError("Local Growth Engine needs migration 0021 before it can load.",503,"DATABASE_BINDING_FAILED");
  const latestPlan=(plans.data??[])[0]??null,items=latestPlan?await scope(db.from("growth_plan_items").select("*"),tenant).eq("plan_id",latestPlan.id).order("sequence"):{data:[],error:null};
  if(items.error)throw new ApiError("The Local Growth Plan could not be loaded.",500,"DATABASE_BINDING_FAILED");
  const promptRows=prompts.data??[],snapshotRows=snapshots.data??[],mentionedPromptIds=new Set(snapshotRows.filter((row:any)=>row.client_mentioned).map((row:any)=>row.prompt_id));
  return{brand:brand.data??null,plans:plans.data??[],latestPlan,planItems:items.data??[],links:links.data??[],refreshCandidates:refresh.data??[],prompts:promptRows.map((row:any)=>({...row,lastObservation:snapshotRows.find((item:any)=>item.prompt_id===row.id)??null})),authority:authority.data??[],tools:tools.data??[],caseStudies:caseStudies.data??[],services:services.data??[],locations:locations.data??[],summary:{plannedActions:(items.data??[]).length,approvalsNeeded:(items.data??[]).filter((row:any)=>row.approval_required&&["proposed","awaiting_approval"].includes(row.status)).length,proposedLinks:(links.data??[]).filter((row:any)=>row.status==="proposed").length,refreshes:(refresh.data??[]).filter((row:any)=>row.status==="open").length,aiVisibility:promptRows.length?Math.round(mentionedPromptIds.size/promptRows.length*100):null,qualifiedAuthority:(authority.data??[]).filter((row:any)=>["qualified","awaiting_approval","approved","outreach","earned"].includes(row.status)).length}};
}

export async function saveBrandProfile(db:SupabaseClient,tenant:GrowthTenant,input:any){
  const row={agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,business_summary:input.businessSummary,target_audiences:input.targetAudiences,tone_attributes:input.toneAttributes,preferred_vocabulary:input.preferredVocabulary,prohibited_vocabulary:input.prohibitedVocabulary,reading_level:input.readingLevel,brand_values:input.brandValues,style_rules:input.styleRules??{},visual_identity:input.visualIdentity??{},source_urls:input.sourceUrls??[],status:"ready",learned_at:now(),updated_at:now()};
  return must(await db.from("brand_profiles").upsert(row,{onConflict:"project_id"}).select("id,status,profile_version").single(),"Brand DNA could not be saved.");
}

function opportunityTitle(row:any,keyword:string){const action=text(row.action_type,"IMPROVE");if(action==="BUILD")return`Build the owner page for “${keyword}”`;if(action==="LINK")return`Strengthen internal authority for “${keyword}”`;if(action==="TECHNICAL")return`Remove the technical blocker affecting “${keyword}”`;if(action==="MAPS")return`Improve local discovery for “${keyword}”`;return`Improve the existing page for “${keyword}”`}
export async function generateGrowthPlan(db:SupabaseClient,tenant:GrowthTenant,input:{monthlyBudget:number;generatedBy?:string}){
  const[services,locations,opportunities,previous]=await Promise.all([scope(db.from("seo_services").select("id,name"),tenant).eq("status","active"),scope(db.from("seo_locations").select("id,name,city,state"),tenant).eq("status","active"),scope(db.from("seo_opportunities").select("id,keyword_id,opportunity_score,confidence_score,action_type,priority,evidence,recommended_actions,status"),tenant).eq("status","open").order("opportunity_score",{ascending:false}).limit(30),scope(db.from("growth_plans").select("version"),tenant).order("version",{ascending:false}).limit(1).maybeSingle()]);
  if(locations.error||!locations.data?.length)throw new ApiError("Add at least one verified service area before generating a local growth plan.",409,"SERVICE_AREA_REQUIRED");
  if(services.error||!services.data?.length)throw new ApiError("Add at least one active service before generating a growth plan.",409,"SERVICE_REQUIRED");
  const keywordIds=(opportunities.data??[]).map((row:any)=>row.keyword_id).filter(Boolean),keywords=keywordIds.length?await db.from("seo_keywords").select("id,keyword,service_id,location_id").eq("project_id",tenant.projectId).in("id",keywordIds):{data:[]},keywordMap=new Map((keywords.data??[]).map((row:any)=>[row.id,row]));
  const version=(previous.data?.version??0)+1,plan=must<any>(await db.from("growth_plans").insert({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,version,monthly_budget:input.monthlyBudget,strategy_summary:`Prioritize technical health, existing-page gains, local relevance, conversion, earned authority, and selective new content across the next 90 days for ${locations.data.map((row:any)=>[row.city||row.name,row.state].filter(Boolean).join(", ")).join("; ")}.`,status:"awaiting_approval",value_model:{monthlyBudget:input.monthlyBudget,basis:"directional",guardrails:["Verified service areas only","Approval before publishing or paid spend","Refresh an owner page before creating overlapping content"]},generated_by:input.generatedBy??"strategy_agent"}).select("id,period_start").single(),"The Local Growth Plan could not be created.");
  const baseline=[
    {action_type:"TECHNICAL",title:"Resolve crawl, indexation, schema, and sitemap blockers",priority_score:95,risk_level:"medium",acceptance_criteria:["Critical pages return a successful status","Robots, canonical, schema, and sitemap checks pass"]},
    {action_type:"LINK",title:"Build the internal-link graph and repair orphaned owner pages",priority_score:88,risk_level:"low",acceptance_criteria:["Every priority owner page has relevant contextual inbound links","No broken or circular recommendation is approved"]},
    {action_type:"REFRESH",title:"Refresh declining pages before creating overlapping content",priority_score:84,risk_level:"low",acceptance_criteria:["Search Console decline and on-page diagnosis are stored","Existing keyword ownership is preserved"]},
    {action_type:"AI_VISIBILITY",title:"Measure buyer-question visibility and citation coverage",priority_score:72,risk_level:"low",acceptance_criteria:["Prompts are service-area relevant","Mentions and citations are recorded as observations, not causation claims"]},
    {action_type:"CONVERSION",title:"Verify lead tracking and local conversion paths",priority_score:82,risk_level:"medium",acceptance_criteria:["Forms and calls have a verifiable attribution path","No revenue claim is made without evidence"]},
    {action_type:"AUTHORITY",title:"Qualify legitimate local and editorial authority opportunities",priority_score:68,risk_level:"medium",acceptance_criteria:["Opportunities pass relevance, geography, editorial, and risk checks","No reciprocal-link or paid-dofollow scheme is used"]}
  ];
  const derived=(opportunities.data??[]).slice(0,14).map((row:any)=>{const kw=keywordMap.get(row.keyword_id),evidence=record(row.evidence),keyword=text(kw?.keyword,text(evidence.keyword,"verified local opportunity"));return{action_type:["BUILD","IMPROVE","LINK","LOCALIZE","DEFEND","TECHNICAL","CONTENT","MAPS"].includes(row.action_type)?row.action_type:"IMPROVE",title:opportunityTitle(row,keyword),target_keyword:keyword,service_id:kw?.service_id??null,location_id:kw?.location_id??null,priority_score:Math.max(0,Math.min(100,number(row.opportunity_score,50))),risk_level:["BUILD","TECHNICAL","MAPS"].includes(row.action_type)?"medium":"low",opportunity_id:row.id,expected_value:{basis:"directional",confidence:row.confidence_score??null,estimatedMonthlyValue:evidence.estimatedMonthlyValue??null,valuePerDollar:evidence.valuePerDollar??null},evidence,acceptance_criteria:["The change is tied to the assigned owner page and verified service area","Pre-change evidence and rollback instructions are stored","Post-change crawl and Search Console monitoring are scheduled"]}});
  const actions=[...baseline,...derived].sort((a,b)=>number(b.priority_score)-number(a.priority_score)).slice(0,20),start=new Date(plan.period_start+"T12:00:00Z");
  const rows=actions.map((item:any,index)=>{const sequence=index+1,scheduled=new Date(start);scheduled.setUTCDate(scheduled.getUTCDate()+Math.min(84,index*5));return{...item,agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,plan_id:plan.id,sequence,phase_days:phaseForSequence(sequence),scheduled_for:scheduled.toISOString().slice(0,10),approval_required:true,status:"awaiting_approval",evidence:item.evidence??{source:"system_baseline"},expected_value:item.expected_value??{basis:"strategic prerequisite"},dependencies:[]}});
  must(await db.from("growth_plan_items").insert(rows).select("id"),"The Local Growth Plan actions could not be saved.");return plan;
}

export async function approveGrowthPlan(db:SupabaseClient,tenant:GrowthTenant,planId:string){
  const plan=must<any>(await scope(db.from("growth_plans").update({status:"approved",approved_by:tenant.userId,approved_at:now(),updated_at:now()}).eq("id",planId).select("id"),tenant).maybeSingle(),"The Local Growth Plan was not found.");
  const updated=await scope(db.from("growth_plan_items").update({status:"approved",updated_at:now()}).eq("plan_id",plan.id).eq("status","awaiting_approval"),tenant);if(updated.error)throw new ApiError("Plan actions could not be approved.",500,"DATABASE_BINDING_FAILED");return plan;
}

function absolute(value:string,base:string){try{return new URL(value,base).href.split("#")[0]}catch{return null}}
export async function buildInternalLinkGraph(db:SupabaseClient,tenant:GrowthTenant){
  const result=await scope(db.from("seo_page_snapshots").select("id,url,title,h1,internal_links,captured_at,indexable"),tenant).order("captured_at",{ascending:false}).limit(500);if(result.error)throw new ApiError("Crawl evidence could not be loaded.",500,"DATABASE_BINDING_FAILED");
  const latest=new Map<string,any>();for(const page of result.data??[])if(!latest.has(page.url))latest.set(page.url,page);const pages=[...latest.values()].filter(page=>page.indexable!==false),known=new Set(pages.map(page=>page.url)),incoming=new Map<string,number>(),rows:any[]=[];
  for(const page of pages)for(const raw of page.internal_links??[]){const target=absolute(typeof raw==="string"?raw:raw?.href??"",page.url);if(!target||target===page.url)continue;incoming.set(target,(incoming.get(target)??0)+1);rows.push({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,source_url:page.url,target_url:target,anchor_text:typeof raw==="object"?raw.text??null:null,relationship:"contextual",status:known.has(target)?"observed":"broken",relevance_score:known.has(target)?60:0,source_snapshot_id:page.id,evidence:{source:"crawl"},last_verified_at:now(),updated_at:now()})}
  for(const target of pages.filter(page=>(incoming.get(page.url)??0)===0).slice(0,30)){const source=pages.filter(page=>page.url!==target.url&&!((page.internal_links??[]).some((item:any)=>absolute(typeof item==="string"?item:item?.href??"",page.url)===target.url))).map(page=>({page,score:semanticOverlap(`${page.title??""} ${page.h1??""} ${page.url}`,`${target.title??""} ${target.h1??""} ${target.url}`)})).sort((a,b)=>b.score-a.score)[0];if(source&&source.score>0)rows.push({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,source_url:source.page.url,target_url:target.url,anchor_text:target.h1||target.title||null,relationship:"supporting_to_owner",status:"proposed",relevance_score:Math.max(50,source.score),source_snapshot_id:source.page.id,evidence:{source:"orphan_detection",targetInboundLinks:0,semanticOverlap:source.score},last_verified_at:now(),updated_at:now()})}
  if(rows.length){const saved=await db.from("internal_link_edges").upsert(rows,{onConflict:"project_id,source_url,target_url,relationship"});if(saved.error)throw new ApiError("Internal-link intelligence could not be saved.",500,"DATABASE_BINDING_FAILED")}return{pages:pages.length,edges:rows.length,proposals:rows.filter(row=>row.status==="proposed").length};
}

export async function evaluateContentRefreshes(db:SupabaseClient,tenant:GrowthTenant){
  const since=new Date(Date.now()-56*86400000).toISOString().slice(0,10),[gsc,pages]=await Promise.all([scope(db.from("search_console_rows").select("date,page_url,clicks,impressions,ctr,average_position"),tenant).gte("date",since).limit(10000),scope(db.from("seo_page_snapshots").select("url,title,meta_description,h1,schema_types,captured_at"),tenant).order("captured_at",{ascending:false}).limit(1000)]);if(gsc.error||pages.error)throw new ApiError("Search and crawl evidence could not be evaluated.",500,"DATABASE_BINDING_FAILED");
  const latest=new Map<string,any>();for(const page of pages.data??[])if(!latest.has(page.url))latest.set(page.url,page);const cutoff=Date.now()-28*86400000,groups=new Map<string,{current:any;prior:any}>();
  for(const row of gsc.data??[]){const group=groups.get(row.page_url)??{current:{clicks:0,impressions:0,positionSum:0,n:0},prior:{clicks:0,impressions:0,positionSum:0,n:0}},bucket=new Date(row.date).getTime()>=cutoff?group.current:group.prior;bucket.clicks+=number(row.clicks);bucket.impressions+=number(row.impressions);bucket.positionSum+=number(row.average_position);bucket.n++;groups.set(row.page_url,group)}
  const rows:any[]=[];for(const[url,group]of groups){const page=latest.get(url),current={clicks:group.current.clicks,impressions:group.current.impressions,ctr:group.current.impressions?group.current.clicks/group.current.impressions:0,position:group.current.n?group.current.positionSum/group.current.n:null},prior={clicks:group.prior.clicks,impressions:group.prior.impressions,ctr:group.prior.impressions?group.prior.clicks/group.prior.impressions:0,position:group.prior.n?group.prior.positionSum/group.prior.n:null},reasons:string[]=[];if(prior.clicks>=5&&current.clicks<prior.clicks*.8)reasons.push("CLICKS_DECLINED");if(prior.ctr>.005&&current.ctr<prior.ctr*.8)reasons.push("CTR_DECLINED");if(prior.position&&current.position&&current.position-prior.position>=2)reasons.push("POSITION_DECLINED");if(page&&(!page.meta_description||!page.h1))reasons.push("ON_PAGE_GAP");if(page&&!(page.schema_types?.length))reasons.push("SCHEMA_GAP");if(!reasons.length)continue;const priority=Math.min(100,40+reasons.length*12+Math.min(24,prior.clicks));rows.push({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,target_url:url,reason_codes:reasons,performance_before:prior,diagnosis:{current,latestCrawlAt:page?.captured_at??null},recommended_changes:reasons.includes("CTR_DECLINED")?["Review search intent, title, and snippet using current query evidence","Preserve the existing owner URL and validate the change"]:["Refresh stale or incomplete sections using verified business proof","Improve relevant internal links and revalidate crawlability"],expected_value:{basis:"recover_observed_demand",priorClicks:prior.clicks},priority_score:priority,last_evaluated_at:now(),updated_at:now()})}
  if(rows.length){const saved=await db.from("content_refresh_candidates").upsert(rows,{onConflict:"project_id,target_url"});if(saved.error)throw new ApiError("Refresh candidates could not be saved.",500,"DATABASE_BINDING_FAILED")}return{evaluated:groups.size,candidates:rows.length};
}

export async function addAiPrompt(db:SupabaseClient,tenant:GrowthTenant,input:any){const normalized=normalizeBuyerQuestion(input.question);return must(await db.from("ai_visibility_prompts").upsert({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,question:input.question,normalized_question:normalized,engine:input.engine,buyer_stage:input.buyerStage,service_id:input.serviceId??null,location_id:input.locationId??null,updated_at:now()},{onConflict:"project_id,normalized_question,engine"}).select("id").single(),"The buyer question could not be saved.")}
export async function recordAiObservation(db:SupabaseClient,tenant:GrowthTenant,input:any){const prompt=await scope(db.from("ai_visibility_prompts").select("id").eq("id",input.promptId),tenant).maybeSingle();if(!prompt.data)throw new ApiError("The AI visibility prompt was not found.",404,"NOT_FOUND");return must(await db.from("ai_visibility_snapshots").insert({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,prompt_id:input.promptId,client_mentioned:input.clientMentioned,mention_position:input.mentionPosition??null,answer_summary:input.answerSummary??null,cited_urls:input.citedUrls??[],competitor_mentions:input.competitorMentions??[],evidence_source:input.evidenceSource}).select("id").single(),"The AI visibility observation could not be saved.")}
export async function addAuthorityOpportunity(db:SupabaseClient,tenant:GrowthTenant,input:any){if(!isSafeAuthorityOpportunity(input.title,input.recommendedAction,input.targetUrl))throw new ApiError("Automated link exchanges, reciprocal schemes, and paid dofollow links are not permitted.",400,"UNSAFE_AUTHORITY_TACTIC");return must(await db.from("authority_opportunities").insert({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,opportunity_type:input.opportunityType,title:input.title,target_domain:input.targetDomain??null,target_url:input.targetUrl??null,relevance_score:input.relevanceScore,geographic_fit:input.geographicFit,editorial_score:input.editorialScore,risk_score:input.riskScore,evidence:input.evidence??{},recommended_action:input.recommendedAction,status:input.riskScore<=30?"qualified":"discovered"}).select("id,status").single(),"The authority opportunity could not be saved.")}
export async function createGrowthToolSpec(db:SupabaseClient,tenant:GrowthTenant,input:any){const claims=await scope(db.from("business_claims").select("id"),tenant).eq("status","verified").limit(100),needsClaims=input.toolType==="estimator"||input.toolType==="calculator",claimIds=(claims.data??[]).map((row:any)=>row.id);return must(await db.from("growth_tool_specs").insert({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,title:input.title,slug:input.slug,tool_type:input.toolType,target_keyword:input.targetKeyword??null,user_job:input.userJob,inputs:input.inputs??[],conversion_goal:input.conversionGoal??{primary:"qualified_lead"},approved_claim_ids:claimIds,status:needsClaims&&!claimIds.length?"evidence_needed":"ready",risk_level:needsClaims?"high":"medium",created_by:tenant.userId}).select("id,status").single(),"The interactive tool specification could not be saved.")}
export async function createCaseStudySnapshot(db:SupabaseClient,tenant:GrowthTenant,input:{title:string;periodStart:string;periodEnd:string}){
  if(input.periodEnd<input.periodStart)throw new ApiError("The outcome period must end on or after it starts.",400,"VALIDATION_ERROR");
  const[gsc,leads,executions]=await Promise.all([
    scope(db.from("search_console_rows").select("clicks,impressions,average_position,page_url,date"),tenant).gte("date",input.periodStart).lte("date",input.periodEnd).limit(10000),
    scope(db.from("seo_leads").select("qualified,revenue,gross_profit,landing_page_url,occurred_at"),tenant).gte("occurred_at",input.periodStart).lte("occurred_at",`${input.periodEnd}T23:59:59Z`).limit(1000),
    scope(db.from("seo_executions").select("id,status,production_commit_sha,production_deployed_at,created_at"),tenant).gte("created_at",input.periodStart).lte("created_at",`${input.periodEnd}T23:59:59Z`).limit(200)
  ]);
  if(gsc.error||leads.error||executions.error)throw new ApiError("Outcome evidence could not be loaded. Verify Search Console, lead tracking, and migrations before retrying.",503,"EVIDENCE_REFRESH_REQUIRED");
  const rows=gsc.data??[],outcome={clicks:rows.reduce((sum:number,row:any)=>sum+number(row.clicks),0),impressions:rows.reduce((sum:number,row:any)=>sum+number(row.impressions),0),averagePosition:rows.length?rows.reduce((sum:number,row:any)=>sum+number(row.average_position),0)/rows.length:null},leadRows=leads.data??[],executionRows=executions.data??[];
  return must(await db.from("case_study_snapshots").insert({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,title:input.title,period_start:input.periodStart,period_end:input.periodEnd,changed_urls:[],deployment_refs:executionRows.map((row:any)=>({id:row.id,status:row.status,commitSha:row.production_commit_sha,deployedAt:row.production_deployed_at,createdAt:row.created_at})),query_filters:{projectId:tenant.projectId,dateRange:[input.periodStart,input.periodEnd]},outcome_metrics:outcome,leads_summary:{count:leadRows.length,qualified:leadRows.filter((row:any)=>row.qualified).length,revenue:leadRows.reduce((sum:number,row:any)=>sum+number(row.revenue),0),grossProfit:leadRows.reduce((sum:number,row:any)=>sum+number(row.gross_profit),0)},confounders:["Search demand, seasonality, competitor activity, and offline marketing may also affect outcomes."],public_summary:`Observed ${outcome.clicks} Search Console clicks and ${leadRows.length} recorded leads during the selected period. Results are observational until a reviewer verifies the underlying evidence.`,status:"draft"}).select("id,status").single(),"The evidence snapshot could not be created.");
}
