import {readFile} from "node:fs/promises";
import {describe,expect,it} from "vitest";
import {selectRepositoryForProject} from "../lib/github/repository-selection";
const root=new URL("../",import.meta.url);
describe("enterprise GitHub and Vercel automation",()=>{
  it("defines the requested control-plane tables and atomic queue functions",async()=>{const sql=await readFile(new URL("supabase/migrations/0013_enterprise_automation_control_plane.sql",root),"utf8");for(const name of ["clients","repositories","deployments","deploy_logs","github_installations","vercel_projects","seo_jobs","automation_runs","webhook_events","background_jobs"])expect(sql).toContain(`public.${name}`);for(const fn of ["claim_background_jobs","enqueue_deployment_job","enqueue_rollback_job","consume_rate_limit","for update skip locked"])expect(sql.toLowerCase()).toContain(fn);});
  it("implements every public integration and deployment route",async()=>{for(const path of ["app/api/github/install/route.ts","app/api/github/setup/route.ts","app/api/github/connect/route.ts","app/api/github/webhook/route.ts","app/api/vercel/connect/route.ts","app/api/vercel/webhook/route.ts","app/api/deploy/route.ts","app/api/deploy/status/route.ts","app/api/deploy/rollback/route.ts"])expect(await readFile(new URL(path,root),"utf8")).toContain("export async function");});
  it("encrypts stored secrets and consumes verified GitHub authorization",async()=>{const encryption=await readFile(new URL("lib/security/encryption.ts",root),"utf8"),connect=await readFile(new URL("app/api/github/connect/route.ts",root),"utf8"),client=await readFile(new URL("lib/github/app-client.ts",root),"utf8");expect(encryption).toContain("aes-256-gcm");expect(client).toContain("/user/installations");expect(connect).toContain("integration_oauth_states");expect(connect).toContain(".delete()");});
  it("runs all required post-deployment validation without leaking protected-preview credentials",async()=>{const validator=await readFile(new URL("lib/automation/validator.ts",root),"utf8"),worker=await readFile(new URL("lib/automation/worker.ts",root),"utf8"),bypass=await readFile(new URL("lib/vercel/protection-bypass.ts",root),"utf8");for(const check of ["health","lighthouse","seo","schema","sitemap","robots","indexing_readiness"])expect(validator).toContain(`checkType:\"${check}\"`);expect(validator).toContain("x-vercel-protection-bypass");expect(validator).toContain("Protected preview credentials are never sent to external PageSpeed services");expect(validator).toContain("required:!preview");expect(validator).toContain("Protected previews are intentionally excluded from indexing");expect(worker).toContain("ensureVercelAutomationBypass");expect(worker).toContain("validationUrl");expect(bypass).toContain("encryptSecret(secret)");});
  it("exposes production GitHub settings and connection controls",async()=>{for(const path of ["app/portal/admin/settings/github/page.tsx","app/api/github/test/route.ts","app/api/github/disconnect/route.ts"]){const source=await readFile(new URL(path,root),"utf8");expect(source).toContain("GitHub");}const callback=await readFile(new URL("app/api/github/connect/route.ts",root),"utf8"),sidebar=await readFile(new URL("app/ui/admin-sidebar.tsx",root),"utf8"),panel=await readFile(new URL("app/ui/github-settings-panel.tsx",root),"utf8");expect(callback).toContain("settingsRedirect");expect(callback).toContain("saveRepositoryConnection");expect(sidebar).toContain("/portal/admin/settings/github");for(const label of ["GitHub Connected","INSTALLATION ID","CONNECTED REPOSITORIES","LAST WEBHOOK RECEIVED","Test Connection","Disconnect GitHub"])expect(panel).toContain(label);});
  it("binds GitHub installations through the signed Setup URL flow",async()=>{const install=await readFile(new URL("app/api/github/install/route.ts",root),"utf8"),setup=await readFile(new URL("app/api/github/setup/route.ts",root),"utf8"),binding=await readFile(new URL("lib/github/installation-binding.ts",root),"utf8"),state=await readFile(new URL("lib/security/signed-state.ts",root),"utf8");expect(install).toContain("/installations/new");expect(install).not.toContain("/settings/installations");expect(install).toContain('purpose:"github_install"');expect(install).toContain("findExistingInstallation");expect(install).toContain('purpose:"github_bind"');expect(install).toContain('setupAction:"existing"');for(const parameter of ["installation_id","setup_action","state"])expect(setup).toContain(parameter);expect(setup).toContain('verifyIntegrationState(parsed.data.state,"github_install")');expect(binding).toContain("getInstallation");expect(binding).toContain("listInstallationRepositories");expect(binding).toContain('from("github_installations").update');expect(binding).toContain('from("github_installations").insert');expect(state).toContain("returnUrl?: string");});
  it("provides secret-safe GitHub installation diagnostics",async()=>{const source=await readFile(new URL("app/api/github/diagnostics/route.ts",root),"utf8");for(const field of ["jwtWorks","installationFound","accountLogin","accessibleRepositories","installationSaved"])expect(source).toContain(field);for(const secret of ["GITHUB_APP_PRIVATE_KEY","GITHUB_WEBHOOK_SECRET","accessToken","installationToken"])expect(source).not.toContain(secret);});
  it("returns a mutable callback redirect and safe stage-specific errors",async()=>{const callback=await readFile(new URL("app/api/github/callback/route.ts",root),"utf8"),errors=await readFile(new URL("lib/api/errors.ts",root),"utf8");expect(callback).toContain("new Response(null,{status:303");expect(callback).not.toContain("response.headers.append");for(const code of ["INVALID_STATE","MISSING_INSTALLATION_ID","GITHUB_JWT_FAILED","INSTALLATION_LOOKUP_FAILED","REPOSITORY_NOT_AUTHORIZED","DATABASE_BINDING_FAILED"])expect(errors).toContain(code);});
  it("selects the uniquely matching repository for a client project",()=>{const repositories=[{id:1,name:"kingdom-roofing-website",full_name:"traeditto/kingdom-roofing-website",private:true,default_branch:"main",owner:{login:"traeditto"}},{id:2,name:"hdseo",full_name:"traeditto/hdseo",private:true,default_branch:"main",owner:{login:"traeditto"}}];expect(selectRepositoryForProject(repositories,{clientName:"Kingdom Roofing",projectName:"Primary SEO Project",domain:"kingdomroofing.com"})?.full_name).toBe("traeditto/kingdom-roofing-website");});
});
