import { describe,expect,it } from "vitest";
import { analyzePageOwnership } from "../lib/seo/page-ownership";
import { evaluateEligibility,opportunityKey,selectNextBestAction } from "../lib/seo/eligibility";
import { scoreOpportunity } from "../lib/seo/opportunity-engine";
import { evaluateBudget,freshnessState,modeCapabilities } from "../lib/seo/campaign-policy";
import { decideCheckpoint,cooldownDays } from "../lib/seo/monitoring";
import { normalizeEnvelope } from "../lib/providers/dataforseo/normalize";
import { validateApprovedFiles,approvedContent } from "../lib/execution/validation";

describe("cross-repository intelligence adaptation",()=>{
  it("detects ownership conflicts before BUILD work",()=>{const result=analyzePageOwnership("roof repair jacksonville",[{url:"/roof-repair",title:"Roof Repair Jacksonville",metaDescription:"Roof repair",canonical:"/roof-repair",assignedKeywords:["roof repair jacksonville"]},{url:"/jacksonville-roof-repair",title:"Roof Repair Jacksonville",metaDescription:"Roof repair",canonical:"/roof-repair"}]);expect(result.ownerPage?.url).toBe("/roof-repair");expect(result.conflictWarnings).toContain("KEYWORD_CANNIBALIZATION");expect(result.conflictWarnings).toContain("DUPLICATE_TITLE");});
  it("separates value scoring from safety eligibility",()=>{const result=scoreOpportunity({currentRank:6,previousRank:8,searchVolume:1100,cpc:38,commercialIntentScore:95,serviceRelevance:90,locationRelevance:90,competitorGap:80,technicalReadiness:85,hasOwnerPage:true,internalLinkCount:6});const eligibility=evaluateEligibility({projectId:"p",keyword:"roof repair",targetUrl:"/roof-repair",result,pageConflict:true});expect(result.opportunityScore).toBeGreaterThan(75);expect(eligibility.eligible).toBe(false);expect(eligibility.reasons).toContain("PAGE_OWNERSHIP_CONFLICT");});
  it("blocks deterministic keyword-quality failures",()=>{const result=scoreOpportunity({currentRank:6,searchVolume:1100,cpc:38,commercialIntentScore:95,serviceRelevance:90,locationRelevance:90,hasOwnerPage:false});const eligibility=evaluateEligibility({projectId:"p",keyword:"roof roofing company",result,disqualifiers:["REDUNDANT_QUERY"]});expect(eligibility.eligible).toBe(false);expect(eligibility.reasons).toContain("REDUNDANT_QUERY");});
  it("uses deterministic keys and confidence-adjusted selection",()=>{expect(opportunityKey("p"," Roof  Repair ","/roof","IMPROVE")).toBe("p|roof repair|/roof|IMPROVE");expect(selectNextBestAction([{opportunityId:"a",score:95,confidence:40,eligible:true},{opportunityId:"b",score:85,confidence:90,eligible:true}])?.opportunityId).toBe("b");});
  it("never grants merge or publish capability",()=>{for(const mode of ["MONITOR","RECOMMEND","PREPARE","EXECUTE_WITH_APPROVAL"] as const){expect(modeCapabilities(mode).canMerge).toBe(false);expect(modeCapabilities(mode).canPublish).toBe(false);}});
  it("enforces real estimated budget and freshness",()=>{expect(evaluateBudget({status:"active",monthlyBudget:100,dailyLimit:20,runLimit:10,monthSpend:99,daySpend:0,estimatedCost:2,paidEnabled:true}).allowed).toBe(false);expect(freshnessState("2026-07-10T00:00:00Z",7,new Date("2026-07-12T00:00:00Z"))).toBe("fresh");});
  it("makes milestone, decline, technical and inconclusive monitoring decisions",()=>{expect(decideCheckpoint({checkpointDay:30,baseline:6,position:3,rankingUrl:"/roof",targetUrl:"/roof",targetMilestone:"Top 3",fresh:true})).toBe("MILESTONE_REACHED");expect(decideCheckpoint({checkpointDay:30,baseline:6,position:12,rankingUrl:"/roof",targetUrl:"/roof",fresh:true})).toBe("DECLINED");expect(decideCheckpoint({checkpointDay:14,baseline:6,position:7,rankingUrl:"/other",targetUrl:"/roof",fresh:true})).toBe("TECHNICAL_CHECK");expect(decideCheckpoint({checkpointDay:7,baseline:6,position:null,rankingUrl:null,targetUrl:"/roof",fresh:false})).toBe("INCONCLUSIVE");expect(cooldownDays("BUILD")).toBe(60);});
  it("normalizes provider costs and rejects task failures",()=>{expect(normalizeEnvelope({status_code:20000,status_message:"Ok",cost:.08,tasks:[{id:"t",status_code:20000,status_message:"Ok",result_count:1,result:[{keyword:"roof"}]}]}).totalCost).toBe(.08);expect(()=>normalizeEnvelope({status_code:20000,status_message:"Ok",tasks:[{status_code:40501,status_message:"Invalid field",result:[]}]})).toThrow(/Invalid field/);});
  it("protects human edits and validates approved files",()=>{const file={file_path:"app/page.tsx",change_type:"MODIFY_FILE",original_sha:"abc",proposed_content:"generated",human_edited_content:"human",approved_content:null,status:"approved"};expect(approvedContent(file)).toBe("human");expect(validateApprovedFiles([file]).passed).toBe(true);expect(validateApprovedFiles([{...file,proposed_content:"SUPABASE_SERVICE_ROLE_KEY=secret",human_edited_content:null}]).passed).toBe(false);});
});
