import { describe,expect,it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");
describe("live HD SEO product",()=>{
  it("uses Supabase-backed durable storage for the live portal",()=>{const store=read("lib/live/store.ts");expect(store).toContain('from "@/lib/live/identity"');expect(store).toContain("getLiveAdminClient");for(const table of ["client_organizations","seo_projects","seo_opportunities","seo_tasks","implementation_packages","proof_of_work_events"])expect(store).toContain(table);const identity=read("lib/live/identity.ts");expect(identity).toContain("auth.admin");expect(identity).toContain("platform_admins");});
  it("protects every real portal through the shared role-aware identity resolver",()=>{for(const portal of ["admin","agency","client"])expect(read(`app/portal/${portal}/page.tsx`)).toContain("requirePortalUser");const resolver=read("lib/auth/portal-user.ts");expect(resolver).toContain("resolvePortalAccess");expect(resolver).toContain("requireChatGPTUser");});
  it("supports production Supabase login and protected hosted identity without demo access",()=>{const login=read("app/ui/portal-login.tsx");expect(login).toContain("Continue with ChatGPT");expect(login).toContain("signInWithPassword");expect(login).not.toContain("Preview portal");});
  it("supports self-serve agency signup and first-workspace onboarding",()=>{const login=read("app/ui/portal-login.tsx"),access=read("lib/auth/portal-access.ts");expect(login).toContain("signUp");expect(login).toContain("Create a new agency account");expect(access).toContain('role:"onboarding"');});
  it("keeps live writes server-authorized and tenant-scoped",()=>{const route=read("app/api/live/route.ts");expect(route).toContain("getChatGPTUser");const store=read("lib/live/store.ts");expect(store).toContain("requireAgency");expect(store).toContain('.eq("agency_id", agencyId)');expect(store).toContain("Client approval access denied");});
  it("enforces live action permissions, rate limits, and client approval roles",()=>{const route=read("app/api/live/route.ts"),store=read("lib/live/store.ts");expect(route).toContain("enforceRateLimit");for(const permission of ["clients.manage","provider.authorize","seo.write","client_portal.manage","execution.approve"])expect(store).toContain(`requireLivePermission(role, "${permission}`);expect(store).toContain('["client_admin", "client_approver"]');expect(store).toContain("client_portal_publications");});
  it("queues and reviews durable campaign work after zero-input keyword discovery",()=>{const store=read("lib/live/store.ts"),dashboard=read("app/ui/live-agency-dashboard.tsx");expect(store).toContain('.from("seo_campaign_jobs")');expect(store).toContain('current_stage: "discover"');expect(store).toContain("reviewCampaignJob");expect(store).toContain("createManualPackage");expect(dashboard).toContain('"Automation"');expect(dashboard).toContain('action:"control_job"');expect(dashboard).toContain('action:"review_job"');});
  it("requires proof and independent live checks before scheduling manual monitoring",()=>{const store=read("lib/live/store.ts"),dashboard=read("app/ui/live-agency-dashboard.tsx"),verification=read("lib/manual/live-verification.ts");expect(store).toContain("verifyLiveImplementation");expect(store).toContain("implementation_verifications");expect(store).toContain("create_manual_monitoring_plan");expect(dashboard).toContain("AUTOMATED LIVE VERIFICATION");expect(dashboard).not.toContain("Confirm every safety check");expect(verification).toContain("inspectPublicPage");});
  it("allows verified agency users to complete first-run setup without auto-promoting admins",()=>{const access=read("lib/auth/portal-access.ts"),identity=read("lib/live/identity.ts");expect(access).toContain('role:"onboarding"');expect(identity).not.toContain("the first resolved user becomes");expect(identity).toContain("platformAdminEmails.has(email)");expect(identity).not.toContain('role: "client_owner"');});
  it("ships explicit browser security headers",()=>{const config=read("next.config.ts");for(const header of ["Content-Security-Policy","X-Frame-Options","X-Content-Type-Options","Referrer-Policy","Permissions-Policy"])expect(config).toContain(header);});
  it("supports Vercel without loading Cloudflare virtual modules",()=>{const vercel=JSON.parse(read("vercel.json")),database=read("db/index.ts");expect(vercel.buildCommand).toBe("pnpm run build:vercel");expect(database).not.toContain('from "cloudflare:workers"');expect(read("package.json")).toContain('"build:vercel": "next build"');});
  it("keeps Vercel portal traffic on the canonical production application",()=>{const resolver=read("lib/auth/portal-user.ts");expect(resolver).toContain("process.env.VERCEL");expect(resolver).toContain("resolvePortalAccess");for(const portal of ["admin","agency","client"]){const source=read(`app/portal/${portal}/page.tsx`);expect(source).not.toContain("HD_SEO_LIVE_ORIGIN");}});
});
