import{readFileSync}from"node:fs";
import{join}from"node:path";
import{describe,expect,it}from"vitest";
import{isSafeAuthorityOpportunity,normalizeBuyerQuestion,phaseForSequence,publicAuditReport,semanticOverlap}from"../lib/growth/core";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");

describe("Local Growth Engine",()=>{
  it("stores every compounding-growth surface behind tenant RLS",()=>{const sql=read("supabase/migrations/0021_local_growth_engine.sql");for(const table of["brand_profiles","growth_plans","growth_plan_items","internal_link_edges","content_refresh_candidates","ai_visibility_prompts","ai_visibility_snapshots","authority_opportunities","growth_tool_specs","case_study_snapshots"]){expect(sql).toContain(`public.${table}`);expect(sql).toContain(`'${table}'`)}expect(sql).toContain("has_client_access");expect(sql).toContain("revoke insert,update,delete");expect(sql).toContain('"forbidAutomatedLinkExchange":true')});
  it("builds the shared tools into the bounded agent registry",()=>{const sql=read("supabase/migrations/0021_local_growth_engine.sql");for(const tool of["brand.profile","growth.plan","internal_links.graph","content.refresh","ai_visibility.observe","authority.research","growth_tool.spec","proof.case_study"])expect(sql).toContain(`'${tool}'`)});
  it("normalizes buyer questions and schedules all three roadmap phases",()=>{expect(normalizeBuyerQuestion("  Best Roofer Near Me?? ")).toBe("best roofer near me");expect([phaseForSequence(1),phaseForSequence(6),phaseForSequence(13)]).toEqual([30,60,90])});
  it("blocks manipulative authority tactics",()=>{expect(isSafeAuthorityOpportunity("Jacksonville builders association directory","Submit verified member profile")).toBe(true);expect(isSafeAuthorityOpportunity("Partner page","Offer a reciprocal link exchange")).toBe(false);expect(isSafeAuthorityOpportunity("Buy a link on a PBN")).toBe(false)});
  it("finds meaningful internal-link similarity",()=>{expect(semanticOverlap("Jacksonville roof repair guide","Roof repair services in Jacksonville")).toBeGreaterThan(30);expect(semanticOverlap("roof repair","commercial landscaping")).toBe(0)});
  it("returns a transparent, non-guaranteed public audit",()=>{const report=publicAuditReport([{url:"https://example.com",title:"Home",h1:"Roofing",metaDescription:null,indexable:true,schemaTypes:[],internalLinks:[]},{url:"https://example.com/repair",title:null,h1:null,metaDescription:null,indexable:true,schemaTypes:[],internalLinks:[]}],{service:"Roof repair",serviceArea:"Jacksonville, FL"});expect(report.score).toBeLessThan(100);expect(report.context).toBe("Roof repair in Jacksonville, FL");expect(report.findings.map(item=>item.code)).toEqual(expect.arrayContaining(["MISSING_TITLE","MISSING_H1","MISSING_META","NO_SCHEMA"]));expect(report.limitations.join(" ")).toContain("not a ranking guarantee")});
  it("exposes the workspace and public audit in the product UI",()=>{expect(read("app/ui/live-agency-dashboard.tsx")).toContain('"Local Growth"');expect(read("app/ui/local-growth-engine.tsx")).toContain("Win the market, not just a keyword");expect(read("app/page.tsx")).toContain('href="/audit"');expect(read("app/api/growth/route.ts")).toContain("requireLiveAgencyProject");expect(read("app/api/public/audit/route.ts")).toContain("enforceRateLimit")});
});
