import{readFileSync}from"node:fs";
import{join}from"node:path";
import{describe,expect,it}from"vitest";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");

describe("outcomes, attribution, and working budgets",()=>{
  it("stores real cost, outcome, local, citation, and outreach evidence per tenant",()=>{const sql=read("supabase/migrations/0024_outcomes_attribution_and_local_operations.sql");for(const table of["project_budget_accounts","project_budget_allocations","project_budget_transactions","analytics_daily_metrics","attribution_touchpoints","local_business_profiles","local_reviews","local_profile_change_requests","citation_listings","authority_outreach_actions","provider_sync_runs"])expect(sql).toContain(`public.${table}`);expect(sql).toContain("has_client_access");expect(sql).toContain("idempotency_key");});
  it("keeps Google local writes approval gated",()=>{const route=read("app/api/local/actions/route.ts"),sql=read("supabase/migrations/0024_outcomes_attribution_and_local_operations.sql");expect(route).toContain('eq("status","approved")');expect(route).toContain("confirm:z.literal(true)");expect(route).toContain('permission:publishing?"execution.approve"');expect(sql).toContain("awaiting_approval");});
  it("encrypts provider tokens and never returns them in workspace snapshots",()=>{const provider=read("lib/providers/attribution.ts"),service=read("lib/outcomes/service.ts");expect(provider).toContain("encryptSecret");expect(provider).toContain("encrypted_secret_reference");expect(service).not.toContain('select("encrypted_secret_reference');});
  it("protects attribution webhooks from replay and duplicate ingestion",()=>{const webhook=read("app/api/webhooks/attribution/[provider]/route.ts");expect(webhook).toContain("timingSafeEqual");expect(webhook).toContain("WEBHOOK_REPLAY_REJECTED");expect(webhook).toContain('eq("delivery_id",eventId)');expect(webhook).toContain("ATTRIBUTION_WEBHOOK_SECRET");});
  it("exposes one honest results and budget workspace to agencies and owners",()=>{const workspace=read("app/ui/outcomes-control-center.tsx"),agency=read("app/ui/live-agency-dashboard.tsx"),client=read("app/ui/live-client-dashboard.tsx");expect(workspace).toContain("Directional search value is kept separate from revenue");expect(workspace).toContain("Saving a budget does not charge the customer or authorize a purchase");expect(agency).toContain('"Results & budget"');expect(client).toContain("OutcomesControlCenter");});
  it("preserves valid OAuth bindings when Google resource discovery is retryable",()=>{const callback=read("app/api/google-suite/callback/route.ts"),suite=read("lib/google/suite.ts"),worker=read("lib/outcomes/worker.ts"),workspace=read("app/ui/outcomes-control-center.tsx");expect(callback).toContain('health:"discovery_pending"');expect(suite).toContain('operation:"resource_discovery"');expect(worker).toContain("discoverSuiteResources");expect(workspace).toContain("Retry discovery");expect(workspace).toContain('encodeURIComponent("/portal/agency?tab=Results%20%26%20budget")');});
  it("reconciles onboarding budgets into the enforceable hard-stop ledger",()=>{const sql=read("supabase/migrations/0032_budget_attribution_reconciliation.sql"),service=read("lib/outcomes/service.ts");expect(sql).toContain("reconcile_project_working_budget");expect(sql).toContain("hard_stop=true");expect(sql).toContain("from public.client_growth_profiles");expect(service).toContain('update({monthly_budget:input.monthlyLimit');});
  it("uses provider-correct authentication and bounded resumable attribution syncs",()=>{const provider=read("lib/providers/attribution.ts");expect(provider).toContain("Token token=");expect(provider).toContain("`Bearer ${token}`");expect(provider).toContain("MAX_PROVIDER_PAGES = 20");expect(provider).toContain("safeCallRailNextPage");expect(provider).toContain("syncCursor");expect(provider).toContain("lastmodifieddate");});
  it("uses a rotatable read-only HubSpot Service Key without deleting the live connection first",()=>{const provider=read("lib/providers/attribution.ts"),workspace=read("app/ui/outcomes-control-center.tsx");expect(provider).toContain('input.provider === "hubspot" ? "service_key"');expect(provider).toContain('"crm.objects.contacts.read"');expect(workspace).toContain("Replace HubSpot Service Key");expect(workspace).toContain("HubSpot Service Key");});
  it("reports attribution readiness from client connections and successful evidence, not a global secret alone",()=>{const readiness=read("lib/readiness/platform-readiness.ts"),dashboard=read("app/ui/system-readiness-dashboard.tsx");expect(readiness).toContain("attributionConnections");expect(readiness).toContain("attributionSyncs");expect(readiness).toContain("attributedLeadCount");expect(dashboard).toContain("system-check-action");});
  it("keeps provider lead upserts idempotent and preserves the submitted form across awaits",()=>{const sql=read("supabase/migrations/0033_provider_lead_ingestion_reliability.sql"),workspace=read("app/ui/outcomes-control-center.tsx");expect(sql).toContain("create unique index seo_leads_external_identity");expect(sql).not.toContain("where external_id is not null");expect(workspace).toContain("const formElement=event.currentTarget");expect(workspace).toContain("formElement.reset()");});
});
