import{readFileSync}from"node:fs";
import{join}from"node:path";
import{describe,expect,it}from"vitest";
import{nextProviderSyncAt,providerResourceNeedsDiscovery,providerSyncBackoffMs}from"../lib/outcomes/provider-health";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");

describe("provider synchronization resilience",()=>{
  it("uses bounded exponential retry delays",()=>{expect(providerSyncBackoffMs(1)).toBe(5*60*1000);expect(providerSyncBackoffMs(2)).toBe(15*60*1000);expect(providerSyncBackoffMs(3)).toBe(60*60*1000);expect(providerSyncBackoffMs(99)).toBe(6*60*60*1000);expect(nextProviderSyncAt(new Date("2026-01-01T00:00:00Z"),1)).toBe("2026-01-01T00:05:00.000Z");});
  it("recovers missing Google resources before attempting data synchronization",()=>{expect(providerResourceNeedsDiscovery({provider:"google_analytics",selected_resource:null,metadata:{health:"discovery_pending"}})).toBe(true);expect(providerResourceNeedsDiscovery({provider:"google_business_profile",selected_resource:"locations/1",metadata:{health:"ready"}})).toBe(true);expect(providerResourceNeedsDiscovery({provider:"google_business_profile",selected_resource:"locations/1",metadata:{health:"ready",selectedAccount:"accounts/1"}})).toBe(false);expect(providerResourceNeedsDiscovery({provider:"hubspot",selected_resource:null})).toBe(false);});
  it("persists retry state and reports provider failures to the scheduler",()=>{const migration=read("supabase/migrations/0045_provider_sync_resilience.sql"),worker=read("lib/outcomes/worker.ts"),cron=read("app/api/cron/automation/route.ts"),readiness=read("lib/readiness/platform-readiness.ts");for(const column of["last_sync_attempt_at","next_sync_at","consecutive_sync_failures","last_sync_error_code"])expect(migration).toContain(column);expect(worker).toContain("discoverSuiteResources");expect(worker).toContain('status:"selection_required"');expect(worker).toContain("nextProviderSyncAt");expect(cron).toContain("outcomesFailed");expect(readiness).toContain("gbpReady");expect(readiness).toContain("last_sync_error_code");});
  it("backs off immediately when Google reports a quota limit",()=>{const google=read("lib/google/search-console.ts"),readiness=read("lib/readiness/platform-readiness.ts");expect(google).toContain('response.status===429)throw new ApiError');expect(google).toContain('503,"RATE_LIMITED"');expect(google).toContain("response.status>=500&&attempt<2");expect(readiness).toContain("Google has temporarily limited Business Profile requests");});
});
