import "server-only";
import { and,desc,eq,inArray } from "drizzle-orm";
import { getD1Binding,getDb } from "@/db";
import * as schema from "@/db/schema";
import type { ChatGPTUser } from "@/app/chatgpt-auth";
import { ApiError } from "@/lib/api/errors";

const statements=[
  `create table if not exists live_users(email text primary key,display_name text not null,platform_role text,created_at text not null,updated_at text not null)`,
  `create table if not exists live_agencies(id text primary key,name text not null,slug text not null unique,owner_email text not null references live_users(email),created_at text not null)`,
  `create table if not exists live_agency_members(id text primary key,agency_id text not null references live_agencies(id) on delete cascade,user_email text not null references live_users(email) on delete cascade,role text not null,created_at text not null,unique(agency_id,user_email))`,
  `create index if not exists live_agency_member_email on live_agency_members(user_email)`,
  `create table if not exists live_clients(id text primary key,agency_id text not null references live_agencies(id) on delete cascade,name text not null,domain text not null,contact_email text,status text not null default 'active',created_at text not null)`,
  `create index if not exists live_clients_agency on live_clients(agency_id)`,
  `create table if not exists live_client_members(id text primary key,client_id text not null references live_clients(id) on delete cascade,user_email text not null references live_users(email) on delete cascade,role text not null,created_at text not null,unique(client_id,user_email))`,
  `create table if not exists live_projects(id text primary key,agency_id text not null references live_agencies(id) on delete cascade,client_id text not null references live_clients(id) on delete cascade,name text not null,domain text not null,status text not null default 'active',created_at text not null)`,
  `create index if not exists live_projects_agency on live_projects(agency_id)`,
  `create index if not exists live_projects_client on live_projects(client_id)`,
  `create table if not exists live_opportunities(id text primary key,agency_id text not null references live_agencies(id) on delete cascade,project_id text not null references live_projects(id) on delete cascade,keyword text not null,current_rank integer,target_rank integer not null default 10,score integer not null,action_type text not null,reason text not null,status text not null default 'open',created_at text not null)`,
  `create index if not exists live_opportunities_project on live_opportunities(project_id)`,
  `create index if not exists live_opportunities_agency on live_opportunities(agency_id)`,
  `create table if not exists live_tasks(id text primary key,agency_id text not null references live_agencies(id) on delete cascade,project_id text not null references live_projects(id) on delete cascade,opportunity_id text references live_opportunities(id) on delete set null,title text not null,status text not null default 'ready',priority text not null default 'medium',assigned_email text,implementation_path text,created_at text not null,updated_at text not null)`,
  `create index if not exists live_tasks_agency on live_tasks(agency_id)`,
  `create index if not exists live_tasks_project on live_tasks(project_id)`,
  `create table if not exists live_packages(id text primary key,agency_id text not null references live_agencies(id) on delete cascade,project_id text not null references live_projects(id) on delete cascade,opportunity_id text not null references live_opportunities(id) on delete cascade,title text not null,implementation_path text not null,status text not null default 'agency_review',package_data text not null,created_at text not null,updated_at text not null)`,
  `create index if not exists live_packages_agency on live_packages(agency_id)`,
  `create index if not exists live_packages_project on live_packages(project_id)`,
  `create table if not exists live_events(id text primary key,agency_id text not null references live_agencies(id) on delete cascade,project_id text references live_projects(id) on delete cascade,event_type text not null,title text not null,description text,actor_email text not null,client_visible integer not null default 0,created_at text not null)`,
  `create index if not exists live_events_agency on live_events(agency_id)`,
  `create index if not exists live_events_project on live_events(project_id)`
];

export async function ensureLiveSchema(){let d1:D1Database;try{d1=getD1Binding();}catch{throw new ApiError("The HD SEO database is hosted on the primary Sites deployment.",503,"NOT_CONFIGURED");}await d1.batch(statements.map(sql=>d1.prepare(sql)));}
export async function upsertLiveUser(user:ChatGPTUser){await ensureLiveSchema();const db=getDb(),now=new Date().toISOString(),email=user.email.toLowerCase();await db.insert(schema.liveUsers).values({email,displayName:user.displayName,createdAt:now,updatedAt:now}).onConflictDoUpdate({target:schema.liveUsers.email,set:{displayName:user.displayName,updatedAt:now}});const owners=await db.select({email:schema.liveUsers.email}).from(schema.liveUsers).where(eq(schema.liveUsers.platformRole,"platform_owner")).limit(1);if(!owners.length)await db.update(schema.liveUsers).set({platformRole:"platform_owner",updatedAt:now}).where(eq(schema.liveUsers.email,email));const matchingClients=await db.select({id:schema.liveClients.id}).from(schema.liveClients).where(eq(schema.liveClients.contactEmail,email));for(const client of matchingClients)await db.insert(schema.liveClientMembers).values({id:crypto.randomUUID(),clientId:client.id,userEmail:email,role:"client_approver",createdAt:now}).onConflictDoNothing();return (await db.select().from(schema.liveUsers).where(eq(schema.liveUsers.email,email)).limit(1))[0];}
export async function createAgencyForUser(email:string,name:string){const db=getDb(),now=new Date().toISOString(),id=crypto.randomUUID(),slug=`${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"agency"}-${id.slice(0,6)}`;await db.batch([db.insert(schema.liveAgencies).values({id,name,slug,ownerEmail:email,createdAt:now}),db.insert(schema.liveAgencyMembers).values({id:crypto.randomUUID(),agencyId:id,userEmail:email,role:"agency_owner",createdAt:now})]);return id;}
export async function agencyMembership(email:string){const db=getDb();return (await db.select({agency:schema.liveAgencies,role:schema.liveAgencyMembers.role}).from(schema.liveAgencyMembers).innerJoin(schema.liveAgencies,eq(schema.liveAgencyMembers.agencyId,schema.liveAgencies.id)).where(eq(schema.liveAgencyMembers.userEmail,email)).limit(1))[0]??null;}
export async function requireAgency(email:string){const membership=await agencyMembership(email);if(!membership)throw new ApiError("Create or join an agency workspace first.",403,"TENANT_DENIED");return membership;}
export async function liveAgencySnapshot(email:string){const membership=await agencyMembership(email);if(!membership)return{agency:null,role:null,clients:[],projects:[],opportunities:[],tasks:[],packages:[],events:[]};const db=getDb(),agencyId=membership.agency.id;const [clients,projects,opportunities,tasks,packages,events]=await Promise.all([db.select().from(schema.liveClients).where(eq(schema.liveClients.agencyId,agencyId)).orderBy(desc(schema.liveClients.createdAt)),db.select().from(schema.liveProjects).where(eq(schema.liveProjects.agencyId,agencyId)).orderBy(desc(schema.liveProjects.createdAt)),db.select().from(schema.liveOpportunities).where(eq(schema.liveOpportunities.agencyId,agencyId)).orderBy(desc(schema.liveOpportunities.score)),db.select().from(schema.liveTasks).where(eq(schema.liveTasks.agencyId,agencyId)).orderBy(desc(schema.liveTasks.updatedAt)),db.select().from(schema.livePackages).where(eq(schema.livePackages.agencyId,agencyId)).orderBy(desc(schema.livePackages.updatedAt)),db.select().from(schema.liveEvents).where(eq(schema.liveEvents.agencyId,agencyId)).orderBy(desc(schema.liveEvents.createdAt)).limit(100)]);return{agency:membership.agency,role:membership.role,clients,projects,opportunities,tasks,packages:packages.map(item=>({...item,packageData:JSON.parse(item.packageData)})),events};}
export async function liveClientSnapshot(email:string){const db=getDb();const matches=await db.select({client:schema.liveClients,role:schema.liveClientMembers.role}).from(schema.liveClientMembers).innerJoin(schema.liveClients,eq(schema.liveClientMembers.clientId,schema.liveClients.id)).where(eq(schema.liveClientMembers.userEmail,email));if(!matches.length)return{clients:[],projects:[],opportunities:[],packages:[],events:[]};const clientIds=matches.map(item=>item.client.id),projects=await db.select().from(schema.liveProjects).where(inArray(schema.liveProjects.clientId,clientIds)),projectIds=projects.map(item=>item.id);if(!projectIds.length)return{clients:matches,projects,opportunities:[],packages:[],events:[]};const [opportunities,packages,events]=await Promise.all([db.select().from(schema.liveOpportunities).where(inArray(schema.liveOpportunities.projectId,projectIds)).orderBy(desc(schema.liveOpportunities.score)),db.select().from(schema.livePackages).where(and(inArray(schema.livePackages.projectId,projectIds),inArray(schema.livePackages.status,["client_review","client_approved","implemented","verified"]))).orderBy(desc(schema.livePackages.updatedAt)),db.select().from(schema.liveEvents).where(and(inArray(schema.liveEvents.projectId,projectIds),eq(schema.liveEvents.clientVisible,true))).orderBy(desc(schema.liveEvents.createdAt)).limit(100)]);return{clients:matches,projects,opportunities,packages:packages.map(item=>({...item,packageData:JSON.parse(item.packageData)})),events};}
export async function liveAdminSnapshot(email:string){const db=getDb(),user=(await db.select().from(schema.liveUsers).where(eq(schema.liveUsers.email,email)).limit(1))[0];if(user?.platformRole!=="platform_owner")throw new ApiError("Platform administration access denied.",403,"ROLE_FORBIDDEN");const [agencies,clients,projects,users]=await Promise.all([db.select().from(schema.liveAgencies),db.select().from(schema.liveClients),db.select().from(schema.liveProjects),db.select().from(schema.liveUsers)]);return{agencies,clients,projects,users};}
