import {z} from "zod";
import {ApiError,jsonError} from "@/lib/api/errors";
import {parseJson} from "@/lib/api/request";
import {requireLiveAgencyProject} from "@/lib/auth/live-tenant";
import {appBaseUrl,env} from "@/lib/config/env";
import {agentCapacityAddOn} from "@/lib/agent-service/catalog";

const schema=z.object({projectId:z.string().uuid(),units:z.number().int().min(1).max(20).default(1)});
export async function POST(request:Request){try{const input=await parseJson(request,schema),context=await requireLiveAgencyProject({projectId:input.projectId,permission:"billing.manage"});if(!env.STRIPE_SECRET_KEY||!env.STRIPE_PRICE_AGENT_CAPACITY)throw new ApiError("Managed-service capacity checkout is not configured.",503,"NOT_CONFIGURED");const enrollment=await context.db.from("agent_service_enrollments").select("id,stripe_customer_id").eq("project_id",input.projectId).maybeSingle();if(!enrollment.data)throw new ApiError("Enroll this project in managed agent service first.",409,"CONFLICT");let customerId=enrollment.data.stripe_customer_id as string|null;if(!customerId){const subscription=context.actorType==="agency"?await context.db.from("agency_subscriptions").select("stripe_customer_id").eq("agency_id",context.agencyId).maybeSingle():await context.db.from("client_subscriptions").select("stripe_customer_id").eq("project_id",input.projectId).maybeSingle();customerId=subscription.data?.stripe_customer_id??null;}const body=new URLSearchParams({mode:"payment",success_url:`${appBaseUrl()}/${context.actorType==="agency"?"portal/agency?tab=Agent%20Service":"portal/client?agentService=capacity-added"}`,cancel_url:`${appBaseUrl()}/${context.actorType==="agency"?"portal/agency?tab=Agent%20Service":"portal/client"}`,"line_items[0][price]":env.STRIPE_PRICE_AGENT_CAPACITY,"line_items[0][quantity]":String(input.units),"metadata[kind]":"agent_capacity","metadata[enrollment_id]":enrollment.data.id,"metadata[project_id]":input.projectId,"metadata[capacity_units]":String(input.units),"metadata[unit_price_cents]":String(agentCapacityAddOn.priceCents),"metadata[provider_budget_per_unit]":String(agentCapacityAddOn.providerBudgetPerAction)});if(customerId)body.set("customer",customerId);else body.set("customer_email",context.email);const response=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,"content-type":"application/x-www-form-urlencoded"},body}),payload=await response.json() as {url?:string;error?:{message?:string}};if(!response.ok||!payload.url)throw new ApiError(payload.error?.message??"Stripe could not create capacity checkout.",502,"BILLING_PROVIDER_FAILED");return Response.json({ok:true,url:payload.url});}catch(error){return jsonError(error);}}
