import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { ApiError } from "@/lib/api/errors";
import { decryptSecret,encryptSecret } from "@/lib/security/encryption";
import { ingestLead } from "@/lib/outcomes/service";

type Tenant={agencyId:string;clientId:string;projectId:string;userId:string|null};
async function providerFetch<T>(url:string,token:string,init:RequestInit={}){const response=await fetch(url,{...init,headers:{accept:"application/json",authorization:`Bearer ${token}`,...init.headers},cache:"no-store"}),body=await response.json().catch(()=>null) as T|null;if(!response.ok||!body)throw new ApiError(response.status===401?"The provider credentials were rejected.":"The attribution provider could not be reached.",response.status===401?401:502,"OPERATION_FAILED");return body;}

export async function verifyAttributionCredentials(provider:"callrail"|"hubspot",credentials:{token:string;accountId?:string}){if(provider==="callrail"){const account=credentials.accountId;if(!account)throw new ApiError("A CallRail account ID is required.",400,"VALIDATION_ERROR");const result=await providerFetch<{accounts?:Array<{id?:number;name?:string}>}>("https://api.callrail.com/v3/a.json",credentials.token);if(!(result.accounts??[]).some(item=>String(item.id)===account))throw new ApiError("The CallRail token cannot access that account.",403,"ROLE_FORBIDDEN");return{externalAccountId:account,accountName:result.accounts?.find(item=>String(item.id)===account)?.name??account};}const result=await providerFetch<{portalId?:number;hubId?:number;user?:string}>("https://api.hubapi.com/integrations/v1/me",credentials.token);return{externalAccountId:String(result.portalId??result.hubId??"hubspot"),accountName:result.user??"HubSpot"};}

export async function saveAttributionConnection(db:SupabaseClient,tenant:Tenant,input:{provider:"callrail"|"hubspot";token:string;accountId?:string}){const verified=await verifyAttributionCredentials(input.provider,input),now=new Date().toISOString(),saved=await db.from("integration_connections").upsert({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,provider:input.provider,connection_type:"api_token",status:"active",external_account_id:verified.externalAccountId,selected_resource:input.accountId??verified.externalAccountId,encrypted_secret_reference:encryptSecret(JSON.stringify({token:input.token,accountId:input.accountId})),scopes:["read:outcomes"],last_verified_at:now,metadata:{accountName:verified.accountName,health:"ready",connectedAt:now},updated_at:now},{onConflict:"project_id,provider"}).select("id").single();if(saved.error||!saved.data)throw new ApiError("The attribution connection could not be saved.",500,"DATABASE_BINDING_FAILED");return{id:saved.data.id,...verified};}

export async function syncAttributionConnection(db:SupabaseClient,tenant:Tenant,provider:"callrail"|"hubspot"){
  const connection=await db.from("integration_connections").select("id,encrypted_secret_reference,selected_resource").eq("agency_id",tenant.agencyId).eq("client_organization_id",tenant.clientId).eq("project_id",tenant.projectId).eq("provider",provider).eq("status","active").maybeSingle();if(!connection.data?.encrypted_secret_reference)throw new ApiError(`Connect ${provider==="callrail"?"CallRail":"HubSpot"} first.`,409,"NOT_CONFIGURED");let secret:{token:string;accountId?:string};try{secret=JSON.parse(decryptSecret(connection.data.encrypted_secret_reference)) as typeof secret}catch{throw new ApiError("Reconnect the attribution provider because its stored authorization is invalid.",409,"NOT_CONFIGURED")}
  const run=await db.from("provider_sync_runs").insert({agency_id:tenant.agencyId,client_organization_id:tenant.clientId,project_id:tenant.projectId,connection_id:connection.data.id,provider,operation:"leads_and_revenue"}).select("id").single();let written=0;
  try{if(provider==="callrail"){const account=secret.accountId??connection.data.selected_resource,start=new Date(Date.now()-90*86400000).toISOString().slice(0,10),result=await providerFetch<{calls?:Array<Record<string,unknown>>}>(`https://api.callrail.com/v3/a/${encodeURIComponent(String(account))}/calls.json?start_date=${start}&fields=id,start_time,source,medium,landing_page_url,keywords,qualified,customer_status,duration,tracking_phone_number`,secret.token);for(const call of result.calls??[]){await ingestLead(db,tenant,{source:"callrail",externalId:String(call.id),landingPageUrl:typeof call.landing_page_url==="string"?call.landing_page_url:undefined,query:typeof call.keywords==="string"?call.keywords:undefined,leadType:"call",status:String(call.customer_status??"completed"),qualified:call.qualified===true,occurredAt:String(call.start_time??new Date().toISOString()),metadata:{source:call.source,medium:call.medium,duration:call.duration,trackingPhoneNumber:call.tracking_phone_number}});written++;}}else{const result=await providerFetch<{results?:Array<{id:string;properties?:Record<string,string>;createdAt?:string;updatedAt?:string}>}>("https://api.hubapi.com/crm/v3/objects/contacts?limit=100&archived=false&properties=lifecyclestage,hs_analytics_source,hs_analytics_first_url,createdate,lastmodifieddate",secret.token);for(const contact of result.results??[]){const p=contact.properties??{},stage=p.lifecyclestage??"lead";await ingestLead(db,tenant,{source:"hubspot",externalId:contact.id,landingPageUrl:p.hs_analytics_first_url||undefined,leadType:"form",status:stage,qualified:["salesqualifiedlead","opportunity","customer"].includes(stage),occurredAt:p.createdate??contact.createdAt??new Date().toISOString(),metadata:{analyticsSource:p.hs_analytics_source,lastModified:p.lastmodifieddate??contact.updatedAt}});written++;}}
    await db.from("provider_sync_runs").update({status:"succeeded",records_read:written,records_written:written,completed_at:new Date().toISOString()}).eq("id",run.data?.id);await db.from("integration_connections").update({last_synced_at:new Date().toISOString(),last_verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",connection.data.id);return{provider,records:written};
  }catch(error){await db.from("provider_sync_runs").update({status:"failed",error_code:"PROVIDER_SYNC_FAILED",error_message:"Attribution synchronization failed.",completed_at:new Date().toISOString()}).eq("id",run.data?.id);throw error;}
}
