import { z } from "zod";
import { ApiError,jsonError } from "@/lib/api/errors";
import { auditEvent,enforceRateLimit } from "@/lib/automation/control-plane";
import { requireLiveAgencyProject } from "@/lib/auth/live-tenant";
import { env } from "@/lib/config/env";

const schema=z.discriminatedUnion("action",[z.object({action:z.literal("approve"),projectId:z.string().uuid(),outreachId:z.string().uuid()}),z.object({action:z.literal("send"),projectId:z.string().uuid(),outreachId:z.string().uuid(),confirm:z.literal(true)})]);
export async function POST(request:Request){try{const input=schema.parse(await request.json()),context=await requireLiveAgencyProject({projectId:input.projectId,permission:"execution.approve"});await enforceRateLimit(`authority:${context.agencyId}:${context.project.id}`,input.action,input.action==="send"?10:30,3600);const outreach=await context.db.from("authority_outreach_actions").select("*").eq("id",input.outreachId).eq("agency_id",context.agencyId).eq("client_organization_id",context.clientId).eq("project_id",context.project.id).maybeSingle();if(!outreach.data)throw new ApiError("Authority outreach not found.",404,"NOT_FOUND");let result:Record<string,unknown>;
  if(input.action==="approve"){if(outreach.data.status!=="awaiting_approval")throw new ApiError("This message is not awaiting approval.",409,"CONFLICT");const saved=await context.db.from("authority_outreach_actions").update({status:"approved",approved_by:context.userId,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",input.outreachId).select("id,status").single();if(saved.error)throw new ApiError("Authority outreach could not be approved.",500,"DATABASE_BINDING_FAILED");result=saved.data;}
  else{if(outreach.data.status!=="approved")throw new ApiError("Approve this exact outreach message before sending it.",409,"CONFLICT");if(!outreach.data.contact_email)throw new ApiError("A verified contact email is required.",400,"VALIDATION_ERROR");if(!env.RESEND_API_KEY||!env.RESEND_FROM_EMAIL)throw new ApiError("Resend email delivery is not configured.",503,"NOT_CONFIGURED");const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:env.RESEND_FROM_EMAIL,to:[outreach.data.contact_email],subject:outreach.data.subject,text:outreach.data.message,headers:{"X-Entity-Ref-ID":outreach.data.id}})}),body=await response.json().catch(()=>null) as {id?:string;message?:string}|null;if(!response.ok||!body?.id)throw new ApiError("The approved outreach message could not be delivered.",502,"OPERATION_FAILED");await context.db.from("authority_outreach_actions").update({status:"sent",external_message_id:body.id,sent_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",input.outreachId);result={id:input.outreachId,status:"sent",messageId:body.id};}
  await auditEvent({agencyId:context.agencyId,actorUserId:context.userId,action:`authority.outreach.${input.action}`,resourceType:"authority_outreach",resourceId:input.outreachId,afterState:result,request});return Response.json({ok:true,result});
}catch(error){if(error instanceof z.ZodError)return jsonError(new ApiError(error.issues[0]?.message??"Invalid authority action.",400,"VALIDATION_ERROR"));return jsonError(error)}}
