import{z}from"zod";
/* Supabase response records are typed after migration 0021 is applied and types are regenerated. */
/* eslint-disable @typescript-eslint/no-explicit-any */
import{ApiError,jsonError}from"@/lib/api/errors";
import{parseJson}from"@/lib/api/request";
import{requireLiveAgencyProject}from"@/lib/auth/live-tenant";
import{auditEvent,enforceRateLimit}from"@/lib/automation/control-plane";
import{addAiPrompt,addAuthorityOpportunity,approveGrowthPlan,buildInternalLinkGraph,createCaseStudySnapshot,createGrowthToolSpec,evaluateContentRefreshes,generateGrowthPlan,growthWorkspaceSnapshot,recordAiObservation,saveBrandProfile}from"@/lib/growth/service";

const project=z.object({projectId:z.string().uuid()}),optionalId=z.string().uuid().optional(),schema=z.discriminatedUnion("action",[
  project.extend({action:z.literal("save_brand"),businessSummary:z.string().trim().min(20).max(5000),targetAudiences:z.array(z.string().trim().min(2).max(160)).max(20),toneAttributes:z.array(z.string().trim().min(2).max(80)).max(20),preferredVocabulary:z.array(z.string().trim().min(1).max(80)).max(50),prohibitedVocabulary:z.array(z.string().trim().min(1).max(80)).max(50),readingLevel:z.enum(["plain_language","general","professional","technical"]),brandValues:z.array(z.string().trim().min(2).max(160)).max(20),styleRules:z.record(z.string(),z.unknown()).optional(),visualIdentity:z.record(z.string(),z.unknown()).optional(),sourceUrls:z.array(z.string().url()).max(30).optional()}),
  project.extend({action:z.literal("generate_plan"),monthlyBudget:z.number().min(0).max(1000000)}),project.extend({action:z.literal("approve_plan"),planId:z.string().uuid()}),project.extend({action:z.literal("build_link_graph")}),project.extend({action:z.literal("evaluate_refreshes")}),
  project.extend({action:z.literal("add_ai_prompt"),question:z.string().trim().min(10).max(500),engine:z.enum(["google_ai_overview","gemini","chatgpt","perplexity","other"]),buyerStage:z.enum(["awareness","consideration","decision"]),serviceId:optionalId,locationId:optionalId}),
  project.extend({action:z.literal("record_ai_observation"),promptId:z.string().uuid(),clientMentioned:z.boolean(),mentionPosition:z.number().int().positive().optional(),answerSummary:z.string().trim().max(3000).optional(),citedUrls:z.array(z.string().url()).max(30).optional(),competitorMentions:z.array(z.record(z.string(),z.unknown())).max(30).optional(),evidenceSource:z.string().trim().min(3).max(1000)}),
  project.extend({action:z.literal("add_authority"),opportunityType:z.enum(["local_directory","association","supplier","sponsorship","digital_pr","original_data","unlinked_mention","broken_link","expert_quote","partner_resource"]),title:z.string().trim().min(5).max(200),targetDomain:z.string().trim().max(255).optional(),targetUrl:z.string().url().optional(),relevanceScore:z.number().min(0).max(100),geographicFit:z.number().min(0).max(100),editorialScore:z.number().min(0).max(100),riskScore:z.number().min(0).max(100),evidence:z.record(z.string(),z.unknown()).optional(),recommendedAction:z.string().trim().min(10).max(2000)}),
  project.extend({action:z.literal("create_tool"),title:z.string().trim().min(5).max(160),slug:z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),toolType:z.enum(["calculator","estimator","checker","comparison","generator","decision_tree","interactive_guide"]),targetKeyword:z.string().trim().max(200).optional(),userJob:z.string().trim().min(20).max(1000),inputs:z.array(z.record(z.string(),z.unknown())).max(30).optional(),conversionGoal:z.record(z.string(),z.unknown()).optional()}),
  project.extend({action:z.literal("create_case_study"),title:z.string().trim().min(5).max(200),periodStart:z.string().date(),periodEnd:z.string().date()})
]);

export async function GET(request:Request){try{const projectId=new URL(request.url).searchParams.get("projectId");if(!projectId||!z.string().uuid().safeParse(projectId).success)throw new ApiError("Choose a client project.",400,"VALIDATION_ERROR");const context=await requireLiveAgencyProject({projectId,permission:"seo.read"});return Response.json({ok:true,workspace:await growthWorkspaceSnapshot(context.db,{agencyId:context.agencyId,clientId:context.clientId,projectId})})}catch(error){return jsonError(error)}}

export async function POST(request:Request){try{const input=await parseJson(request,schema),permission=input.action==="approve_plan"?"draft.approve":"seo.write",context=await requireLiveAgencyProject({projectId:input.projectId,permission});await enforceRateLimit(`agency:${context.agencyId}:project:${input.projectId}`,`growth_${input.action}`,input.action==="generate_plan"?8:input.action==="build_link_graph"||input.action==="evaluate_refreshes"?12:100,3600);const tenant={agencyId:context.agencyId,clientId:context.clientId,projectId:input.projectId,userId:context.userId};let resource:any;
  if(input.action==="save_brand")resource=await saveBrandProfile(context.db,tenant,input);else if(input.action==="generate_plan")resource=await generateGrowthPlan(context.db,tenant,input);else if(input.action==="approve_plan")resource=await approveGrowthPlan(context.db,tenant,input.planId);else if(input.action==="build_link_graph")resource=await buildInternalLinkGraph(context.db,tenant);else if(input.action==="evaluate_refreshes")resource=await evaluateContentRefreshes(context.db,tenant);else if(input.action==="add_ai_prompt")resource=await addAiPrompt(context.db,tenant,input);else if(input.action==="record_ai_observation")resource=await recordAiObservation(context.db,tenant,input);else if(input.action==="add_authority")resource=await addAuthorityOpportunity(context.db,tenant,input);else if(input.action==="create_tool")resource=await createGrowthToolSpec(context.db,tenant,input);else resource=await createCaseStudySnapshot(context.db,tenant,input);
  await auditEvent({agencyId:context.agencyId,actorUserId:context.userId,action:`growth.${input.action}`,resourceType:"local_growth",resourceId:resource?.id,request,afterState:{projectId:input.projectId,result:resource}});return Response.json({ok:true,workspace:await growthWorkspaceSnapshot(context.db,{agencyId:context.agencyId,clientId:context.clientId,projectId:input.projectId})});}catch(error){return jsonError(error)}}
