import type { ImplementationPath } from "./implementation-path";
export interface ManualPackageInput{path:Exclude<ImplementationPath,"repository">;cmsMode?:string|null;keyword:string;targetUrl:string|null;actionType:string;title?:string|null;metaDescription?:string|null;h1?:string|null;verifiedEvidence:Array<{type:string;title:string;wording:string}>;missingEvidence:string[];}
const clean=(value:string)=>value.replace(/\s+/g," ").trim();
const titleCase=(value:string)=>value.replace(/\b\w/g,(letter)=>letter.toUpperCase());
const formatLocation=(value:string)=>titleCase(value.trim().replace(/^jax\b/i,"Jacksonville")).replace(/\s+([a-z]{2})$/i,(_,state:string)=>`, ${state.toUpperCase()}`);
export function naturalKeywordTitle(keyword:string){
  const value=clean(keyword.toLowerCase());
  const company=value.match(/^(.+?)\s+compan(?:y|ies)(?:\s+in)?\s+(.+)$/);
  if(company)return`${titleCase(company[1])} Company in ${formatLocation(company[2])}`;
  const contractor=value.match(/^(.+?)\s+contractors?(?:\s+in)?\s+(.+)$/);
  if(contractor)return`${titleCase(contractor[1])} Contractor in ${formatLocation(contractor[2])}`;
  return titleCase(value.replace(/\bjax\b/g,"Jacksonville")).replace(/\s+([a-z]{2})$/i,(_,state:string)=>`, ${state.toUpperCase()}`);
}
export function buildManualPackage(input:ManualPackageInput){
  const keyword=clean(input.keyword),titleSuggestion=naturalKeywordTitle(keyword).slice(0,60),metaSuggestion=`Explore ${titleSuggestion.toLowerCase()} options, the service process, and next steps from the verified local team.`.slice(0,155);
  const facts=input.verifiedEvidence.map(item=>({label:item.title,approvedWording:item.wording,type:item.type}));
  const common={title:`Improve visibility for ${titleSuggestion}`,targetUrl:input.targetUrl,keyword,actionType:input.actionType,current:{title:input.title??null,metaDescription:input.metaDescription??null,h1:input.h1??null},metadata:{title:titleSuggestion,metaDescription:metaSuggestion,h1:input.actionType==="IMPROVE"&&input.h1?input.h1:titleSuggestion},verifiedFacts:facts,missingEvidence:input.missingEvidence,internalLinks:{instruction:"Add contextual links only from relevant indexed pages to the verified owner URL.",anchors:[keyword]},schema:{types:["Service","FAQPage"],instruction:"Publish only claims supported by the verified evidence list. Validate JSON-LD before completion."},acceptanceCriteria:["Metadata matches the approved package","Canonical points to the intended owner URL","The page remains indexable","Internal links resolve without redirects","Every public business claim is verified"],verificationChecklist:["Check live title and meta description","Check H1 and canonical","Validate schema","Confirm noindex is absent","Test internal links","Capture mobile and desktop proof"]};
  if(input.path==="wordpress_package")return{...common,format:"wordpress" as const,editorMode:input.cmsMode??"generic_wordpress",gutenbergBlocks:[{block:"core/heading",content:titleSuggestion},{block:"core/paragraph",content:`Introduce ${keyword} using only approved business evidence.`},{block:"core/heading",content:"Service details"},{block:"core/paragraph",content:"Insert agency-approved copy and verified facts here."}],html:`<h1>${titleSuggestion}</h1>\n<p>Introduce ${keyword} using only approved business evidence.</p>`,seoPluginFields:{yoast:{seoTitle:titleSuggestion,metaDescription:metaSuggestion,focusKeyphrase:keyword},rankMath:{title:titleSuggestion,description:metaSuggestion,focusKeyword:keyword}},faqItems:[],redirectInstructions:[],imageRequirements:[{purpose:"Service proof",altText:`Verified ${keyword} service evidence`,requiresClientApproval:true}]};
  if(input.path==="developer_ticket")return{...common,format:"developer_ticket" as const,issue:`Implement the approved ${input.actionType.toLowerCase()} action for ${input.targetUrl??keyword}.`,validationSteps:common.verificationChecklist,rollback:"Restore the previous metadata/content snapshot and re-run live validation."};
  return{...common,format:"generic_cms" as const,contentBlocks:input.actionType==="IMPROVE"?[{type:"metadata",content:`Update the SEO title and description. Keep the existing H1 and body copy unchanged.`}]:[{type:"heading",content:titleSuggestion},{type:"body",content:`Prepare approved copy for ${titleSuggestion.toLowerCase()} using the verified evidence list.`}],redirectInstructions:[]};
}
