"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Arrow, MarketingFooter, MarketingHeader, MarketingLogo } from "./marketing-shared";
import {agentServicePlans,pricingPlans} from "./pricing-catalog";
import {foundingBetaProgram} from "@/lib/billing/catalog";

const integrations = ["Google Search Console", "Google Analytics 4", "Google Business Profile", "CallRail", "HubSpot", "GitHub", "Vercel", "WordPress", "Shopify", "Webflow"];

function SectionHeading({ eyebrow, title, copy, centered = false }: { eyebrow?: string; title: string; copy?: string; centered?: boolean }) {
  return <header className={`m-section-heading${centered ? " centered" : ""}`}>{eyebrow && <span className="m-eyebrow">{eyebrow}</span>}<h2>{title}</h2>{copy && <p>{copy}</p>}</header>;
}

function ProductDemo() {
  const stages = ["Website checked", "Best opportunity found", "Waiting for approval", "Work prepared", "Quality checks passed", "Results being measured"];
  const [stage, setStage] = useState(1);
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const timer = window.setInterval(() => setStage(value => (value + 1) % stages.length), 2400);
    return () => window.clearInterval(timer);
  }, [stages.length]);
  return <div className="product-demo" aria-label="Illustrative HD SEO product demo">
    <header><MarketingLogo /><span>ILLUSTRATIVE PRODUCT DEMO · NOT A CUSTOMER CASE STUDY</span></header>
    <div className="product-demo-body"><aside aria-label="Workflow stages">{stages.map((item, index) => <button key={item} type="button" className={index === stage ? "active" : index < stage ? "complete" : ""} onClick={() => setStage(index)} aria-label={`Show ${item}`}><i>{index < stage ? "✓" : index + 1}</i><span>{item}</span></button>)}</aside><article><div className="demo-status"><span className="m-eyebrow">RECOMMENDED NEXT ACTION</span><em>{stages[stage]}</em></div><h3>Create a roof-repair decision page for Jacksonville homeowners.</h3><p>Public site data suggests a useful, high-intent page is missing inside the approved service area.</p><dl><div><dt>Why this action</dt><dd>Relevant demand + a clear site gap</dd></div><div><dt>Risk</dt><dd>Low</dd></div><div><dt>Effort</dt><dd>Moderate</dd></div><div><dt>Measurement</dt><dd>Rankings, qualified leads, and recorded outcomes</dd></div></dl><div className="demo-approval"><span><small>HD SEO WILL</small>Prepare the page, add links, check technical details, and monitor the result.</span><button type="button" onClick={() => setStage(3)}>Approve work</button></div></article></div>
  </div>;
}

function ProofPlaceholder() {
  return <section className="proof-section" aria-labelledby="proof-title"><div className="proof-intro"><span className="m-eyebrow">CUSTOMER PROOF</span><h2 id="proof-title">Trust should be earned with verified evidence.</h2><p>This launch-ready proof area intentionally separates the product demo from customer claims. Replace each labeled placeholder only after the underlying customer data is approved.</p></div><div className="proof-logos" aria-label="Reserved customer logo positions">{["CUSTOMER LOGO 01", "CUSTOMER LOGO 02", "CUSTOMER LOGO 03"].map(item => <span key={item}><b>VERIFIED LOGO</b>{item}<small>Reserved — not a customer claim</small></span>)}</div><div className="proof-grid"><article className="quote-placeholder"><small>TESTIMONIAL PLACEHOLDER · UNVERIFIED</small><blockquote>“Add an approved customer quote about clarity, trust, or time saved.”</blockquote><p>Customer name, role, company, and permission required.</p></article><article className="quote-placeholder"><small>TESTIMONIAL PLACEHOLDER · UNVERIFIED</small><blockquote>“Add an approved customer quote about implementation or measurable outcomes.”</blockquote><p>Customer name, role, company, and permission required.</p></article><article className="result-placeholder"><small>QUANTIFIED RESULT · AWAITING VERIFIED DATA</small><strong>—</strong><span>qualified leads, revenue, or cost outcome</span><p>Show baseline, date range, attribution method, and source before publishing a number.</p></article><article className="case-placeholder"><small>CASE STUDY PREVIEW · ILLUSTRATIVE PRODUCT DEMO</small><h3>Harbor Roofing workflow</h3><p>See how HD SEO can move from a missing local page to approval, implementation, quality checks, and measurement.</p><a href="#product">View the illustrative workflow <span aria-hidden="true">↓</span></a></article></div></section>;
}

function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);
  const id = `faq-${question.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
  return <article className="faq-item"><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpen(!open)}><span>{question}</span><i aria-hidden="true">{open ? "−" : "+"}</i></button></h3>{open && <p id={id}>{answer}</p>}</article>;
}

export default function MarketingHome() {
  const businessPlans = [...pricingPlans.filter(plan => plan.audience === "business"),...agentServicePlans.filter(plan=>plan.audience==="business")];
  return <main className="marketing-site"><a className="skip-link" href="#main-content">Skip to content</a><MarketingHeader /><div id="main-content">
    <section className="hero"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy"><span className="pilot-chip dark">FOUNDING BETA · LIMITED ENROLLMENT</span><span className="m-eyebrow light">AGENT-OPERATED SEO, CONTROLLED BY YOU</span><h1>Connect your website once. Let HD SEO run the approved SEO workflow for you.</h1><p>HD SEO agents find the opportunity, create the work, request approval, publish safely, validate the change, and monitor business outcomes inside your permissions and budget.</p><div className="hero-actions"><Link className="primary-button" href={`/register?plan=pro&offer=${foundingBetaProgram.offerKey}`} data-analytics-event="founding_beta_signup_click" data-analytics-placement="hero">Start Run It For Me Beta <Arrow /></Link><Link className="secondary-button" href="/audit" data-analytics-event="primary_audit_cta_click" data-analytics-placement="hero">Try One Free Website Crawl</Link></div><small className="reassurance">No SEO knowledge required. Approval-controlled publishing. No rankings or revenue guarantee.</small></div><ProductDemo /></section>

    <ProofPlaceholder />

    <section className="how-section" id="how-it-works"><SectionHeading eyebrow="HOW IT WORKS" title="One clear path from website problem to measured result." copy="You do not need keyword spreadsheets or SEO training. HD SEO handles the complexity and keeps the decision with you." centered /><div className="three-steps"><article><span>01</span><h3>We find the best next move.</h3><p>HD SEO checks your website, services, approved market, and available performance data to identify a useful opportunity.</p><b>YOU SEE</b><em>A plain-language recommendation and why it matters.</em></article><article><span>02</span><h3>You review and approve it.</h3><p>See the evidence, expected effort, risk level, and exact work before anything changes.</p><b>YOU CONTROL</b><em>What gets approved, what waits, and what never publishes.</em></article><article><span>03</span><h3>HD SEO does the work and measures it.</h3><p>Approved changes are prepared, implemented through the connected website, checked, and monitored.</p><b>YOU GET</b><em>Completed work tied to rankings, qualified leads, and verified outcomes.</em></article></div></section>

    <section className="product-section" id="product"><div><SectionHeading eyebrow="SEE THE DECISION BEFORE THE WORK" title="A recommendation your whole team can understand." copy="Every proposed action explains what HD SEO found, why it matters, what will change, how much effort it needs, and how the result will be measured." /><ul className="plain-benefits"><li><span>✓</span> The opportunity and supporting evidence</li><li><span>✓</span> The exact work awaiting approval</li><li><span>✓</span> Quality checks before and after publishing</li><li><span>✓</span> Results separated from estimates</li></ul></div><ProductDemo /></section>

    <section className="safety-section"><div><SectionHeading eyebrow="SAFE BY DESIGN" title="Your rules come before automation." copy="HD SEO works inside the permissions, budgets, service areas, and approval rules you set." /><div className="safety-points"><span><b>Approval first</b>No meaningful website change publishes without the configured approval.</span><span><b>Clear history</b>See what changed, who approved it, and whether validation passed.</span><span><b>Recoverable work</b>Deployment monitoring and rollback protection are available for supported connections.</span><span><b>Verified outcomes</b>Estimated search value is never shown as actual revenue.</span></div><details className="technical-details"><summary>Technical and security details</summary><p>Tenant isolation, role-based access, encrypted secrets, tool-specific permissions, spending limits, bounded retries, audit history, and risk-based approval gates support controlled execution.</p></details></div><div className="integration-panel"><span className="m-eyebrow">CONNECTED TO THE TOOLS YOU ALREADY USE</span>{integrations.map(item => <span key={item}>{item}</span>)}<small>Availability depends on connection type, permissions, and pilot configuration.</small></div></section>

    <section className="plans-section" id="plans"><SectionHeading eyebrow="FOUNDING BETA PRICING" title="Start with guidance—or let the agents run it for you." copy="Every beta tier uses real production workflows with fixed capacity, approval controls, validation, and reporting. Optional third-party spending is separate and never automatic." centered /><div className="plans-grid">{businessPlans.map(plan => <article key={plan.slug} className={plan.slug === "autopilot" ? "featured" : ""}><span>{plan.slug==="autopilot"?"RUN IT FOR ME · BEST VALUE":"FOUNDING BETA"}</span><h3>{plan.name}</h3><strong className="home-plan-price">${plan.betaOffer.price}<small>/first month</small></strong><del>${plan.monthly}/month</del><p>{plan.description}</p><ul>{plan.features.slice(0, 4).map(feature => <li key={feature}>{feature}</li>)}</ul><Link href={`${plan.href}${plan.href.includes("?")?"&":"?"}offer=${foundingBetaProgram.offerKey}`} data-analytics-event="business_beta_plan_selection" data-analytics-placement={`home_${plan.slug}`}>{plan.slug.startsWith("autopilot")?"Start Run It For Me Beta":`Start ${plan.name} Beta`} <Arrow /></Link></article>)}</div><p className="plan-note">The beta discount applies to the first monthly billing period. HD SEO measures the first {foundingBetaProgram.measurementWindowDays} days of delivery so the system can keep, improve, or stop low-value work. The plan then renews at the displayed standard monthly price unless canceled. Rankings, leads, and revenue are not guaranteed.</p><div className="plans-see-all"><Link href="/pricing">Compare every plan, limit, add-on, and agency option <Arrow /></Link></div></section>

    <section className="faq-section" id="faq"><SectionHeading eyebrow="COMMON QUESTIONS" title="Know what happens before you connect anything." /><div><FaqItem question="What do I get in the free audit?" answer="A crawl of up to 25 public pages, a technical readiness summary, the most important findings we can verify, and a plain-language next step. It does not require a credit card." /><FaqItem question="Will HD SEO publish without asking me?" answer="No. Publishing follows the permissions and approval rules configured for your workspace. The pilot is designed around reviewable, controlled work." /><FaqItem question="Does HD SEO guarantee rankings or revenue?" answer="No. Search performance depends on many factors. HD SEO shows evidence, records the work completed, and keeps estimates separate from measured and verified outcomes." /><FaqItem question="Is HD SEO only for local businesses?" answer="The homepage is designed for local service businesses. Dedicated Agency and Enterprise experiences support client portfolios and multi-location governance." /><FaqItem question="Is HD SEO generally available?" answer="Not yet. HD SEO is operating as a limited pilot while production readiness and customer proof are verified." /></div></section>

    <section className="contact-section"><div><span className="m-eyebrow">COMPANY & CONTACT</span><h2>Talk through your website, market, and approval needs.</h2><p>HD SEO is currently a limited pilot. The walkthrough route explains current availability and what information is still pending before general release.</p></div><Link href="/book-demo" data-analytics-event="booking_cta_click" data-analytics-placement="contact">Book a Platform Walkthrough <Arrow /></Link></section>

    <section className="final-cta"><span className="m-eyebrow light">START WITH PUBLIC WEBSITE DATA</span><h2>See what HD SEO finds on your first 25 pages.</h2><p>Create a verified business workspace, run one free crawl, and explore how plans, approvals, agents, and results fit together.</p><div><Link className="primary-button" href="/register" data-analytics-event="free_trial_signup_click" data-analytics-placement="final">Create My Free Account <Arrow /></Link><Link className="secondary-button" href="/audit" data-analytics-event="primary_audit_cta_click" data-analytics-placement="final">Audit Without an Account</Link></div><small className="reassurance">No credit card. One crawl. Paid actions remain locked.</small></section>
  </div><MarketingFooter /></main>;
}
