import { createHash } from "node:crypto";
import { z } from "zod";
import { resolveTenantContext, requirePermission } from "@/lib/auth/context";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { parseJson } from "@/lib/api/request";
import { jsonError, ApiError, logEvent } from "@/lib/api/errors";
import { systemReadiness } from "@/lib/readiness/system-readiness";

const schema=z.object({agencyId:z.string().uuid(),clientId:z.string().uuid(),projectId:z.string().uuid(),campaignId:z.string().uuid().optional(),automationMode:z.enum(["MONITOR","RECOMMEND","PREPARE","EXECUTE_WITH_APPROVAL"]).default("PREPARE"),minimumConfidence:z.number().int().min(0).max(100).default(55)});
export async function POST(request:Request){try{const input=await parseJson(request,schema),context=await resolveTenantContext({agencyId:input.agencyId,clientId:input.clientId,projectId:input.projectId,requireProject:true});requirePermission(context,input.automationMode==="EXECUTE_WITH_APPROVAL"?"execution.approve":"seo.write");if(!context.client||!context.project)throw new ApiError("A project is required.",400,"VALIDATION_ERROR");const readiness=await systemReadiness(context.project.id);if(!readiness.ready)throw new ApiError("The automation foundation is not ready.",409,"CONFLICT");const db=createSupabaseAdminClient();if(!db)throw new ApiError("Supabase is not configured.",503,"NOT_CONFIGURED");if(input.campaignId){const campaign=await db.from("seo_campaigns").select("id").eq("id",input.campaignId).eq("agency_id",context.agency.id).eq("client_organization_id",context.client.id).eq("project_id",context.project.id).maybeSingle();if(!campaign.data)throw new ApiError("Campaign not found for this project.",404,"NOT_FOUND");}if(input.automationMode==="EXECUTE_WITH_APPROVAL"){const gate=await db.rpc("github_execution_readiness",{target_agency:context.agency.id,target_project:context.project.id});if(!gate.data?.ready)throw new ApiError(`Repository execution is not ready: ${(gate.data?.blockers??[]).join(", ")}.`,409,"CONFLICT");}const hour=new Date().toISOString().slice(0,13),idempotencyKey=createHash("sha256").update(`${context.agency.id}:${context.project.id}:${context.user.id}:${hour}:${JSON.stringify(input)}`).digest("hex"),existing=await db.from("seo_campaign_jobs").select("id,status,reference_id").eq("idempotency_key",idempotencyKey).maybeSingle();if(existing.data)return Response.json({ok:true,jobId:existing.data.id,status:existing.data.status,referenceId:existing.data.reference_id,duplicate:true},{status:202});const referenceId=crypto.randomUUID(),job=await db.from("seo_campaign_jobs").insert({agency_id:context.agency.id,client_organization_id:context.client.id,project_id:context.project.id,campaign_id:input.campaignId??null,requested_by:context.user.id,status:"queued",current_stage:"validate",input,idempotency_key:idempotencyKey,reference_id:referenceId}).select("id,status").single();if(!job.data)throw new ApiError("The job could not be created.",500,"OPERATION_FAILED",referenceId);logEvent("job_created",{jobId:job.data.id,agencyId:context.agency.id,projectId:context.project.id,referenceId});return Response.json({ok:true,jobId:job.data.id,status:job.data.status,referenceId},{status:202});}catch(error){return jsonError(error)}}
