export const agentRegistry = [
  {key:"onboarding",name:"Onboarding Agent",shortName:"Onboarding",description:"Builds the business, website, service-area, and integration profile.",color:"#4d8f7a",capabilities:["detect_business","detect_platform","map_services","map_locations","check_integrations"],tools:["website.detect","website.crawl","google.search_console.read"]},
  {key:"research",name:"Research Agent",shortName:"Research",description:"Finds keywords, competitors, gaps, AI-answer visibility, and legitimate authority opportunities.",color:"#4778a8",capabilities:["keyword_research","competitor_research","gap_analysis","opportunity_scoring","ai_visibility","authority_research"],tools:["google.search_console.read","keywords.discover","competitors.analyze","opportunities.score","ai_visibility.observe","authority.research"]},
  {key:"strategy",name:"Strategy Agent",shortName:"Strategy",description:"Turns evidence and budget into a value-gated 30, 60, and 90-day Local Growth Plan.",color:"#8064a2",capabilities:["prioritize","plan","budget_allocation","dependency_mapping"],tools:["opportunities.score","strategy.plan","growth.plan","audit.read"]},
  {key:"technical_seo",name:"Technical SEO Agent",shortName:"Technical SEO",description:"Audits indexing, schema, sitemaps, metadata, links, and performance.",color:"#b16a43",capabilities:["crawl","technical_audit","indexing_audit","performance_audit","internal_link_graph"],tools:["website.crawl","google.search_console.read","lighthouse.run","seo.validate","schema.validate","sitemap.verify","robots.verify","internal_links.graph"]},
  {key:"content",name:"Content Agent",shortName:"Content",description:"Refreshes existing owner pages first, then compiles verified business proof into original, QA-scored content and useful tools.",color:"#a15e7f",capabilities:["content_brief","creative_spec","evidence_gated_draft","metadata_draft","internal_links","content_refresh","interactive_tools"],tools:["google.search_console.read","proof.read","creative.spec","creative.generate","content.refresh","internal_links.graph","growth_tool.spec","cms.draft","cms.publish"]},
  {key:"local_seo",name:"Local SEO Agent",shortName:"Local SEO",description:"Plans local visibility, profile, review, and geographic improvements.",color:"#75964e",capabilities:["local_research","location_gaps","profile_recommendations","review_strategy"],tools:["google.search_console.read","google.business_profile.read","strategy.plan"]},
  {key:"implementation",name:"Implementation Agent",shortName:"Implementation",description:"Publishes approved changes through CMS, GitHub, and deployment connections.",color:"#8b6e55",capabilities:["cms_write","repository_write","deploy","rollback"],tools:["cms.draft","cms.publish","github.read","github.write","vercel.deploy","vercel.rollback","dns.write","pricing.change","legal.publish"]},
  {key:"qa",name:"QA Agent",shortName:"QA",description:"Independently validates deployments, SEO, schema, robots, sitemaps, and rollback readiness.",color:"#426c80",capabilities:["health_check","lighthouse","seo_validation","schema_validation","rollback_validation"],tools:["lighthouse.run","seo.validate","schema.validate","sitemap.verify","robots.verify","vercel.rollback"]},
  {key:"reporting",name:"Reporting Agent",shortName:"Reporting",description:"Explains completed work, rankings, leads, spending, and verifiable outcomes in plain language.",color:"#697d6d",capabilities:["summarize","attribute_outcomes","case_study","report","notify"],tools:["google.search_console.read","google.analytics.read","proof.case_study","report.generate","notification.send","audit.read"]},
  {key:"supervisor",name:"Supervisor Agent",shortName:"Supervisor",description:"Assigns work, enforces budgets and permissions, coordinates retries, and requests approvals.",color:"#293f38",capabilities:["assign","authorize_tools","enforce_budget","enforce_risk","request_approval","retry","dead_letter"],tools:["audit.read","opportunities.score","strategy.plan"]},
] as const;

export type AgentKey=(typeof agentRegistry)[number]["key"];
export const agentByKey=new Map(agentRegistry.map(agent=>[agent.key,agent]));

export const workTemplates={
  "onboarding.profile":{agentKey:"onboarding",goal:"Complete the structured business, website, service-area, and integration profile.",tools:["website.detect","website.crawl","google.search_console.read"],riskLevel:"low",priority:95},
  "research.discovery":{agentKey:"research",goal:"Discover and score the best-value keyword and competitor opportunities within budget.",tools:["google.search_console.read","keywords.discover","competitors.analyze","opportunities.score"],riskLevel:"medium",priority:85},
  "strategy.roadmap":{agentKey:"strategy",goal:"Build an evidence-backed, value-gated 30, 60, and 90-day Local Growth Plan.",tools:["opportunities.score","strategy.plan","growth.plan","audit.read"],riskLevel:"low",priority:75},
  "technical.audit":{agentKey:"technical_seo",goal:"Audit technical SEO, indexing readiness, schema, sitemaps, robots, internal links, and performance.",tools:["website.crawl","google.search_console.read","lighthouse.run","seo.validate","schema.validate","sitemap.verify","robots.verify","internal_links.graph"],riskLevel:"low",priority:90},
  "content.plan":{agentKey:"content",goal:"Identify refresh wins before compiling high-value opportunities and verified business proof into evidence-gated creative specifications.",tools:["google.search_console.read","proof.read","content.refresh","internal_links.graph","creative.spec","growth_tool.spec","cms.draft"],riskLevel:"medium",priority:65},
  "local.plan":{agentKey:"local_seo",goal:"Identify local visibility, service-area, profile, and review opportunities.",tools:["google.search_console.read","google.business_profile.read","strategy.plan"],riskLevel:"medium",priority:65},
  "implementation.change":{agentKey:"implementation",goal:"Implement an approved SEO change with deployment and rollback protection.",tools:["cms.draft","cms.publish","github.read","github.write","vercel.deploy","vercel.rollback"],riskLevel:"high",priority:80},
  "qa.validate":{agentKey:"qa",goal:"Independently validate the implementation and confirm rollback readiness.",tools:["lighthouse.run","seo.validate","schema.validate","sitemap.verify","robots.verify","vercel.rollback"],riskLevel:"high",priority:85},
  "reporting.summary":{agentKey:"reporting",goal:"Explain completed work, evidence, spending, rankings, and verifiable outcomes in plain language.",tools:["google.search_console.read","proof.case_study","report.generate","audit.read"],riskLevel:"low",priority:50},
} as const;

export type AgentWorkType=keyof typeof workTemplates;
