"use client";

import {useEffect,useState} from "react";
import {agencyBillingPlans} from "@/lib/billing/agency-catalog";
import {FOUNDING_BETA_OFFER_KEY} from "@/lib/billing/catalog";

type PlanKey="launch"|"growth"|"scale";
type Billing={subscription:{plan_key:PlanKey;status:string;price_cents:number;included_client_limit:number;included_scale_client_limit:number;current_period_end:string|null;cancel_at_period_end:boolean;offer_key:string|null;offer_price_cents:number|null;offer_ends_at:string|null;beta_redeemed_at:string|null}|null;usage:{activeClients:number;scaleClients:number}};
type Payload={billing?:Billing;url?:string;error?:{message?:string}};

const plans=[
  {key:"launch" as const,...agencyBillingPlans.launch},
  {key:"growth" as const,...agencyBillingPlans.growth},
  {key:"scale" as const,...agencyBillingPlans.scale},
];
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(cents/100);

export function AgencyBillingPanel({canManage}:{canManage:boolean}){
  const [billing,setBilling]=useState<Billing|null>(null),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState("");
  async function load(){try{const response=await fetch("/api/agency-billing/status"),payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error?.message??"Agency billing could not be loaded.");setBilling(payload.billing??null);}catch(error){setMessage(error instanceof Error?error.message:"Agency billing could not be loaded.");}}
  useEffect(()=>{let active=true;fetch("/api/agency-billing/status").then(async response=>({response,payload:await response.json() as Payload})).then(({response,payload})=>{if(!active)return;if(!response.ok)throw new Error(payload.error?.message??"Agency billing could not be loaded.");setBilling(payload.billing??null);}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:"Agency billing could not be loaded.");});return()=>{active=false;};},[]);
  async function act(path:string,body:Record<string,unknown>,key:string){setBusy(key);setMessage("");try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error?.message??"Billing could not be opened.");if(payload.url){window.location.assign(payload.url);return;}await load();setMessage("Agency plan updated. Stripe will apply any prorated amount automatically.");}catch(error){setMessage(error instanceof Error?error.message:"Billing could not be opened.");}finally{setBusy(null);}}
  const current=billing?.subscription,currentPlan=plans.find(plan=>plan.key===current?.plan_key),hasSubscription=Boolean(current&&["trialing","active","past_due"].includes(current.status)),betaEligible=!hasSubscription&&!current?.beta_redeemed_at;
  return <section className="agency-billing">
    <header><small>AGENCY SUBSCRIPTION</small><h1>Profitable capacity, billed clearly.</h1><p>Your agency plan pays for HD SEO access and bounded execution capacity across active managed clients. Provider budgets and capacity remain capped per client, protecting your margin.</p></header>
    {message&&<div className="agent-service-message">{message}</div>}
    {current&&<section className="agency-billing-status"><div><small>CURRENT PLAN</small><strong>{currentPlan?.label??current.plan_key}</strong><span>{current.status.replaceAll("_"," ")}{current.cancel_at_period_end?" · cancels at period end":""}</span>{current.offer_key===FOUNDING_BETA_OFFER_KEY&&current.offer_price_cents&&<span>Founding Beta {money(current.offer_price_cents)} through {current.offer_ends_at?new Date(current.offer_ends_at).toLocaleDateString():"the first period"}, then {money(current.price_cents)}/month.</span>}</div><div><small>ACTIVE CLIENTS</small><strong>{billing.usage.activeClients} / {current.included_client_limit}</strong><span>{billing.usage.scaleClients} / {current.included_scale_client_limit} Scale seats used</span></div><div><small>NEXT BILLING DATE</small><strong>{current.current_period_end?new Date(current.current_period_end).toLocaleDateString():"Pending Stripe sync"}</strong></div>{canManage&&hasSubscription&&<button disabled={busy!==null} onClick={()=>void act("/api/agency-billing/portal",{},"portal")}>{busy==="portal"?"Opening…":"Manage billing"}</button>}</section>}
    <div className="agency-pricing-grid">{plans.map(plan=>{const selected=hasSubscription&&current?.plan_key===plan.key,shownPrice=betaEligible?plan.beta.priceCents:plan.priceCents;return <article className={plan.key==="growth"?"featured":""} key={plan.key}><small>{betaEligible?plan.key==="growth"?"FOUNDING BETA · RECOMMENDED":"FOUNDING BETA":plan.key==="growth"?"RECOMMENDED":"MONTHLY"}</small><h2>{plan.label}</h2><strong>{money(shownPrice)}<em>{betaEligible?" first month":"/mo"}</em></strong>{betaEligible&&<span className="agency-beta-renewal">Then {money(plan.priceCents)}/month unless canceled · {plan.beta.enrollmentLimit} spots</span>}<p>{plan.description}</p><ul><li>{plan.includedClients} active managed-client seats</li><li>{plan.includedScaleClients?`${plan.includedScaleClients} Managed Scale seats`:"Managed Core delivery"}</li><li>White-label client experience</li><li>Approvals, audit history and rollback</li><li>Hard provider and action limits</li></ul>{canManage&&<button disabled={busy!==null||selected} onClick={()=>{if(hasSubscription&&!window.confirm(`Change your agency subscription to ${plan.label}? Stripe may apply a prorated charge or credit.`))return;void act(hasSubscription?"/api/agency-billing/change-plan":"/api/agency-billing/checkout",{planKey:plan.key,...(betaEligible?{offerKey:FOUNDING_BETA_OFFER_KEY}:{})},plan.key);}}>{selected?"Current plan":busy===plan.key?"Opening secure billing…":hasSubscription?`Change to ${plan.label}`:betaEligible?`Start ${plan.label} Beta`:`Choose ${plan.label}`}</button>}</article>;})}</div>
    <footer><strong>Usage protection is built in.</strong><span>HD SEO uses weighted execution capacity for verified customer outcomes. One high-value campaign may use more capacity than a small improvement. Failed work, retries, and no-action reviews do not consume capacity; add-ons require explicit purchase.</span></footer>
  </section>;
}
