"use client";

import {useEffect,useState} from "react";

type Project={id:string;name:string;domain:string};
type Enrollment={status:string;plan_key:string;approval_owner:string;monthly_action_limit:number};
type Cycle={stage:string};
type ServiceWork={id:string;status:string;assigned_agent_key:string;goal:string};
type ServiceApproval={id:string;title:string;summary:string;risk_level:string};
type ServiceEscalation={id:string;status:string;title:string;summary:string;escalation_type:string};
type Snapshot={enrollment:Enrollment|null;cycles:Cycle[];usage:unknown[];escalations:ServiceEscalation[];activeWork:ServiceWork[];approvals:ServiceApproval[];summary:{actionsRemaining:number;providerBudgetRemaining:number;openEscalations:number;nextCycleAt:string}|null};
type ApiPayload={error?:{message?:string};service?:Snapshot;url?:string};
const friendly=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(value);

export function AgentServicePanel({projects,role="agency",canManage=true,canApprove=canManage}:{projects:Project[];role?:"agency"|"client";canManage?:boolean;canApprove?:boolean}){
  const [projectId,setProjectId]=useState(projects[0]?.id??""),[data,setData]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const effectiveProjectId=projects.some(project=>project.id===projectId)?projectId:(projects[0]?.id??"");
  useEffect(()=>{if(!effectiveProjectId)return;let active=true;fetch(`/api/agent-service/status?projectId=${encodeURIComponent(effectiveProjectId)}`).then(async response=>({response,payload:await response.json() as ApiPayload})).then(({response,payload})=>{if(!active)return;if(!response.ok)throw new Error(payload.error?.message??"Managed SEO status could not be loaded.");setData(payload.service??null);}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:"Managed SEO status could not be loaded.");});return()=>{active=false;};},[effectiveProjectId]);
  async function action(path:string,body:Record<string,unknown>={}){setBusy(true);setMessage("");try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:effectiveProjectId,...body})}),payload=await response.json() as ApiPayload;if(!response.ok)throw new Error(payload.error?.message??"The request could not be completed.");if(payload.url){window.location.assign(payload.url);return;}setData(payload.service??null);setMessage("Saved. The supervisor will use this setting on the next safe cycle.");}catch(error){setMessage(error instanceof Error?error.message:"The request could not be completed.");}finally{setBusy(false);}}
  if(!projects.length)return <section className="agent-service-empty"><h2>Add a client project first</h2><p>Managed agents need a tenant-scoped project, business profile, and website before they can operate.</p></section>;
  const enrollment=data?.enrollment,cycle=data?.cycles?.[0],current=projects.find(project=>project.id===effectiveProjectId);
  return <section className={`agent-service-panel ${role}`}>
    <header className="agent-service-heading"><div><small>{role==="client"?"HD SEO AUTOPILOT":"WHITE-LABEL AGENT TEAM"}</small><h1>{role==="client"?"Your SEO team, always working safely.":"Managed agent service"}</h1><p>{role==="client"?"HD SEO researches, prioritizes, prepares and validates work. You only step in when a decision needs you.":"Enroll each client in a bounded, metered service with explicit tools, approval ownership and resale controls."}</p></div>{projects.length>1&&<select value={effectiveProjectId} onChange={event=>setProjectId(event.target.value)}>{projects.map(project=><option key={project.id} value={project.id}>{project.domain} · {project.name}</option>)}</select>}</header>
    {message&&<div className="agent-service-message">{message}</div>}
    {!enrollment?<section className="agent-service-enroll"><div><strong>{role==="client"?"Turn on Autopilot":"This client is not enrolled"}</strong><p>{role==="client"?"Start with guarded automation. Publishing, spending and high-risk changes still require the approvals you choose.":"Choose a plan and approval owner. HD SEO will schedule cycles only when real evidence supports useful work."}</p></div>{canManage&&<button disabled={busy} onClick={()=>void action("/api/agent-service/enroll",role==="client"?{serviceMode:"managed_agent",planKey:"growth",approvalOwner:"client",operatorBrand:"hdseo",billingOwner:"client"}:{serviceMode:"managed_agent",planKey:"agency_core",approvalOwner:"agency",operatorBrand:"agency",billingOwner:"agency"})}>{busy?"Starting…":role==="client"?"Start HD SEO Autopilot":"Enroll managed client"}</button>}</section>:
    <>
      <section className="agent-service-status"><div><i className={enrollment.status}/><span><small>SERVICE STATUS</small><strong>{friendly(enrollment.status)}</strong><em>{current?.domain}</em></span></div><div><small>NEXT REVIEW</small><strong>{data?.summary?.nextCycleAt?new Date(data.summary.nextCycleAt).toLocaleString():"Not scheduled"}</strong></div>{canManage&&<button disabled={busy} onClick={()=>void action(enrollment.status==="paused"?"/api/agent-service/resume":"/api/agent-service/pause",enrollment.status==="paused"?{}:{reason:"Paused from the managed-service workspace"})}>{enrollment.status==="paused"?"Resume service":"Pause service"}</button>}</section>
      <section className="agent-service-metrics"><article><small>ACTIONS LEFT</small><strong>{data?.summary?.actionsRemaining??0}</strong><span>Completed customer-visible deliverables</span></article><article><small>PROVIDER BUDGET LEFT</small><strong>{money(data?.summary?.providerBudgetRemaining??0)}</strong><span>Hard API/data cost ceiling</span></article><article><small>DECISIONS WAITING</small><strong>{data?.approvals.length??0}</strong><span>Nothing publishes without policy</span></article><article><small>OPEN ESCALATIONS</small><strong>{data?.summary?.openEscalations??0}</strong><span>Blocked work needing attention</span></article></section>
      <div className="agent-service-grid"><section><header><small>CURRENT WORK</small><h2>{cycle?friendly(cycle.stage):"Waiting for the next evidence review"}</h2></header>{data?.activeWork.length?data.activeWork.map(item=><article key={item.id}><i>{item.status==="awaiting_approval"?"!":"↻"}</i><div><strong>{friendly(item.assigned_agent_key)}</strong><p>{item.goal}</p></div><span>{friendly(item.status)}</span></article>):<div className="agent-service-clear"><strong>No busywork</strong><p>There is no active work. HD SEO will start the next cycle only when evidence supports a worthwhile action.</p></div>}</section><section><header><small>DECISIONS</small><h2>Plain-language approval inbox</h2></header>{data?.approvals.length?data.approvals.map(item=><article className="agent-service-approval" key={item.id}><div><strong>{item.title}</strong><p>{item.summary}</p><small>{friendly(item.risk_level)} risk</small></div>{canApprove&&<nav><button disabled={busy} onClick={()=>void action("/api/agent-service/decide",{approvalId:item.id,decision:"rejected",note:"Declined from managed-service workspace"})}>Decline</button><button disabled={busy} onClick={()=>void action("/api/agent-service/decide",{approvalId:item.id,decision:"approved",note:"Approved from managed-service workspace"})}>Approve</button></nav>}</article>):<div className="agent-service-clear"><strong>You are all caught up</strong><p>No managed-agent decision needs attention.</p></div>}</section></div>
      {role==="agency"&&canManage&&<section className="agent-service-controls"><div><small>SERVICE CONTROLS</small><strong>Plan, capacity and approval policy</strong><span>One action is one completed customer-visible deliverable. Internal agent handoffs, failed work, and no-action reviews do not use credits.</span></div><label>Plan<select value={enrollment.plan_key} onChange={event=>void action("/api/agent-service/change-plan",{planKey:event.target.value})}><option value="agency_core">Agency Managed Core</option><option value="agency_scale">Agency Managed Scale</option><option value="growth">Growth Autopilot</option><option value="pro">Pro + Human Review</option></select></label><label>Approval owner<select value={enrollment.approval_owner} onChange={event=>void action("/api/agent-service/settings",{approvalOwner:event.target.value})}><option value="agency">Agency</option><option value="client">Client</option><option value="both">Agency + client</option></select></label><button disabled={busy} onClick={()=>void action("/api/agent-service/purchase-capacity",{units:1})}>Buy 1 action · $15</button></section>}
      {!!data?.escalations.filter(item=>item.status==="open").length&&<section className="agent-service-escalations"><header><small>NEEDS ATTENTION</small><h2>Blocked actions</h2></header>{data.escalations.filter(item=>item.status==="open").map(item=><article key={item.id}><div><strong>{item.title}</strong><p>{item.summary}</p></div><span>{friendly(item.escalation_type)}</span></article>)}</section>}
    </>}
  </section>;
}
