"use client";

import { useEffect,useMemo,useState } from "react";

type Project={id:string;name:string;domain:string};
type Agent={key:string;name:string;shortName:string;description:string;color:string;capabilities:readonly string[];tools:readonly string[]};
type WorkItem={id:string;work_type:string;goal:string;assigned_agent_key:string;status:string;priority:number;risk_level:string;spending_limit:number;spent_amount:number;authorized_tools:string[];evidence:Record<string,unknown>;validation_results:Record<string,unknown>;final_outcome:Record<string,unknown>;created_at:string;updated_at:string;completed_at:string|null};
type Step={id:string;work_item_id:string;sequence:number;agent_key:string;title:string;status:string;tool_key:string|null;error_message:string|null};
type Approval={id:string;work_item_id:string;approval_type:string;title:string;summary:string;risk_level:string;status:string;requested_at:string;decision_note:string|null};
type MutationIntent={id:string;tool_key:string;resource_type:string;resource_id:string|null;environment:string|null;summary:string;risk_level:string;action_digest:string;status:string;expires_at:string;created_at:string};
type Activity={id:number;work_item_id:string|null;agent_key:string;event_type:string;title:string;description:string|null;occurred_at:string};
type Deployment={id:string;environment:string;url:string|null;status:string;git_ref:string;created_at:string;rollback_of_id:string|null};
type Workspace={agents:Agent[];workItems:WorkItem[];steps:Step[];approvals:Approval[];mutationIntents:MutationIntent[];activity:Activity[];deployments:Deployment[];summary:{queued:number;running:number;awaitingApproval:number;completed:number;blocked:number;failed:number;moneyUsed:number;monthlyBudget:number;expectedMonthlyValue:number;memoryCount:number}};

const statusLabel=(value:string)=>value.replaceAll("_"," ");
const formatMoney=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value||0);

export function AgentWorkspace({projects,canRun,canApprove}:{projects:Project[];canRun:boolean;canApprove:boolean}){
  const [projectId,setProjectId]=useState(projects[0]?.id??""),[workspace,setWorkspace]=useState<Workspace|null>(null),[busy,setBusy]=useState(true),[message,setMessage]=useState(""),[expanded,setExpanded]=useState<string|null>(null);
  const stepsByWork=useMemo(()=>{const map=new Map<string,Step[]>();for(const step of workspace?.steps??[])map.set(step.work_item_id,[...(map.get(step.work_item_id)??[]),step]);return map;},[workspace?.steps]);
  async function load(){if(!projectId)return;setBusy(true);setMessage("");try{const response=await fetch(`/api/agents/workspace?projectId=${encodeURIComponent(projectId)}`,{cache:"no-store"}),result=await response.json();if(!response.ok){setWorkspace(null);setMessage(result.error?.message??"The Agent Workspace could not be loaded.");return;}setWorkspace(result.workspace);}catch{setMessage("The Agent Workspace could not reach the server.");}finally{setBusy(false);}}
  useEffect(()=>{if(!projectId)return;const controller=new AbortController();fetch(`/api/agents/workspace?projectId=${encodeURIComponent(projectId)}`,{cache:"no-store",signal:controller.signal}).then(async response=>({response,result:await response.json()})).then(({response,result})=>{if(!response.ok){setWorkspace(null);setMessage(result.error?.message??"The Agent Workspace could not be loaded.");setBusy(false);return;}setWorkspace(result.workspace);setBusy(false);}).catch(error=>{if(error instanceof DOMException&&error.name==="AbortError")return;setMessage("The Agent Workspace could not reach the server.");setBusy(false);});return()=>controller.abort();},[projectId]);
  async function act(body:Record<string,unknown>){setBusy(true);setMessage("");try{const response=await fetch("/api/agents/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,...body})}),result=await response.json();if(!response.ok){setMessage(result.error?.message??"The supervisor could not complete that action.");return;}setWorkspace(result.workspace);setMessage(result.notice??"Saved. The Supervisor Agent will process the next safe step.");}catch{setMessage("The supervisor could not be reached.");}finally{setBusy(false);}}
  if(!projects.length)return <section className="live-section"><div className="live-empty"><strong>Add a client first</strong><p>The Agent Workspace is always scoped to one client project.</p></div></section>;
  return <div className="agent-workspace">
    <div className="live-heading agent-heading"><div><small>AGENT-FIRST OPERATING ENVIRONMENT</small><h1>Agent Workspace</h1><p>Specialized agents collaborate behind a supervisor that enforces evidence, budgets, permissions, approvals, and rollback safety.</p></div><div className="agent-project-controls"><select value={projectId} onChange={event=>{setBusy(true);setWorkspace(null);setMessage("");setProjectId(event.target.value)}}>{projects.map(item=><option value={item.id} key={item.id}>{item.domain} · {item.name}</option>)}</select><button onClick={()=>void load()} disabled={busy}>Refresh</button></div></div>
    {message&&<div className="agent-message">{message}</div>}
    {busy&&!workspace?<div className="agent-loading">Loading the client&apos;s agent workspace…</div>:workspace&&<>
      <section className="agent-value-bar"><article><small>IN PROGRESS</small><strong>{workspace.summary.running+workspace.summary.queued}</strong><span>{workspace.summary.running} actively working</span></article><article className={workspace.summary.awaitingApproval?"attention":""}><small>NEEDS APPROVAL</small><strong>{workspace.summary.awaitingApproval}</strong><span>Protected decisions</span></article><article><small>COMPLETED</small><strong>{workspace.summary.completed}</strong><span>{workspace.summary.blocked} blocked</span></article><article><small>MONEY USED</small><strong>{formatMoney(workspace.summary.moneyUsed)}</strong><span>of {formatMoney(workspace.summary.monthlyBudget)} budget</span></article><article><small>EXPECTED VALUE</small><strong>{formatMoney(workspace.summary.expectedMonthlyValue)}</strong><span>directional monthly opportunity</span></article></section>
      <section className="agent-launch-panel"><div><small>SUPERVISOR AGENT</small><h2>Put the full team to work</h2><p>Requests the next managed cycle through your plan allowance. The supervisor enforces included actions, provider-cost limits, permissions, approvals, and rollback safety before any specialist starts.</p></div>{canRun&&<div><button disabled={busy} onClick={()=>void act({action:"run_team"})}>{busy?"Requesting cycle…":"Run agent team →"}</button></div>}</section>
      <section className="agent-layout">
        <div className="agent-main-column">
          <section className="agent-panel"><header><div><small>LIVE WORK</small><h2>Agent activity</h2></div><span>{workspace.workItems.length} work items</span></header>{workspace.workItems.length?workspace.workItems.map(item=>{const agent=workspace.agents.find(candidate=>candidate.key===item.assigned_agent_key),steps=stepsByWork.get(item.id)??[],open=expanded===item.id;return <article className={`agent-work-item status-${item.status}`} key={item.id}><button className="agent-work-summary" onClick={()=>setExpanded(open?null:item.id)}><i style={{background:agent?.color}}>{agent?.shortName.slice(0,1)??"A"}</i><div><span><strong>{agent?.name??item.assigned_agent_key}</strong><em>{statusLabel(item.status)}</em><b>{item.risk_level} risk</b></span><h3>{item.goal}</h3><small>{new Date(item.updated_at).toLocaleString()} · {item.authorized_tools.length} authorized tools · {formatMoney(item.spent_amount)} spent of {formatMoney(item.spending_limit)}</small></div><u>{open?"−":"+"}</u></button>{open&&<div className="agent-work-detail"><div className="agent-steps">{steps.map(step=><span key={step.id} className={step.status}><i>{step.status==="succeeded"?"✓":step.sequence}</i><div><strong>{step.title}</strong><small>{step.agent_key.replaceAll("_"," ")}{step.tool_key?` · ${step.tool_key}`:""}</small>{step.error_message&&<p>{step.error_message}</p>}</div><em>{statusLabel(step.status)}</em></span>)}</div><div className="agent-work-meta"><div><small>EVIDENCE USED</small><p>{Object.keys(item.evidence??{}).length?JSON.stringify(item.evidence):"Evidence is being collected"}</p></div><div><small>AUTHORIZED TOOLS</small><p>{item.authorized_tools.join(" · ")||"No external tools"}</p></div><div><small>VALIDATION</small><p>{Object.keys(item.validation_results??{}).length?JSON.stringify(item.validation_results):"Pending"}</p></div><div><small>FINAL OUTCOME</small><p>{typeof item.final_outcome?.summary==="string"?item.final_outcome.summary:"Pending"}</p></div></div>{canRun&&["failed","blocked","dead_letter"].includes(item.status)&&<button onClick={()=>void act({action:"control",workItemId:item.id,command:"retry"})}>Retry safely</button>}{canRun&&!['succeeded','cancelled','failed','dead_letter'].includes(item.status)&&<button className="agent-cancel" onClick={()=>void act({action:"control",workItemId:item.id,command:"cancel"})}>Cancel work</button>}</div>}</article>}):<div className="agent-empty"><strong>No agent work yet</strong><p>Run the team to create the first supervised work plan.</p></div>}</section>
          <section className="agent-panel"><header><div><small>PROOF OF WORK</small><h2>Agent timeline</h2></div></header>{workspace.activity.slice(0,25).map(item=>{const agent=workspace.agents.find(candidate=>candidate.key===item.agent_key);return <article className="agent-timeline-row" key={item.id}><i style={{background:agent?.color}}/><div><strong>{item.title}</strong><p>{item.description}</p><small>{agent?.name??item.agent_key} · {new Date(item.occurred_at).toLocaleString()}</small></div></article>})}</section>
        </div>
        <aside className="agent-side-column">
          <section className="agent-panel approval-panel"><header><div><small>HUMAN CONTROL</small><h2>Approval inbox</h2></div><span>{workspace.approvals.filter(item=>item.status==="awaiting").length+workspace.mutationIntents.filter(item=>item.status==="awaiting").length}</span></header>{workspace.mutationIntents.filter(item=>item.status==="awaiting").map(item=><article key={item.id}><span><em>{item.tool_key}</em><b>{item.risk_level} risk</b></span><strong>{item.summary}</strong><p>{item.environment?`${item.environment} · `:""}{item.resource_type}{item.resource_id?` ${item.resource_id}`:""}</p><small>Exact action {item.action_digest.slice(0,12)}… · expires {new Date(item.expires_at).toLocaleString()}</small>{canApprove&&<div><button onClick={()=>void act({action:"decide_mutation",intentId:item.id,decision:"rejected"})}>Reject</button><button onClick={()=>void act({action:"decide_mutation",intentId:item.id,decision:"approved"})}>Approve exact action</button></div>}</article>)}{workspace.approvals.filter(item=>item.status==="awaiting").map(item=><article key={item.id}><span><em>{item.approval_type}</em><b>{item.risk_level} risk</b></span><strong>{item.title}</strong><p>{item.summary}</p><small>Requested {new Date(item.requested_at).toLocaleString()}</small>{canApprove&&<div><button onClick={()=>void act({action:"decide",approvalId:item.id,decision:"rejected",note:"Rejected from Agent Workspace"})}>Reject</button><button onClick={()=>void act({action:"decide",approvalId:item.id,decision:"approved",note:"Approved from Agent Workspace"})}>Approve</button></div>}</article>)}{!workspace.approvals.some(item=>item.status==="awaiting")&&!workspace.mutationIntents.some(item=>item.status==="awaiting")&&<div className="agent-empty compact"><strong>Nothing needs approval</strong><p>Safe work continues automatically.</p></div>}</section>
          <section className="agent-panel"><header><div><small>SPECIALISTS</small><h2>Agent team</h2></div><span>{workspace.agents.length}</span></header><div className="agent-roster">{workspace.agents.map(agent=><article key={agent.key}><i style={{background:agent.color}}>{agent.shortName.slice(0,1)}</i><div><strong>{agent.name}</strong><p>{agent.description}</p><small>{workspace.workItems.filter(item=>item.assigned_agent_key===agent.key&&!['succeeded','cancelled'].includes(item.status)).length} active · {agent.tools.length} tools</small></div></article>)}</div></section>
          <section className="agent-panel"><header><div><small>DEPLOYMENT SAFETY</small><h2>Deployments</h2></div></header>{workspace.deployments.slice(0,6).map(item=><article className="agent-deployment" key={item.id}><span><strong>{item.environment}</strong><em>{statusLabel(item.status)}</em></span><small>{item.git_ref} · {new Date(item.created_at).toLocaleDateString()}</small>{item.url&&<a href={item.url} target="_blank" rel="noreferrer">Open deployment ↗</a>}</article>)}{!workspace.deployments.length&&<div className="agent-empty compact"><strong>No deployments yet</strong><p>Deployment and rollback history will appear here.</p></div>}</section>
        </aside>
      </section>
    </>}
  </div>;
}
