"use client";
import{FormEvent,useEffect,useMemo,useState}from"react";
type Project={id:string;name:string;domain:string};
type Proof={id:string;proof_type:string;title:string;summary:string;service:string|null;location:string|null;verification_status:string;storage_path:string|null;captured_at:string};
type Spec={id:string;opportunity_id:string;target_keyword:string;search_intent:string;creative_angle:string;status:string;expected_value:{expectedMonthlyProfit?:number;priorityScore?:number};proof_asset_ids:string[];created_at:string};
type Draft={id:string;creative_spec_id:string;title:string;meta_description:string;h1:string;summary:string;sections:Array<{heading:string;body:string}>;originality_score:number;evidence_coverage_score:number;helpfulness_score:number;conversion_score:number;qa_results:{passed?:boolean;blockers?:string[]};status:string;created_at:string};
type Opportunity={id:string;keyword:string;opportunity_score:number;confidence_score:number;action_type:string;priority:string};
type Workspace={proof:Proof[];specs:Spec[];drafts:Draft[];opportunities:Opportunity[];summary:{verifiedProof:number;proofNeeded:number;draftsToReview:number;approvedDrafts:number;attributedGrossProfit:number}};
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value||0);
const label=(value:string)=>value.replaceAll("_"," ");

export function CreativeStudio({projects,canWrite,canApprove}:{projects:Project[];canWrite:boolean;canApprove:boolean}){
  const[projectId,setProjectId]=useState(projects[0]?.id??""),[workspace,setWorkspace]=useState<Workspace|null>(null),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
  const specsByOpportunity=useMemo(()=>new Set((workspace?.specs??[]).map(item=>item.opportunity_id)),[workspace?.specs]);
  async function load(id=projectId){if(!id)return;setBusy(true);try{const response=await fetch(`/api/creatives?projectId=${encodeURIComponent(id)}`,{cache:"no-store"}),result=await response.json();if(!response.ok)throw new Error(result.error?.message);setWorkspace(result.workspace);setMessage("");}catch(error){setWorkspace(null);setMessage(error instanceof Error?error.message:"Creative Studio could not be loaded.");}finally{setBusy(false)}}
  useEffect(()=>{if(!projectId)return;const controller=new AbortController();fetch(`/api/creatives?projectId=${encodeURIComponent(projectId)}`,{cache:"no-store",signal:controller.signal}).then(async response=>({response,result:await response.json()})).then(({response,result})=>{if(!response.ok)throw new Error(result.error?.message);setWorkspace(result.workspace);setMessage("");setBusy(false)}).catch(error=>{if(error instanceof DOMException&&error.name==="AbortError")return;setWorkspace(null);setMessage(error instanceof Error?error.message:"Creative Studio could not be loaded.");setBusy(false)});return()=>controller.abort()},[projectId]);
  async function act(body:Record<string,unknown>){setBusy(true);setMessage("");try{const response=await fetch("/api/creatives",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,...body})}),result=await response.json();if(!response.ok){setMessage(result.error?.message??"The action could not be completed.");return;}setWorkspace(result.workspace);setMessage("Saved. Evidence and QA history are up to date.");}catch{setMessage("The Creative Studio could not reach the server.");}finally{setBusy(false)}}
  async function addProof(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),file=data.get("file");if(file instanceof File&&file.size){data.set("projectId",projectId);setBusy(true);try{const response=await fetch("/api/creatives/proof-upload",{method:"POST",body:data}),result=await response.json();if(!response.ok){setMessage(result.error?.message??"Proof upload failed.");return;}form.reset();await load();setMessage("Proof uploaded. Verify it before an agent may use it.");}finally{setBusy(false)}return;}await act({action:"add_proof",proofType:String(data.get("proofType")),title:String(data.get("title")),summary:String(data.get("summary")),sourceUrl:String(data.get("sourceUrl")||"")||undefined,service:String(data.get("service")||"")||undefined,location:String(data.get("location")||"")||undefined});form.reset();}
  if(!projects.length)return <section className="live-section"><div className="live-empty"><strong>Add a client first</strong><p>Creative proof and drafts are always isolated to one client project.</p></div></section>;
  return <div className="creative-studio"><div className="live-heading creative-heading"><div><small>COMPETITIVE CONTENT ENGINE</small><h1>Creative Studio</h1><p>Turn real business proof and search intent into original pages that competitors cannot copy.</p></div><div className="creative-project"><select value={projectId} onChange={event=>{setBusy(true);setWorkspace(null);setMessage("");setProjectId(event.target.value)}}>{projects.map(item=><option key={item.id} value={item.id}>{item.domain} · {item.name}</option>)}</select><button disabled={busy} onClick={()=>void load()}>{busy?"Working…":"Refresh"}</button></div></div>{message&&<div className="agent-message">{message}</div>}
  {workspace&&<><section className="creative-metrics"><article><small>VERIFIED PROOF</small><strong>{workspace.summary.verifiedProof}</strong><span>safe for agent use</span></article><article><small>NEEDS EVIDENCE</small><strong>{workspace.summary.proofNeeded}</strong><span>creative specifications</span></article><article><small>REVIEW INBOX</small><strong>{workspace.summary.draftsToReview}</strong><span>QA-passed drafts</span></article><article><small>ATTRIBUTED PROFIT</small><strong>{money(workspace.summary.attributedGrossProfit)}</strong><span>from recorded SEO leads</span></article></section>
  <section className="creative-grid"><div className="creative-main"><section className="creative-panel"><header><div><small>SEARCH-INTENT COMPILER</small><h2>Best creative opportunities</h2><p>Each specification combines search intent, page ownership, proof, conversion value, and QA requirements.</p></div></header>{workspace.opportunities.slice(0,12).map(item=><article className="creative-opportunity" key={item.id}><b>{item.opportunity_score}</b><div><strong>{item.keyword}</strong><span>{item.action_type} · {item.confidence_score}% evidence confidence · {item.priority}</span></div>{canWrite&&!specsByOpportunity.has(item.id)?<button disabled={busy} onClick={()=>void act({action:"create_spec",opportunityId:item.id})}>Build creative spec</button>:<em>{specsByOpportunity.has(item.id)?"Spec created":"View only"}</em>}</article>)}{!workspace.opportunities.length&&<div className="agent-empty"><strong>Run keyword discovery first</strong><p>The Research Agent will supply automatically discovered opportunities here.</p></div>}</section>
  <section className="creative-panel"><header><div><small>CREATIVE PIPELINE</small><h2>Evidence-gated specifications</h2></div></header>{workspace.specs.map(spec=><article className="creative-spec" key={spec.id}><div><span><em>{label(spec.status)}</em><b>{label(spec.search_intent)}</b></span><h3>{spec.target_keyword}</h3><p>{spec.creative_angle}</p><small>{spec.proof_asset_ids.length} proof assets · Directional expected profit {money(spec.expected_value?.expectedMonthlyProfit??0)}/mo · Priority {spec.expected_value?.priorityScore??0}</small></div>{canWrite&&["ready","generated"].includes(spec.status)&&<button disabled={busy} onClick={()=>void act({action:"generate_draft",specId:spec.id})}>{busy?"Generating…":"Generate evidence-safe draft"}</button>}{spec.status==="evidence_needed"&&<strong className="creative-warning">Verify two proof types first</strong>}</article>)}</section>
  <section className="creative-panel"><header><div><small>HUMAN REVIEW</small><h2>Drafts and deterministic QA</h2></div></header>{workspace.drafts.map(draft=><article className="creative-draft" key={draft.id}><div className="creative-draft-head"><div><span><em>{label(draft.status)}</em><b>{draft.qa_results?.passed?"QA passed":"QA blocked"}</b></span><h3>{draft.title}</h3><p>{draft.meta_description}</p></div><div className="creative-score"><strong>{Math.round((draft.originality_score+draft.evidence_coverage_score+draft.helpfulness_score+draft.conversion_score)/4)}</strong><small>QUALITY</small></div></div><div className="creative-score-grid"><span>Proof difference <b>{draft.originality_score}</b></span><span>Evidence <b>{draft.evidence_coverage_score}</b></span><span>Helpful <b>{draft.helpfulness_score}</b></span><span>Conversion <b>{draft.conversion_score}</b></span></div>{draft.qa_results?.blockers?.map(blocker=><p className="creative-blocker" key={blocker}>{blocker}</p>)}<details><summary>Preview draft</summary><h4>{draft.h1}</h4><p>{draft.summary}</p>{draft.sections.map((section,index)=><div key={index}><strong>{section.heading}</strong><p>{section.body}</p></div>)}</details>{canApprove&&draft.status==="awaiting_review"&&<button disabled={busy} onClick={()=>void act({action:"approve_draft",draftId:draft.id})}>Approve for implementation</button>}</article>)}{!workspace.drafts.length&&<div className="agent-empty"><strong>No generated drafts</strong><p>Verify real proof, create a specification, then let the Content Agent draft within those facts.</p></div>}</section></div>
  <aside><section className="creative-panel proof-vault"><header><div><small>BUSINESS PROOF ENGINE</small><h2>Proof Vault</h2><p>Photos, jobs, credentials, processes, and real answers make every page defensible and specific.</p></div></header>{canWrite&&<form onSubmit={event=>void addProof(event)}><label>Proof type<select name="proofType" defaultValue="project"><option value="project">Completed project</option><option value="photo">Real photo</option><option value="voice_note">Voice note</option><option value="credential">Credential</option><option value="review">Customer review</option><option value="process">Process detail</option><option value="material">Material detail</option><option value="warranty">Warranty</option><option value="pricing_factor">Pricing factor</option><option value="faq">Customer question</option><option value="service_area">Service area</option><option value="case_study">Case study</option><option value="other">Other</option></select></label><label>Short title<input name="title" minLength={3} maxLength={160} required placeholder="Roof replacement in Mandarin"/></label><label>What does this prove?<textarea name="summary" minLength={10} maxLength={5000} required placeholder="Specific facts an agent may safely use…"/></label><div><label>Service<input name="service" placeholder="Roof replacement"/></label><label>Location<input name="location" placeholder="Jacksonville, FL"/></label></div><label>Source link (optional)<input name="sourceUrl" type="url" placeholder="https://…"/></label><label>Photo, audio, or PDF (optional)<input name="file" type="file" accept="image/jpeg,image/png,image/webp,audio/mpeg,audio/mp4,audio/wav,application/pdf"/></label><button disabled={busy}>Add unverified proof</button></form>}<div className="proof-list">{workspace.proof.map(proof=><article key={proof.id}><span><em>{label(proof.proof_type)}</em><b className={proof.verification_status}>{label(proof.verification_status)}</b></span><strong>{proof.title}</strong><p>{proof.summary}</p><small>{[proof.service,proof.location].filter(Boolean).join(" · ")||new Date(proof.captured_at).toLocaleDateString()}</small>{canApprove&&proof.verification_status==="unverified"&&<div><button onClick={()=>void act({action:"verify_proof",proofId:proof.id,decision:"rejected"})}>Reject</button><button onClick={()=>void act({action:"verify_proof",proofId:proof.id,decision:"verified"})}>Verify</button></div>}</article>)}</div></section></aside></section></>}
  </div>;
}
