"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import type { GitHubSettingsSnapshot } from "@/lib/github/integration-settings";

function displayDate(value:string|null|undefined){return value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"No webhook received yet"}

export function GitHubSettingsPanel({snapshot,justConnected=false}:{snapshot:GitHubSettingsSnapshot;justConnected?:boolean}){
  const router=useRouter(),[message,setMessage]=useState(justConnected?"GitHub authorization completed. Select a repository to connect it to an HD SEO project.":""),[error,setError]=useState(snapshot.connectionError??""),[busy,setBusy]=useState<"test"|"disconnect"|"repository"|null>(null);
  const defaultProject=snapshot.projects[0],defaultRepository=snapshot.availableRepositories.find(repo=>!snapshot.connectedRepositories.some(item=>item.fullName===repo.fullName));
  const[projectId,setProjectId]=useState(defaultProject?.id??""),[repositoryId,setRepositoryId]=useState(defaultRepository?String(defaultRepository.id):"");
  const selectedProject=useMemo(()=>snapshot.projects.find(item=>item.id===projectId),[projectId,snapshot.projects]);
  const installation=snapshot.installation,connectHref=snapshot.selectedAgencyId&&selectedProject?`/api/github/install?agencyId=${encodeURIComponent(snapshot.selectedAgencyId)}&clientId=${encodeURIComponent(selectedProject.clientId)}&projectId=${encodeURIComponent(selectedProject.id)}`:snapshot.selectedAgencyId?`/api/github/install?agencyId=${encodeURIComponent(snapshot.selectedAgencyId)}`:"#";

  function chooseAgency(value:string){router.push(`/portal/admin/settings/github?agencyId=${encodeURIComponent(value)}`)}
  async function action(path:string,body:Record<string,unknown>,kind:"test"|"disconnect"|"repository"){
    setBusy(kind);setError("");setMessage("");
    try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.error?.message??"The GitHub operation failed.");setMessage(kind==="test"?`Connection verified. ${result.repositoryCount} repositories are available.`:kind==="disconnect"?"GitHub was disconnected and HD SEO access was removed.":"Repository connected to the selected project.");router.refresh();}
    catch(value){setError(value instanceof Error?value.message:"The GitHub operation failed.")}
    finally{setBusy(null)}
  }
  async function disconnect(){if(!snapshot.selectedAgencyId||!window.confirm("Disconnect GitHub and remove the HD SEO GitHub App installation? Automated repository access will stop immediately."))return;await action("/api/github/disconnect",{agencyId:snapshot.selectedAgencyId,confirm:true},"disconnect")}
  async function connectRepository(){if(!snapshot.selectedAgencyId||!installation||!selectedProject||!repositoryId)return;await action("/api/github/connect",{agencyId:snapshot.selectedAgencyId,clientId:selectedProject.clientId,projectId:selectedProject.id,installationId:installation.installationId,repositoryId:Number(repositoryId)},"repository")}

  return <div className="github-settings">
    <div className="github-settings-heading"><div><small>SETTINGS / GITHUB</small><h1>GitHub integration</h1><p>Authorize repositories, verify webhook delivery, and control HD SEO deployment access.</p></div>{snapshot.agencies.length>1&&<label>Agency workspace<select value={snapshot.selectedAgencyId??""} onChange={event=>chooseAgency(event.target.value)}>{snapshot.agencies.map(agency=><option value={agency.id} key={agency.id}>{agency.name}</option>)}</select></label>}</div>
    {message&&<div className="github-alert success" role="status">✓ {message}</div>}{error&&<div className="github-alert error" role="alert">{error}</div>}
    {!snapshot.selectedAgencyId?<section className="github-card github-empty"><h2>Create an agency first</h2><p>A GitHub installation must belong to an agency workspace.</p></section>:!installation?<section className="github-card github-connect-card"><div className="github-icon">⌘</div><div><small>NOT CONNECTED</small><h2>Connect GitHub to HD SEO</h2><p>Install the HD SEO GitHub App, choose the repositories it may access, and return here to bind them to client projects.</p>{snapshot.projects.length>0&&<label className="github-install-project">Initial client project<select value={projectId} onChange={event=>setProjectId(event.target.value)}>{snapshot.projects.map(project=><option value={project.id} key={project.id}>{project.clientName} — {project.name}</option>)}</select></label>}</div><a className="github-primary" href={connectHref}>Connect GitHub</a></section>:<>
      <section className="github-card github-status-card"><header><div><span className="github-status-dot"/><div><small>CONNECTION STATUS</small><h2>GitHub Connected</h2><p>{installation.accountLogin} · {installation.accountType}</p></div></div><span className="github-badge">ACTIVE</span></header><div className="github-status-grid"><div><small>INSTALLATION ID</small><strong>{installation.installationId}</strong></div><div><small>REPOSITORY ACCESS</small><strong>{installation.repositorySelection==="all"?"All repositories":"Selected repositories"}</strong></div><div><small>LAST SYNCED</small><strong>{displayDate(installation.lastSyncedAt)}</strong></div><div><small>LAST WEBHOOK RECEIVED</small><strong>{snapshot.lastWebhook?displayDate(snapshot.lastWebhook.receivedAt):"No webhook received yet"}</strong>{snapshot.lastWebhook&&<span>{snapshot.lastWebhook.eventType} · {snapshot.lastWebhook.status}</span>}</div></div><footer><button disabled={busy!==null} onClick={()=>void action("/api/github/test",{agencyId:snapshot.selectedAgencyId},"test")}>{busy==="test"?"Testing…":"Test Connection"}</button><button className="danger" disabled={busy!==null} onClick={()=>void disconnect()}>{busy==="disconnect"?"Disconnecting…":"Disconnect GitHub"}</button></footer></section>
      <section className="github-card"><div className="github-card-heading"><div><small>PROJECT BINDING</small><h2>Connect a repository</h2><p>Choose which GitHub repository HD SEO should use for each client website.</p></div></div>{snapshot.projects.length&&snapshot.availableRepositories.length?<div className="github-binding"><label>Client project<select value={projectId} onChange={event=>setProjectId(event.target.value)}>{snapshot.projects.map(project=><option value={project.id} key={project.id}>{project.clientName} — {project.name}</option>)}</select></label><label>GitHub repository<select value={repositoryId} onChange={event=>setRepositoryId(event.target.value)}>{snapshot.availableRepositories.map(repo=><option value={repo.id} key={repo.id}>{repo.fullName}</option>)}</select></label><button className="github-primary" disabled={!projectId||!repositoryId||busy!==null} onClick={()=>void connectRepository()}>{busy==="repository"?"Connecting…":"Connect repository"}</button></div>:<div className="github-inline-empty">{snapshot.projects.length?"No repositories are currently available to this installation.":"Create a client project before binding a repository."}</div>}</section>
      <section className="github-card"><div className="github-card-heading"><div><small>CONNECTED REPOSITORIES</small><h2>{snapshot.connectedRepositories.length} connected</h2></div></div>{snapshot.connectedRepositories.length?<div className="github-repository-list">{snapshot.connectedRepositories.map(repository=><article key={repository.id}><span>⌘</span><div><strong>{repository.fullName}</strong><small>{repository.projectName} · {repository.defaultBranch}</small></div><em>{repository.status}</em></article>)}</div>:<div className="github-inline-empty">No repositories have been connected to an HD SEO project yet.</div>}</section>
    </>}
  </div>;
}
