"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";

type Project={id:string;name:string;domain:string};
type Summary={spent:number;committed:number;remaining:number|null;organicSessions:number;conversions:number;leads:number;qualifiedLeads:number;bookedRevenue:number;grossProfit:number;returnOnSpend:number|null;averageRating:number|null;unansweredReviews:number;citationIssues:number};
type Connection={id:string;provider:string;status:string;selected_resource:string|null;last_synced_at:string|null;metadata:Record<string,unknown>};
type Snapshot={budget:Record<string,unknown>|null;allocations:Array<Record<string,unknown>>;transactions:Array<Record<string,unknown>>;metrics:Array<Record<string,unknown>>;leads:Array<Record<string,unknown>>;profiles:Array<Record<string,unknown>>;reviews:Array<Record<string,unknown>>;citations:Array<Record<string,unknown>>;outreach:Array<Record<string,unknown>>;connections:Connection[];syncs:Array<Record<string,unknown>>;summary:Summary};
const money=(value:number|null)=>value==null?"Not set":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
const label=(value:string)=>value.replace(/^google_/,"Google ").replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());

export function OutcomesControlCenter({projects,canManage=true,compact=false}:{projects:Project[];canManage?:boolean;compact?:boolean}){
  const[projectId,setProjectId]=useState(projects[0]?.id??""),[data,setData]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const connections=useMemo(()=>new Map((data?.connections??[]).map(item=>[item.provider,item])),[data]);
  async function load(){if(!projectId)return;setBusy(true);setMessage("");try{const response=await fetch(`/api/outcomes?projectId=${encodeURIComponent(projectId)}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Results could not be loaded.");setData(payload.data);}catch(error){setMessage(error instanceof Error?error.message:"Results could not be loaded.");setData(null);}finally{setBusy(false)}}
  useEffect(()=>{if(!projectId)return;let active=true;fetch(`/api/outcomes?projectId=${encodeURIComponent(projectId)}`,{cache:"no-store"}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Results could not be loaded.");if(active)setData(payload.data);}).catch(error=>{if(active){setMessage(error instanceof Error?error.message:"Results could not be loaded.");setData(null);}});return()=>{active=false};},[projectId]);
  async function post(body:Record<string,unknown>){setBusy(true);setMessage("");try{const response=await fetch("/api/outcomes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,projectId})}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"The action could not be completed.");setData(payload.data);setMessage("Saved and added to the audit trail.");}catch(error){setMessage(error instanceof Error?error.message:"The action could not be completed.");}finally{setBusy(false)}}
  async function sync(provider:string){setBusy(true);setMessage("");try{const response=await fetch("/api/google-suite/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,provider})}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Provider sync failed.");setMessage(`${label(provider)} synchronized.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Provider sync failed.");}finally{setBusy(false)}}
  async function syncAttribution(provider:"callrail"|"hubspot"){setBusy(true);setMessage("");try{const response=await fetch("/api/integrations/attribution",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"sync",projectId,provider})}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"Sync failed.");const result=payload.result as {records?:number;pages?:number;truncated?:boolean};setMessage(`${label(provider)} synchronized ${result.records??0} outcome record${result.records===1?"":"s"}${result.truncated?". The bounded sync reached its page limit and will continue from the overlap window on the next run.":"."}`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Sync failed.");}finally{setBusy(false)}}
  async function selectGoogleResource(provider:"google_analytics"|"google_business_profile",value:string){const[resource,account]=value.split("|||");const response=await fetch("/api/google-suite/select",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,provider,resource,account:account||undefined})}),payload=await response.json();if(!response.ok){setMessage(payload.error?.message??"The Google resource could not be selected.");return}setMessage("Google resource selected. Syncing evidence now…");await sync(provider);}
  async function connectAttribution(event:FormEvent<HTMLFormElement>,provider:"callrail"|"hubspot"){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);setBusy(true);setMessage("");try{const response=await fetch("/api/integrations/attribution",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"connect",projectId,provider,token:String(form.get("token")),accountId:provider==="callrail"?String(form.get("accountId")):undefined})}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message??"The provider could not be connected.");formElement.reset();await load();setMessage(`${label(provider)} connected securely.`);}catch(error){setMessage(error instanceof Error?error.message:"The provider could not be connected.");}finally{setBusy(false)}}
  function attributionSetup(provider:"callrail"|"hubspot",summary:string){return <details className="outcomes-provider-setup"><summary>{summary}</summary><form className="outcomes-form" onSubmit={event=>void connectAttribution(event,provider)}>{provider==="callrail"&&<label>CallRail account ID<input name="accountId" placeholder="ACC…" required autoComplete="off"/></label>}<label>{provider==="callrail"?"CallRail API v3 key":"HubSpot Service Key"}<input name="token" type="password" minLength={20} required autoComplete="new-password"/></label><button disabled={busy}>Verify, encrypt and replace connection</button><small>{provider==="callrail"?"Use an API v3 key that can read the selected account. HD SEO uses CallRail token authentication and bounded, incremental pagination.":"Use a HubSpot Service Key with crm.objects.contacts.read. Sync is incremental and bounded; HubSpot webhooks are not required."} The credential is verified server-side, encrypted before storage, and never returned to the browser.</small></form></details>}
  function budget(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),limit=Number(form.get("monthlyLimit")),warningPercent=Number(form.get("warningPercent")),values=[25,20,15,15,10,10,5,0],categories=["data","content","technical","local","authority","implementation","software","reserve"];void post({action:"configure_budget",monthlyLimit:limit,warningPercent,hardStop:true,allocations:categories.map((category,index)=>({category,monthlyAmount:+(limit*values[index]/100).toFixed(2),approvalThreshold:category==="authority"||category==="content"?100:0}))});}
  function lead(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void post({action:"record_lead",source:String(form.get("source")),externalId:`manual:${crypto.randomUUID()}`,leadType:String(form.get("leadType")),status:"recorded",qualified:form.get("qualified")==="on",revenue:Number(form.get("revenue"))||0,grossProfit:Number(form.get("grossProfit"))||0,occurredAt:new Date().toISOString(),metadata:{recordedManually:true}});event.currentTarget.reset();}
  if(!projects.length)return <section className="live-section"><h1>Results and budget</h1><p>Add a client project first.</p></section>;
  return <section className={`live-section outcomes-center${compact?" compact":""}`}>
    <div className="live-section-head"><div><small>OUTCOMES CONTROL PLANE</small><h1>Results, attribution and SEO budget</h1><p>Only verified provider data and recorded business outcomes count. Directional search value is kept separate from revenue.</p></div><div className="outcomes-toolbar"><select value={projectId} onChange={event=>setProjectId(event.target.value)}>{projects.map(item=><option value={item.id} key={item.id}>{item.name} · {item.domain}</option>)}</select><button disabled={busy} onClick={()=>void load()}>{busy?"Working…":"Refresh"}</button></div></div>
    {message&&<p className="outcomes-message">{message}</p>}
    {data&&<>
      <div className="live-metrics outcomes-metrics"><article><small>ACTUAL SEO SPEND</small><strong>{money(data.summary.spent)}</strong><span>{money(data.summary.remaining)} remaining this month</span></article><article><small>ORGANIC SESSIONS</small><strong>{data.summary.organicSessions.toLocaleString()}</strong><span>{data.summary.conversions.toLocaleString()} measured conversions</span></article><article><small>QUALIFIED LEADS</small><strong>{data.summary.qualifiedLeads}</strong><span>{data.summary.leads} total recorded</span></article><article><small>RECORDED GROSS PROFIT</small><strong>{money(data.summary.grossProfit)}</strong><span>{data.summary.returnOnSpend==null?"Waiting for real cost and outcome data":`${data.summary.returnOnSpend.toFixed(2)}× verified gross-profit/spend`}</span></article></div>
      <div className="outcomes-grid"><article className="outcomes-panel"><header><small>MEASUREMENT CONNECTIONS</small><h2>Bring in real outcomes</h2></header>{(["google_analytics","google_business_profile"] as const).map(provider=>{const connection=connections.get(provider),resources=provider==="google_analytics"?(connection?.metadata?.properties as Array<{property:string;displayName:string}>|undefined)?.map(item=>({value:item.property,label:item.displayName})):(connection?.metadata?.locations as Array<{name:string;title:string;account:string}>|undefined)?.map(item=>({value:`${item.name}|||${item.account}`,label:item.title})),returnUrl=encodeURIComponent("/portal/agency?tab=Results%20%26%20budget");return <div className="outcomes-connection" key={provider}><div><strong>{label(provider)}</strong><span>{connection?`Connected${connection.last_synced_at?` · synced ${new Date(connection.last_synced_at).toLocaleDateString()}`:""}`:"Not connected"}</span></div>{connection?.selected_resource?<button disabled={busy} onClick={()=>void sync(provider)}>Sync now</button>:connection&&resources?.length?<select aria-label={`Choose ${label(provider)} resource`} defaultValue="" onChange={event=>{if(event.target.value)void selectGoogleResource(provider,event.target.value)}}><option value="" disabled>Choose property…</option>{resources.map(item=><option value={item.value} key={item.value}>{item.label}</option>)}</select>:connection?<button disabled={busy} onClick={()=>void sync(provider)}>Retry discovery</button>:<a href={`/api/google-suite/connect?projectId=${projectId}&provider=${provider}&returnUrl=${returnUrl}`}>Connect</a>}</div>})}{(["callrail","hubspot"] as const).map(provider=>{const connection=connections.get(provider),accountName=typeof connection?.metadata?.accountName==="string"?connection.metadata.accountName:null,lastRecords=Number(connection?.metadata?.lastRecordsWritten??0),health=connection?.metadata?.health;return <div key={provider}>{connection?<><div className="outcomes-connection"><div><strong>{label(provider)}{accountName?` · ${accountName}`:""}</strong><span>{health==="partial"?"Connected · bounded sync partially complete":`Connected securely${connection.last_synced_at?` · synced ${new Date(connection.last_synced_at).toLocaleDateString()}`:""}`} · {lastRecords} records last run</span></div><button disabled={busy} onClick={()=>void syncAttribution(provider)}>Sync now</button></div>{canManage&&attributionSetup(provider,provider==="hubspot"?"Replace HubSpot Service Key":"Replace CallRail API key")}</>:canManage&&attributionSetup(provider,`Connect ${label(provider)}`)}</div>})}</article>
      <article className="outcomes-panel"><header><small>MONTHLY GUARDRAIL</small><h2>{data.budget?`${money(Number(data.budget.monthly_limit))} maximum`:"Set the working budget"}</h2></header>{canManage&&<form className="outcomes-form" onSubmit={budget}><label>Monthly SEO working budget<input name="monthlyLimit" type="number" min="0" max="10000000" step="100" defaultValue={String(data.budget?.monthly_limit??1000)} required/></label><label>Warn me when the budget reaches<input name="warningPercent" type="number" min="1" max="100" defaultValue={String(data.budget?.warning_percent??80)} required/></label><div className="outcomes-budget-lock"><strong>Hard stop is on</strong><span>HD SEO must reject new tracked spend after this ceiling. Saving a budget does not charge the customer or authorize a purchase.</span></div><button disabled={busy}>Save budget guardrail</button><small>Planning allocation: 25% evidence, 20% content, 15% technical, 15% local, 10% authority, 10% implementation and 5% software. Content and authority purchases still require approval.</small></form>}</article>
      <article className="outcomes-panel"><header><small>BUSINESS OUTCOME</small><h2>Record a verified lead or sale</h2></header>{canManage&&<form className="outcomes-form" onSubmit={lead}><label>Source<select name="source"><option value="manual">Verified manually</option><option value="callrail">CallRail</option><option value="crm">CRM</option></select></label><label>Outcome<select name="leadType"><option value="call">Phone call</option><option value="form">Form lead</option><option value="booking">Booking</option><option value="sale">Sale</option></select></label><label>Revenue<input name="revenue" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Gross profit<input name="grossProfit" type="number" min="0" step="0.01" defaultValue="0"/></label><label className="outcomes-check"><input name="qualified" type="checkbox"/> Qualified customer opportunity</label><button disabled={busy}>Record outcome</button></form>}</article>
      <article className="outcomes-panel"><header><small>LOCAL PRESENCE</small><h2>Reputation and listings</h2></header><div className="outcomes-facts"><p><b>{data.profiles.length}</b> Business Profile location{data.profiles.length===1?"":"s"}</p><p><b>{data.summary.averageRating??"—"}</b> average review rating</p><p><b>{data.summary.unansweredReviews}</b> unanswered reviews</p><p><b>{data.summary.citationIssues}</b> citation issues</p></div><small>Profile edits, review replies, citation submissions, outreach and external spend always require the configured approval and budget policy.</small></article></div>
    </>}
  </section>;
}
