"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import type { PortalIdentity,PortalRole } from "@/lib/auth/portal-types";

const adminNavigation=["Platform overview","Agencies","System health","Usage & billing","Access control","Audit log"];
const clientNavigation=["Results overview","Rankings","Recommended work","Approvals","Reports","Messages"];
const adminMetrics=[{label:"ACTIVE AGENCIES",value:"24",detail:"3 onboarding",change:"+4"},{label:"MANAGED CLIENTS",value:"186",detail:"Across all agencies",change:"+18"},{label:"RUNNING JOBS",value:"38",detail:"No stalled workers",change:"Healthy"},{label:"PLATFORM UPTIME",value:"99.98%",detail:"Past 30 days",change:"Stable"}];
const clientMetrics=[{label:"SEO HEALTH",value:"86",detail:"Strong",change:"+7"},{label:"TOP 10 KEYWORDS",value:"28",detail:"6 new this month",change:"+6"},{label:"ORGANIC LEADS",value:"47",detail:"Past 30 days",change:"+14%"},{label:"PENDING APPROVALS",value:"2",detail:"Your decision needed",change:"Review"}];

export function PortalDashboard({portal,identity,demo=false}:{portal:Exclude<PortalRole,"agency">;identity:PortalIdentity;demo?:boolean}){
  const isAdmin=portal==="admin",router=useRouter(),[active,setActive]=useState(isAdmin?adminNavigation[0]:clientNavigation[0]),[toast,setToast]=useState("");const navigation=isAdmin?adminNavigation:clientNavigation,metrics=isAdmin?adminMetrics:clientMetrics;
  async function signOut(){await createSupabaseBrowserClient()?.auth.signOut();router.push("/");router.refresh();}
  function notify(value:string){setToast(value);window.setTimeout(()=>setToast(""),2400);}
  return <main className={`role-dashboard role-${portal}`}>
    <aside className="role-sidebar"><Link className="role-brand" href="/"><span className="login-mark"><i/><b/></span><span>HD <em>SEO</em></span></Link><div className="role-workspace"><span>{isAdmin?"HD":"KR"}</span><div><small>{isAdmin?"PLATFORM":"CLIENT WORKSPACE"}</small><strong>{identity.organization}</strong></div></div><nav>{navigation.map((item,index)=><button className={active===item?"active":""} key={item} onClick={()=>setActive(item)}><span>{["⌂","◇","◎","▤","♙","◫"][index]}</span>{item}</button>)}</nav><div className="role-user"><span>{identity.displayName.slice(0,2).toUpperCase()}</span><div><strong>{identity.displayName}</strong><small>{demo?"Demo access":identity.role.replaceAll("_"," ")}</small></div><button onClick={signOut} aria-label="Sign out">↪</button></div></aside>
    <section className="role-main"><header><div><small>{isAdmin?"ADMIN PORTAL":"CLIENT PORTAL"}</small><strong>{active}</strong></div><div><button onClick={()=>notify("Notifications marked as read")}>♢</button><button className="role-primary" onClick={()=>notify(isAdmin?"Agency setup opened":"Message sent to your SEO team")}>{isAdmin?"＋ Add agency":"Message agency"}</button></div></header><div className="role-content">{demo&&<div className="demo-banner"><span>DEMO ACCESS</span><p>This preview shows the {isAdmin?"platform administration":"client results"} workspace with synthetic data.</p><Link href={`/login/${portal}`}>Sign in securely →</Link></div>}<div className="role-hero"><div><small>{isAdmin?"PLATFORM COMMAND":"YOUR SEO PERFORMANCE"}</small><h1>{isAdmin?"Platform overview":`Welcome back, ${identity.displayName}`}</h1><p>{isAdmin?"Control access, reliability, and operations across every HD SEO workspace.":"Your clearest opportunities, completed work, and measurable search progress in one place."}</p></div><button onClick={()=>notify(isAdmin?"System status refreshed":"Latest report opened")}>{isAdmin?"↻ Refresh status":"View latest report"}</button></div><section className="role-metrics">{metrics.map(item=><button key={item.label} onClick={()=>notify(`${item.label.toLowerCase()} details opened`)}><small>{item.label}</small><strong>{item.value}</strong><span>{item.detail}</span><em>{item.change}</em></button>)}</section>{isAdmin?<AdminWorkspace notify={notify}/>:<ClientWorkspace notify={notify}/>}</div></section>{toast&&<div className="toast" role="status"><span>✓</span>{toast}</div>}
  </main>;
}

function AdminWorkspace({notify}:{notify:(value:string)=>void}){const rows=[{name:"HD SEO Agency",plan:"Enterprise",clients:12,health:"Healthy",usage:"$84 / $150"},{name:"Summit Growth",plan:"Pro",clients:8,health:"Healthy",usage:"$61 / $100"},{name:"Northstar Digital",plan:"Pro",clients:15,health:"Review",usage:"$96 / $100"}];return <><section className="role-focus"><div><span>SYSTEM READINESS</span><h2>All critical services operational</h2><p>Automation workers, provider controls, repository execution, and monitoring queues are healthy.</p></div><div className="readiness-ring"><strong>100</strong><small>READY</small></div><button onClick={()=>notify("Detailed system health opened")}>View system health →</button></section><section className="role-table"><header><div><h2>Agency operations</h2><p>Tenants, client load, and authorized data usage</p></div><button onClick={()=>notify("Agency directory opened")}>View all agencies →</button></header><div>{rows.map(row=><article key={row.name}><span className="agency-tile">{row.name.slice(0,2).toUpperCase()}</span><div><strong>{row.name}</strong><small>{row.plan} plan</small></div><dl><div><dt>Clients</dt><dd>{row.clients}</dd></div><div><dt>System</dt><dd>{row.health}</dd></div><div><dt>Usage</dt><dd>{row.usage}</dd></div></dl><button onClick={()=>notify(`${row.name} administration opened`)}>Manage</button></article>)}</div></section></>}

function ClientWorkspace({notify}:{notify:(value:string)=>void}){return <><section className="client-win"><div><span>BIGGEST OPPORTUNITY</span><h2>Move “roof repair Jacksonville” into the Top 3</h2><p>Your page currently ranks #6. The agency prepared a focused improvement plan supported by ranking and competitor evidence.</p><div><button onClick={()=>notify("Recommendation approved")}>Approve recommendation</button><button onClick={()=>notify("Evidence report opened")}>View evidence</button></div></div><aside><small>OPPORTUNITY SCORE</small><strong>94</strong><span>High confidence</span></aside></section><section className="client-progress"><header><div><h2>Recent progress</h2><p>What your SEO team completed and what changed</p></div><button onClick={()=>notify("Full activity opened")}>View all activity →</button></header><div><article><span>+12</span><div><strong>Average ranking positions gained</strong><p>Across priority service keywords in the last 30 days</p></div><em>MEASURED</em></article><article><span>✓</span><div><strong>Emergency roof repair content improved</strong><p>Approved June 18 · Monitoring through July 18</p></div><em>COMPLETED</em></article><article><span>2</span><div><strong>Recommendations need your approval</strong><p>Both include scope, evidence, and expected milestone</p></div><button onClick={()=>notify("Approvals opened")}>Review</button></article></div></section></>}
