import "server-only";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { decideCheckpoint, cooldownDays } from "@/lib/seo/monitoring";

export async function processOneMonitoringCheckpoint(workerId=crypto.randomUUID()){
  const db=createSupabaseAdminClient();if(!db)throw new Error("Supabase is not configured.");const claim=await db.rpc("claim_seo_monitoring_checkpoint",{p_worker_id:workerId,p_lock_seconds:300}),checkpoint=(claim.data??[])[0];if(!checkpoint)return{status:"idle"};
  try{const planResult=await db.from("seo_monitoring_plans").select("*,seo_executions(action_type,agency_id,client_organization_id),seo_opportunities(target_milestone)").eq("id",checkpoint.monitoring_plan_id).single(),plan=planResult.data;if(!plan)throw new Error("Monitoring plan missing");const freshSince=new Date(Date.now()-3*86_400_000).toISOString(),ranking=plan.keyword_id?await db.from("organic_ranking_snapshots").select("position,ranking_url,collected_at").eq("project_id",plan.project_id).eq("keyword_id",plan.keyword_id).gte("collected_at",freshSince).order("collected_at",{ascending:false}).limit(1).maybeSingle():{data:null},decision=decideCheckpoint({checkpointDay:checkpoint.checkpoint_day,baseline:plan.baseline_position,position:ranking.data?.position==null?null:Number(ranking.data.position),rankingUrl:ranking.data?.ranking_url??null,targetUrl:plan.target_url,targetMilestone:plan.target_milestone,fresh:Boolean(ranking.data)}),terminal=decision==="MILESTONE_REACHED"||checkpoint.checkpoint_day===90;await db.from("seo_monitoring_checkpoints").update({status:decision==="MILESTONE_REACHED"?"milestone_reached":decision==="INCONCLUSIVE"?"inconclusive":"recorded",decision,position:ranking.data?.position??null,ranking_url:ranking.data?.ranking_url??null,collected_at:new Date().toISOString(),evidence:{source:"stored_ranking_snapshot",capturedAt:ranking.data?.collected_at??null,disclaimer:"Ranking movement observed since implementation; causation is not claimed."},worker_id:null,locked_at:null,lock_expires_at:null}).eq("id",checkpoint.id);if(terminal){const execution=Array.isArray(plan.seo_executions)?plan.seo_executions[0]:plan.seo_executions;await Promise.all([db.from("seo_monitoring_plans").update({status:decision==="INCONCLUSIVE"?"inconclusive":"completed"}).eq("id",plan.id),db.from("seo_executions").update({status:"completed"}).eq("id",plan.execution_id),db.from("seo_opportunities").update({status:decision==="MILESTONE_REACHED"?"completed":"open",cooldown_until:new Date(Date.now()+cooldownDays(execution?.action_type??"LINK")*86_400_000).toISOString()}).eq("id",plan.opportunity_id)]);}return{status:"recorded",checkpointId:checkpoint.id,decision,terminal};}
  catch{await db.from("seo_monitoring_checkpoints").update({status:"failed",worker_id:null,locked_at:null,lock_expires_at:null,error_details:{retryable:true}}).eq("id",checkpoint.id);return{status:"failed",checkpointId:checkpoint.id};}
}
