import { z } from "zod";
import { requireLiveAgencyProject } from "@/lib/auth/live-tenant";
import { parseJson } from "@/lib/api/request";
import { ApiError,jsonError } from "@/lib/api/errors";
import { auditEvent,requireAdminDb } from "@/lib/automation/control-plane";

const schema=z.object({agencyId:z.string().uuid(),clientId:z.string().uuid(),projectId:z.string().uuid(),repositoryId:z.string().uuid(),acknowledgeHumanApprovedExecution:z.literal(true)});
export async function GET(request:Request){try{const url=new URL(request.url),projectId=url.searchParams.get("projectId"),agencyId=url.searchParams.get("agencyId"),clientId=url.searchParams.get("clientId");if(!projectId||!agencyId||!clientId)throw new ApiError("Agency, client, and project are required.",400,"VALIDATION_ERROR");const context=await requireLiveAgencyProject({projectId,permission:"integrations.manage"});if(context.agencyId!==agencyId||context.clientId!==clientId)throw new ApiError("Repository setup does not belong to this business.",403,"TENANT_DENIED");const db=requireAdminDb(),result=await db.rpc("github_execution_readiness",{target_agency:context.agencyId,target_project:context.project.id});if(result.error)throw new ApiError("GitHub readiness could not be evaluated.",500,"OPERATION_FAILED");return Response.json({ok:true,GITHUB_EXECUTION_READINESS:result.data});}catch(error){return jsonError(error)}}
export async function POST(request:Request){try{const input=await parseJson(request,schema),context=await requireLiveAgencyProject({projectId:input.projectId,permission:"integrations.manage"});if(context.agencyId!==input.agencyId||context.clientId!==input.clientId)throw new ApiError("Repository setup does not belong to this business.",403,"TENANT_DENIED");const db=requireAdminDb(),project=await db.from("seo_projects").select("manual_workflow_verified_at").eq("id",input.projectId).eq("agency_id",context.agencyId).single();if(!project.data?.manual_workflow_verified_at)throw new ApiError("Verify the GitHub and Vercel safety baseline before enabling repository execution.",409,"CONFLICT");const repository=await db.from("repositories").select("id,status").eq("id",input.repositoryId).eq("project_id",input.projectId).eq("agency_id",context.agencyId).single();if(!repository.data||repository.data.status!=="active")throw new ApiError("An active repository connection is required.",409,"CONFLICT");await Promise.all([db.from("agencies").update({repository_execution_enabled:true}).eq("id",context.agencyId),db.from("seo_projects").update({repository_execution_enabled:true}).eq("id",input.projectId),db.from("repositories").update({repository_execution_enabled:true,updated_at:new Date().toISOString()}).eq("id",input.repositoryId)]);const readiness=await db.rpc("github_execution_readiness",{target_agency:context.agencyId,target_project:input.projectId});await auditEvent({agencyId:context.agencyId,actorUserId:context.userId,action:"github.repository_execution.enabled",resourceType:"repository",resourceId:input.repositoryId,request,afterState:{readiness:readiness.data}});return Response.json({ok:true,GITHUB_EXECUTION_READINESS:readiness.data});}catch(error){return jsonError(error)}}
