import "server-only";

import { env,hasCreativeModelConfig,hasDataForSeoConfig,hasGitHubConfig,hasGoogleSearchConsoleConfig,hasSupabaseAdminConfig } from "@/lib/config/env";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

type ReadinessState="ready"|"warning"|"blocked"|"unknown";
type Check={key:string;label:string;state:ReadinessState;detail:string;lastSeenAt?:string|null;count?:number|null};
const missingTable=(error:unknown)=>/schema cache|does not exist|PGRST205/i.test(String((error as {message?:string}|null)?.message??error));

export async function platformReadiness(){
  const db=createSupabaseAdminClient(),checks:Check[]=[];
  if(!db){checks.push({key:"database",label:"Supabase database",state:"blocked",detail:"Service-role configuration is missing."});return{ready:false,productionReady:false,checks,queue:{queued:0,running:0,retryScheduled:0,deadLetter:0,oldestQueuedAt:null},heartbeats:[],lastSuccessfulAutomationAt:null};}
  const required=["agencies","seo_projects","background_jobs","integration_connections","evidence_collection_runs","project_evidence_policies","seo_page_snapshots","search_console_rows","agent_definitions","agent_work_items","agent_approvals","agent_memory","agent_tool_executions","business_proof_assets","seo_creative_specs","seo_creative_drafts","seo_leads","production_acceptance_runs","production_acceptance_steps","cms_publications"];
  for(const table of required){const result=await db.from(table).select("*",{head:true,count:"exact"}).limit(0);checks.push({key:`table:${table}`,label:`Database · ${table}`,state:result.error?(missingTable(result.error)?"blocked":"warning"):"ready",detail:result.error?(missingTable(result.error)?"Migration is not applied.":"The table could not be checked."):"Available",count:result.count??0});}
  const [queued,running,retry,dead,oldest,heartbeats,acceptance,github,vercel,gsc,websites,cmsConnections,repositories,cmsPublished,cmsRolledBack,searchRows,latestSearchRow,latestCrawl]=await Promise.all([
    db.from("background_jobs").select("id",{head:true,count:"exact"}).eq("status","queued"),db.from("background_jobs").select("id",{head:true,count:"exact"}).eq("status","running"),db.from("background_jobs").select("id",{head:true,count:"exact"}).eq("status","retry_scheduled"),db.from("background_jobs").select("id",{head:true,count:"exact"}).eq("status","dead_letter"),db.from("background_jobs").select("created_at").in("status",["queued","retry_scheduled"]).order("created_at",{ascending:true}).limit(1).maybeSingle(),db.from("system_heartbeats").select("component,status,last_seen_at,metadata").order("last_seen_at",{ascending:false}),db.from("production_acceptance_runs").select("completed_at").eq("status","succeeded").eq("environment","production").order("completed_at",{ascending:false}).limit(1).maybeSingle(),db.from("github_installations").select("id",{head:true,count:"exact"}).eq("status","active"),db.from("vercel_connections").select("id",{head:true,count:"exact"}).eq("status","active"),db.from("integration_connections").select("id",{head:true,count:"exact"}).eq("provider","google_search_console").eq("status","active"),db.from("websites").select("id",{head:true,count:"exact"}).eq("status","active"),db.from("cms_connections").select("id",{head:true,count:"exact"}).eq("status","active").eq("connection_mode","api"),db.from("repository_connections").select("id",{head:true,count:"exact"}).eq("status","connected"),db.from("cms_publications").select("id",{head:true,count:"exact"}).eq("status","published"),db.from("cms_publications").select("id",{head:true,count:"exact"}).eq("status","rolled_back"),db.from("search_console_rows").select("id",{head:true,count:"exact"}),db.from("search_console_rows").select("captured_at").order("captured_at",{ascending:false}).limit(1).maybeSingle(),db.from("evidence_collection_runs").select("completed_at,records_written").eq("run_type","crawl").eq("status","succeeded").order("completed_at",{ascending:false}).limit(1).maybeSingle(),
  ]);
  const queue={queued:queued.count??0,running:running.count??0,retryScheduled:retry.count??0,deadLetter:dead.count??0,oldestQueuedAt:(oldest.data as {created_at?:string}|null)?.created_at??null};
  const heartbeatRows=(heartbeats.data??[]) as Array<{component:string;status:string;last_seen_at:string;metadata:Record<string,unknown>}>,heartbeatMap=new Map(heartbeatRows.map(row=>[row.component,row]));
  const heartbeatState=(component:string)=>{const row=heartbeatMap.get(component);if(!row)return{state:"unknown" as ReadinessState,detail:"No scheduler invocation has been recorded yet.",lastSeenAt:null};const stale=Date.now()-new Date(row.last_seen_at).getTime()>15*60_000;return{state:row.status==="healthy"&&!stale?"ready" as ReadinessState:stale?"warning" as ReadinessState:"blocked" as ReadinessState,detail:stale?"Scheduler invocation is older than 15 minutes.":row.status==="healthy"?"Scheduler is invoking normally.":"Scheduler reported a degraded or failed invocation.",lastSeenAt:row.last_seen_at};};
  const seoScheduler=heartbeatState("scheduler:seo"),automationScheduler=heartbeatState("scheduler:automation");
  checks.push({key:"scheduler:seo",label:"SEO evidence scheduler",state:env.CRON_SECRET?seoScheduler.state:"blocked",detail:env.CRON_SECRET?seoScheduler.detail:"CRON_SECRET is not configured.",lastSeenAt:seoScheduler.lastSeenAt});
  checks.push({key:"scheduler:automation",label:"Deployment and agent scheduler",state:env.CRON_SECRET?automationScheduler.state:"blocked",detail:env.CRON_SECRET?automationScheduler.detail:"CRON_SECRET is not configured.",lastSeenAt:automationScheduler.lastSeenAt});
  const crawl=(latestCrawl.data as {completed_at?:string;records_written?:number}|null),crawlAge=crawl?.completed_at?Date.now()-new Date(crawl.completed_at).getTime():null,crawlStale=crawlAge==null||crawlAge>7*86_400_000;
  checks.push({key:"crawler",label:"Website crawler evidence",state:!crawl?"unknown":crawlStale?"warning":"ready",detail:!crawl?"No successful production crawl has been recorded.":crawlStale?"The most recent successful crawl is older than seven days.":`${crawl.records_written??0} pages were written by the latest successful crawl.`,lastSeenAt:crawl?.completed_at??null});
  checks.push({key:"github",label:"GitHub App",state:hasGitHubConfig&&github.count?"ready":hasGitHubConfig?"warning":"blocked",detail:!hasGitHubConfig?"GitHub App credentials are incomplete.":github.count?`${github.count} active installation${github.count===1?"":"s"}.`:"Credentials exist, but no active installation is bound.",count:github.count??0});
  checks.push({key:"vercel",label:"Vercel deployment access",state:!env.VERCEL_ACCESS_TOKEN?"blocked":vercel.count?"ready":"warning",detail:!env.VERCEL_ACCESS_TOKEN?"Vercel access token is not configured.":vercel.count?(env.VERCEL_WEBHOOK_SECRET?"A Vercel connection, webhook, and polling fallback are configured.":"A Vercel connection and polling fallback are configured; webhook secret is not set."):"A platform token exists, but no agency Vercel connection is configured.",count:vercel.count??0});
  checks.push({key:"dataforseo",label:"DataForSEO",state:hasDataForSeoConfig?"ready":"warning",detail:hasDataForSeoConfig?"Provider credentials configured; paid actions remain confirmation-gated.":"Provider credentials are not configured."});
  const searchCount=searchRows.count??0,searchSeen=(latestSearchRow.data as {captured_at?:string}|null)?.captured_at??null;
  checks.push({key:"search_console",label:"Google Search Console evidence",state:!hasGoogleSearchConsoleConfig?"blocked":!gsc.count?"warning":searchCount?"ready":"warning",detail:!hasGoogleSearchConsoleConfig?"OAuth credentials are not configured.":!gsc.count?"OAuth is configured; connect a project property.":searchCount?`${searchCount} evidence rows are available from ${gsc.count} active project connection${gsc.count===1?"":"s"}.`:"A property is connected, but it has produced zero Search Console rows.",count:searchCount,lastSeenAt:searchSeen});
  checks.push({key:"cms",label:"Website read access",state:websites.count?"ready":"warning",detail:websites.count?`${websites.count} verified website connection${websites.count===1?"":"s"}.`:"No website has been verified yet.",count:websites.count??0});
  const repositoryWriters=repositories.count??0,directCmsCredentials=cmsConnections.count??0,directCmsPublishes=cmsPublished.count??0,directCmsRollbacks=cmsRolledBack.count??0,publishingReady=Boolean(repositoryWriters||directCmsPublishes);
  checks.push({key:"publishing",label:"Verified publishing path",state:publishingReady?"ready":"warning",detail:repositoryWriters?`${repositoryWriters} connected repository execution path${repositoryWriters===1?" is":"s are"} available. ${directCmsCredentials} direct CMS credential set${directCmsCredentials===1?" is":"s are"} verified.`:directCmsPublishes?`${directCmsPublishes} provider-native CMS publication${directCmsPublishes===1?" has":"s have"} succeeded; ${directCmsRollbacks} rollback${directCmsRollbacks===1?" has":"s have"} been proven.`:`${directCmsCredentials} direct CMS credential set${directCmsCredentials===1?" is":"s are"} verified, but a controlled production publication has not passed yet.`,count:repositoryWriters+directCmsPublishes});
  checks.push({key:"pagespeed",label:"PageSpeed / Lighthouse",state:env.PAGESPEED_API_KEY?"ready":"warning",detail:env.PAGESPEED_API_KEY?"API key configured.":"PageSpeed API key is not configured; deployment checks will be limited."});
  checks.push({key:"creative_model",label:"Creative generation model",state:hasCreativeModelConfig?"ready":"warning",detail:hasCreativeModelConfig?`${env.OPENAI_CREATIVE_MODEL} is configured; generation remains proof- and approval-gated.`:"OPENAI_API_KEY is not configured; production copy generation is paused."});
  checks.push({key:"email",label:"Email delivery",state:env.RESEND_API_KEY&&env.RESEND_FROM_EMAIL?"ready":"warning",detail:env.RESEND_API_KEY&&env.RESEND_FROM_EMAIL?"Resend credentials are configured; delivery acceptance must still be tested.":"Resend is not configured; invitations and operational email are unavailable."});
  checks.push({key:"billing",label:"Billing and entitlements",state:"warning",detail:env.STRIPE_SECRET_KEY&&env.STRIPE_WEBHOOK_SECRET?"Stripe credentials exist, but checkout, entitlement, and lifecycle acceptance must still be proven.":"Stripe is not configured; public self-service billing is unavailable."});
  checks.push({key:"queue",label:"Queue health",state:queue.deadLetter>0||queue.retryScheduled>0?"warning":"ready",detail:queue.deadLetter?`${queue.deadLetter} job${queue.deadLetter===1?"":"s"} in dead letter.`:queue.retryScheduled?`${queue.retryScheduled} job${queue.retryScheduled===1?"":"s"} waiting for retry.`:"No dead-letter jobs."});
  const lastSuccessfulAutomationAt=(acceptance.data as {completed_at?:string}|null)?.completed_at??null;
  checks.push({key:"automation",label:"Production acceptance run",state:lastSuccessfulAutomationAt?"ready":"unknown",detail:lastSuccessfulAutomationAt?"A complete production acceptance run is recorded.":"No complete crawl-to-report production acceptance run is recorded yet.",lastSeenAt:lastSuccessfulAutomationAt});
  const productionKeys=["scheduler:seo","scheduler:automation","crawler","github","vercel","dataforseo","search_console","publishing","pagespeed","creative_model","queue","automation"],productionReady=productionKeys.every(key=>checks.find(check=>check.key===key)?.state==="ready");
  return{ready:checks.every(check=>check.state!=="blocked"),productionReady,checks,queue,heartbeats:heartbeatRows.map(row=>({component:row.component,status:row.status,lastSeenAt:row.last_seen_at})),lastSuccessfulAutomationAt,configuration:{database:hasSupabaseAdminConfig,cron:Boolean(env.CRON_SECRET)}};
}
