import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage } from "../marketing-shared";

export const metadata: Metadata = { title: "HD SEO for Agencies", description: "Client-first SEO workflows, approvals, controlled implementation, and white-label reporting for agencies.", alternates: { canonical: "/agencies" }, openGraph: { title: "HD SEO for Agencies", description: "Manage client SEO work from evidence to approved execution and reporting.", url: "/agencies", type: "website" } };

export default function AgenciesPage() {
  return <InfoPage eyebrow="FOR AGENCIES" title="One accountable workspace for every client." intro="HD SEO helps agencies organize opportunities, approvals, implementation, and outcome reporting around each client—not around disconnected tools."><div className="info-callout"><strong>Pricing by active managed client</strong><p>Agency Launch is $499/month for 3 active managed client websites. Team members and read-only client viewers are included without per-seat charges. Limited Founding Beta pricing is shown on the pricing page.</p></div><h2>Built around the client relationship.</h2><div className="audience-grid"><article><h3>Prioritized work</h3><p>See high-value opportunities, approval status, blocked connections, and deployment health by client.</p></article><article><h3>Controlled delivery</h3><p>Apply client-specific permissions, budgets, service areas, and publishing rules.</p></article><article><h3>Clear reporting</h3><p>Keep estimates, measured performance, qualified leads, and verified outcomes clearly separated.</p></article></div><h2>What agency plans are designed to include</h2><ul><li>Client-first portfolio and approval views</li><li>White-label dashboard and reporting patterns</li><li>GitHub, CMS, analytics, and attribution connections where configured</li><li>Role-based permissions and complete work history</li><li>Human approval for high-risk or externally funded actions</li></ul><div className="info-actions"><Link href="/pricing" data-analytics-event="agency_cta_click" data-analytics-placement="agency_page">Compare Agency Plans</Link><Link className="secondary" href="/audit">Run a Free Client-Site Audit</Link></div></InfoPage>;
}
