import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage } from "../marketing-shared";

export const metadata: Metadata = { title: "HD SEO for Enterprise and Multi-Location Teams", description: "Governed SEO workflows for multi-location organizations that need role-based access, approval controls, and auditability.", alternates: { canonical: "/enterprise" }, openGraph: { title: "HD SEO for Enterprise", description: "Governed, measurable SEO operations for multi-location organizations.", url: "/enterprise", type: "website" } };

export default function EnterprisePage() {
  return <InfoPage eyebrow="ENTERPRISE & MULTI-LOCATION" title="Scale the workflow without losing control." intro="HD SEO coordinates SEO decisions across locations, roles, budgets, and infrastructure while preserving review, validation, and audit history."><div className="info-callout"><strong>Custom plans start at $2,500/month</strong><p>Infrastructure, security review, client and website limits, service levels, and implementation scope are confirmed during an enterprise assessment.</p></div><h2>Governance before automation.</h2><div className="audience-grid"><article><h3>Market boundaries</h3><p>Keep approved locations, regions, services, and publishing policies distinct.</p></article><article><h3>Permission boundaries</h3><p>Define who can review, approve, publish, connect tools, and authorize external spend.</p></article><article><h3>Outcome boundaries</h3><p>Separate estimates from measured traffic, leads, recorded revenue, and verified return.</p></article></div><h2>Designed for complex operating environments</h2><ul><li>Multi-location and multi-brand organization patterns</li><li>SSO, role-based access, audit exports, and custom retention policies</li><li>Approval gates for legal, pricing, DNS, destructive, and high-risk publishing changes</li><li>Dedicated infrastructure options, validation evidence, and rollback-aware workflows</li><li>Advanced security review, custom SLAs, onboarding, and support</li></ul><div className="info-actions"><Link href="/book-demo" data-analytics-event="booking_cta_click" data-analytics-placement="enterprise_page">Book an Enterprise Review</Link><Link className="secondary" href="/pricing">Compare Plans</Link></div></InfoPage>;
}
