import "server-only";
import { env } from "@/lib/config/env";

export type CheckStatus="passed"|"warning"|"failed"|"skipped";
export interface ValidationCheck{checkType:"health"|"lighthouse"|"seo"|"links"|"schema"|"sitemap"|"robots"|"indexing_readiness"|"drift";status:CheckStatus;required:boolean;score?:number;details:Record<string,unknown>}
export interface ValidationOptions{protectionBypassSecret?:string;environment?:"preview"|"production"}

async function fetchText(url:string,options:ValidationOptions={},timeoutMs=20_000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs),protectedOrigin=new URL(url).origin;try{let current=url;for(let redirectCount=0;redirectCount<=5;redirectCount+=1){const currentOrigin=new URL(current).origin,response=await fetch(current,{redirect:"manual",cache:"no-store",signal:controller.signal,headers:{"user-agent":"HDSEO-Deployment-Validator/1.0",...(options.protectionBypassSecret&&currentOrigin===protectedOrigin?{"x-vercel-protection-bypass":options.protectionBypassSecret}:{})}});if(response.status<300||response.status>=400)return{response,text:(await response.text()).slice(0,2_000_000)};const location=response.headers.get("location");if(!location)return{response,text:(await response.text()).slice(0,2_000_000)};const next=new URL(location,current);if(options.protectionBypassSecret&&next.origin!==protectedOrigin){const error=new Error("Protected preview redirected outside its verified origin.") as Error&{redirectOrigin?:string;redirectPath?:string};error.redirectOrigin=next.origin;error.redirectPath=next.pathname;throw error;}current=next.toString()}throw new Error("Preview exceeded the redirect limit.")}finally{clearTimeout(timer)}}
const match=(html:string,pattern:RegExp)=>pattern.exec(html)?.[1]?.trim()??null;

export async function validateDeploymentUrl(inputUrl:string,options:ValidationOptions={}):Promise<ValidationCheck[]>{
  const base=new URL(inputUrl.startsWith("http")?inputUrl:`https://${inputUrl}`),checks:ValidationCheck[]=[],preview=options.environment==="preview";
  let home:{response:Response;text:string};
  try{home=await fetchText(base.toString(),options);const finalUrl=new URL(home.response.url),protectionBlocked=finalUrl.hostname==="vercel.com"&&finalUrl.pathname==="/login";checks.push({checkType:"health",status:home.response.ok&&!protectionBlocked?"passed":"failed",required:true,details:{status:home.response.status,finalUrl:home.response.url,contentType:home.response.headers.get("content-type"),...(protectionBlocked?{reason:"vercel_deployment_protection"}:{})}})}
  catch(error){const safe=error as Error&{redirectOrigin?:string;redirectPath?:string};return[{checkType:"health",status:"failed",required:true,details:{error:error instanceof Error?error.message:"Health request failed",...(safe.redirectOrigin?{redirectOrigin:safe.redirectOrigin,redirectPath:safe.redirectPath??"/"}:{})}},{checkType:"lighthouse",status:"skipped",required:false,details:{reason:"Site is unavailable"}},{checkType:"seo",status:"failed",required:true,details:{reason:"Site is unavailable"}},{checkType:"links",status:"failed",required:true,details:{reason:"Site is unavailable"}},{checkType:"schema",status:"skipped",required:false,details:{reason:"Site is unavailable"}},{checkType:"sitemap",status:"failed",required:true,details:{reason:"Site is unavailable"}},{checkType:"robots",status:"failed",required:true,details:{reason:"Site is unavailable"}},{checkType:"indexing_readiness",status:"failed",required:true,details:{reason:"Site is unavailable"}}]}
  const html=home.text,title=match(html,/<title[^>]*>([\s\S]*?)<\/title>/i),description=match(html,/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["'][^>]*>/i)??match(html,/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["'][^>]*>/i),canonical=match(html,/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["'][^>]*>/i),h1Count=(html.match(/<h1\b/gi)??[]).length,h1Text=match(html,/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()??null,metaRobots=match(html,/<meta[^>]+name=["']robots["'][^>]+content=["']([^"']+)["'][^>]*>/i)?.toLowerCase()??"";
  const seoProblems=[!title&&"missing_title",!description&&"missing_meta_description",h1Count===0&&"missing_h1",h1Count>1&&"multiple_h1",!canonical&&"missing_canonical"].filter(Boolean),blockingSeoProblems=preview?seoProblems.filter(problem=>problem!=="missing_canonical"):seoProblems;
  checks.push({checkType:"seo",status:blockingSeoProblems.length?"failed":seoProblems.length?"warning":"passed",required:true,score:Math.max(0,100-seoProblems.length*20),details:{title,description,descriptionLength:description?.length??0,canonical,h1Count,h1Text,metaRobots:metaRobots||null,problems:seoProblems,blockingProblems:blockingSeoProblems,previewPolicy:preview}});
  const internalLinks=[...new Set([...html.matchAll(/<a\b[^>]*href=["']([^"']+)["']/gi)].map(item=>item[1]).filter(href=>!href.startsWith("#")&&!/^(?:mailto|tel|javascript):/i.test(href)).map(href=>{try{return new URL(href,base)}catch{return null}}).filter((url):url is URL=>Boolean(url&&url.origin===base.origin)).map(url=>url.toString()))].slice(0,30),linkResults=await Promise.all(internalLinks.map(async url=>{try{const result=await fetchText(url,options,8_000);return{url,status:result.response.status,ok:result.response.ok}}catch{return{url,status:null,ok:false}}})),brokenLinks=linkResults.filter(item=>!item.ok);checks.push({checkType:"links",status:brokenLinks.length?"failed":"passed",required:true,score:internalLinks.length?Math.round((internalLinks.length-brokenLinks.length)/internalLinks.length*100):100,details:{checked:internalLinks.length,broken:brokenLinks}});
  const schemaBlocks=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].map(item=>item[1]),schemaErrors:string[]=[],schemaTypes=new Set<string>();for(const block of schemaBlocks){try{const parsed=JSON.parse(block);const visit=(value:unknown)=>{if(Array.isArray(value)){value.forEach(visit);return}if(value&&typeof value==="object"){const record=value as Record<string,unknown>,type=record["@type"];if(typeof type==="string")schemaTypes.add(type);if(Array.isArray(type))type.filter((item):item is string=>typeof item==="string").forEach(item=>schemaTypes.add(item));Object.values(record).forEach(visit)}};visit(parsed)}catch(error){schemaErrors.push(error instanceof Error?error.message:"Invalid JSON-LD")}}
  checks.push({checkType:"schema",status:schemaErrors.length?"failed":schemaBlocks.length?"passed":"warning",required:false,details:{blocks:schemaBlocks.length,types:[...schemaTypes].sort(),errors:schemaErrors}});
  let robotsOk=false,robotsDisallowAll=false;try{const robots=await fetchText(new URL("/robots.txt",base).toString(),options);robotsOk=robots.response.ok&&/user-agent\s*:/i.test(robots.text);robotsDisallowAll=/user-agent\s*:\s*\*[\s\S]*?disallow\s*:\s*\/(?:\s|$)/i.test(robots.text);checks.push({checkType:"robots",status:preview?"skipped":robotsOk&&!robotsDisallowAll?"passed":"failed",required:!preview,details:{status:robots.response.status,hasUserAgent:/user-agent\s*:/i.test(robots.text),disallowsAll:robotsDisallowAll,...(preview?{reason:"Protected previews must not be indexable; production robots.txt is checked after release."}:{})}})}catch(error){checks.push({checkType:"robots",status:preview?"skipped":"failed",required:!preview,details:{error:error instanceof Error?error.message:"robots.txt request failed"}})}
  let sitemapOk=false;try{const sitemap=await fetchText(new URL("/sitemap.xml",base).toString(),options);sitemapOk=sitemap.response.ok&&/<(?:urlset|sitemapindex)\b/i.test(sitemap.text);checks.push({checkType:"sitemap",status:sitemapOk?"passed":"failed",required:true,details:{status:sitemap.response.status,validRoot:/<(?:urlset|sitemapindex)\b/i.test(sitemap.text),urlCount:(sitemap.text.match(/<loc>/gi)??[]).length}})}catch(error){checks.push({checkType:"sitemap",status:"failed",required:true,details:{error:error instanceof Error?error.message:"sitemap.xml request failed"}})}
  const indexable=home.response.ok&&!metaRobots.includes("noindex")&&!robotsDisallowAll&&sitemapOk;checks.push({checkType:"indexing_readiness",status:preview?"skipped":indexable?"passed":"failed",required:!preview,details:{httpOk:home.response.ok,metaRobots:metaRobots||null,robotsAllowsCrawling:!robotsDisallowAll,sitemapValid:sitemapOk,...(preview?{reason:"Protected previews are intentionally excluded from indexing; production readiness is checked after release."}:{})}});
  if(options.protectionBypassSecret)checks.push({checkType:"lighthouse",status:"skipped",required:false,details:{reason:"Protected preview credentials are never sent to external PageSpeed services; Lighthouse runs again after release."}});
  else try{const endpoint=new URL("https://www.googleapis.com/pagespeedonline/v5/runPagespeed");endpoint.searchParams.set("url",base.toString());endpoint.searchParams.append("category","PERFORMANCE");endpoint.searchParams.append("category","SEO");endpoint.searchParams.set("strategy","mobile");if(env.PAGESPEED_API_KEY)endpoint.searchParams.set("key",env.PAGESPEED_API_KEY);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45_000);try{const response=await fetch(endpoint,{signal:controller.signal,cache:"no-store"});if(!response.ok)throw new Error(`PageSpeed HTTP ${response.status}`);const data=await response.json() as {lighthouseResult?:{categories?:{performance?:{score?:number};seo?:{score?:number}}}};const performance=Math.round((data.lighthouseResult?.categories?.performance?.score??0)*100),seo=Math.round((data.lighthouseResult?.categories?.seo?.score??0)*100);checks.push({checkType:"lighthouse",status:performance>=70&&seo>=90?"passed":"warning",required:false,score:performance,details:{performance,seo,strategy:"mobile"}})}finally{clearTimeout(timer)}}catch(error){checks.push({checkType:"lighthouse",status:"warning",required:false,details:{error:error instanceof Error?error.message:"Lighthouse request failed"}})}
  return checks;
}
