import "server-only";
import { ApiError,logEvent,safeError } from "@/lib/api/errors";
import { env } from "@/lib/config/env";
import { requireAdminDb } from "./control-plane";
import { loadVercelCredentials } from "@/lib/vercel/credentials";
import { createVercelDeployment,getVercelDeployment,getVercelDeploymentEvents,rollbackVercelProject } from "@/lib/vercel/client";
import { validateDeploymentUrl } from "./validator";
import { compareSeoDrift,deploymentSnapshotFromChecks } from "@/lib/seo/drift";

interface BackgroundJob{id:string;job_type:string;agency_id:string;automation_run_id:string|null;deployment_id:string|null;payload:Record<string,unknown>;attempt_count:number;max_attempts:number}
const terminalStates=new Set(["READY","ERROR","CANCELED"]);
async function addLog(deploymentId:string,source:string,level:string,message:string,metadata:Record<string,unknown>={}){const db=requireAdminDb();await db.from("deploy_logs").upsert({deployment_id:deploymentId,sequence:Date.now()*1000+Math.floor(Math.random()*1000),source,level,message,metadata},{onConflict:"deployment_id,source,sequence"})}
async function setRun(runId:string|null,status:string,stage:string,error?:{code:string;message:string}){if(!runId)return;const db=requireAdminDb(),run=await db.from("automation_runs").select("seo_job_id").eq("id",runId).single(),now=new Date().toISOString();await db.from("automation_runs").update({status,current_stage:stage,error_code:error?.code??null,error_message:error?.message??null,started_at:status==="running"?now:undefined,completed_at:["succeeded","failed"].includes(status)?now:null,updated_at:now}).eq("id",runId);if(run.data)await db.from("seo_jobs").update({status,started_at:status==="running"?now:undefined,completed_at:status==="succeeded"?now:null,failed_at:status==="failed"?now:null,updated_at:now}).eq("id",run.data.seo_job_id)}
async function deploymentContext(id:string){const db=requireAdminDb(),deployment=await db.from("deployments").select("*").eq("id",id).single();if(!deployment.data)throw new ApiError("Deployment record not found.",404,"NOT_FOUND");const project=await db.from("vercel_projects").select("*").eq("id",deployment.data.vercel_project_id).single(),repository=deployment.data.repository_id?await db.from("repositories").select("*").eq("id",deployment.data.repository_id).single():null;if(!project.data)throw new ApiError("Vercel project record not found.",404,"NOT_FOUND");return{db,deployment:deployment.data,project:project.data,repository:repository?.data??null}}

async function createDeployment(job:BackgroundJob){if(!job.deployment_id)throw new ApiError("Deployment job is incomplete.",500,"OPERATION_FAILED");const{db,deployment,project,repository}=await deploymentContext(job.deployment_id);if(!repository)throw new ApiError("Repository record not found.",404,"NOT_FOUND");const credentials=await loadVercelCredentials(project.connection_id,job.agency_id),now=new Date().toISOString();await db.from("deployments").update({status:"creating",started_at:now,updated_at:now}).eq("id",deployment.id);await setRun(job.automation_run_id,"running","deployment.create");const created=await createVercelDeployment(credentials,{projectId:project.vercel_project_id,projectName:project.name,repositoryId:String(repository.github_repository_id),ref:deployment.git_ref,sha:deployment.git_sha??undefined,environment:deployment.environment,metadata:{hdSeoDeploymentId:deployment.id,hdSeoRunId:job.automation_run_id??"",githubCommitSha:deployment.git_sha??"",projectId:project.vercel_project_id}});await db.from("deployments").update({external_deployment_id:created.id,url:created.url,status:created.readyState==="READY"?"ready":"building",provider_metadata:created,updated_at:new Date().toISOString()}).eq("id",deployment.id);await addLog(deployment.id,"vercel","info","Vercel deployment created.",{providerDeploymentId:created.id,url:created.url});await db.from("background_jobs").upsert({queue:"deployments",job_type:created.readyState==="READY"?"deployment.validate":"deployment.poll",agency_id:job.agency_id,automation_run_id:job.automation_run_id,deployment_id:deployment.id,payload:{},status:"queued",priority:created.readyState==="READY"?80:60,available_at:new Date(Date.now()+(created.readyState==="READY"?0:20_000)).toISOString(),idempotency_key:`${created.readyState==="READY"?"deployment.validate":"deployment.poll"}:${deployment.id}`},{onConflict:"queue,idempotency_key",ignoreDuplicates:true});}

async function pollDeployment(job:BackgroundJob){if(!job.deployment_id)throw new ApiError("Poll job is incomplete.",500,"OPERATION_FAILED");const{db,deployment,project}=await deploymentContext(job.deployment_id);if(!deployment.external_deployment_id)throw new ApiError("Vercel deployment ID is not available yet.",503,"OPERATION_FAILED");const credentials=await loadVercelCredentials(project.connection_id,job.agency_id),provider=await getVercelDeployment(credentials,deployment.external_deployment_id),state=(provider.readyState??"").toUpperCase();await db.from("deployments").update({status:state==="READY"?"ready":state==="ERROR"?"failed":"building",url:provider.url??deployment.url,ready_at:state==="READY"?new Date().toISOString():null,completed_at:state==="ERROR"?new Date().toISOString():null,provider_metadata:provider,updated_at:new Date().toISOString()}).eq("id",deployment.id);if(!terminalStates.has(state))throw new ApiError("Vercel deployment is still building.",503,"OPERATION_FAILED");try{const events=await getVercelDeploymentEvents(credentials,deployment.external_deployment_id);for(const [index,event] of events.entries())await db.from("deploy_logs").upsert({deployment_id:deployment.id,sequence:event.date??event.created??index,source:"vercel",level:event.type==="stderr"?"error":"info",message:(event.text??event.type??"Vercel event").slice(0,10_000),metadata:event},{onConflict:"deployment_id,source,sequence",ignoreDuplicates:true})}catch{await addLog(deployment.id,"vercel","warn","Deployment completed, but build logs could not be collected.")};if(state==="ERROR"){await setRun(job.automation_run_id,"failed","deployment.failed",{code:"VERCEL_DEPLOYMENT_FAILED",message:"Vercel reported a failed deployment."});return}await db.from("background_jobs").upsert({queue:"deployments",job_type:"deployment.validate",agency_id:job.agency_id,automation_run_id:job.automation_run_id,deployment_id:deployment.id,payload:{},status:"queued",priority:80,idempotency_key:`deployment.validate:${deployment.id}`},{onConflict:"queue,idempotency_key",ignoreDuplicates:true});}

async function validateDeployment(job:BackgroundJob){
  if(!job.deployment_id)throw new ApiError("Validation job is incomplete.",500,"OPERATION_FAILED");
  const{db,deployment}=await deploymentContext(job.deployment_id);
  if(!deployment.url)throw new ApiError("Deployment URL is not available.",503,"OPERATION_FAILED");
  const previous=await db.from("deployments").select("id").eq("vercel_project_id",deployment.vercel_project_id).eq("environment",deployment.environment).eq("status","healthy").neq("id",deployment.id).order("completed_at",{ascending:false}).limit(1).maybeSingle();
  const baselineChecks=previous.data?await db.from("deployment_checks").select("check_type,score,details").eq("deployment_id",previous.data.id):{data:[]};
  const baseline=previous.data?deploymentSnapshotFromChecks(baselineChecks.data??[]):null;
  await db.from("deployments").update({status:"validating",updated_at:new Date().toISOString()}).eq("id",deployment.id);
  await setRun(job.automation_run_id,"running","deployment.validate");
  const started=new Date().toISOString(),checks=await validateDeploymentUrl(deployment.url),current=deploymentSnapshotFromChecks(checks),drift=compareSeoDrift(baseline,current);
  checks.push({checkType:"drift",status:drift.status,required:drift.required,details:{baselineDeploymentId:previous.data?.id??null,findings:drift.findings,baseline:drift.baseline,current:drift.current}});
  for(const check of checks)await db.from("deployment_checks").upsert({deployment_id:deployment.id,check_type:check.checkType,status:check.status,required:check.required,score:check.score??null,details:check.details,started_at:started,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"deployment_id,check_type"});
  const failed=checks.filter(check=>check.required&&check.status==="failed"),summary={passed:checks.filter(c=>c.status==="passed").length,warnings:checks.filter(c=>c.status==="warning").length,failed:failed.map(c=>c.checkType),checks:checks.length,baselineDeploymentId:previous.data?.id??null};
  await db.from("deployments").update({status:failed.length?"failed":"healthy",validation_summary:summary,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",deployment.id);
  await addLog(deployment.id,"hdseo",failed.length?"error":"info",failed.length?`Deployment validation failed: ${failed.map(item=>item.checkType).join(", ")}.`:"All required deployment validations passed.",summary);
  await setRun(job.automation_run_id,failed.length?"failed":"succeeded",failed.length?"deployment.validation_failed":"completed",failed.length?{code:"DEPLOYMENT_VALIDATION_FAILED",message:`Required checks failed: ${failed.map(item=>item.checkType).join(", ")}`} : undefined);
  const client=await db.from("clients").select("organization_id,automation_config").eq("id",deployment.client_id).single(),run=job.automation_run_id?await db.from("automation_runs").select("seo_job_id").eq("id",job.automation_run_id).single():null,seoJob=run?.data?await db.from("seo_jobs").select("requested_by").eq("id",run.data.seo_job_id).single():null;
  await db.from("notifications").insert({agency_id:deployment.agency_id,client_organization_id:client.data?.organization_id??null,project_id:deployment.project_id,user_id:seoJob?.data?.requested_by??null,event_type:failed.length?"deployment.failed":"deployment.healthy",title:failed.length?"Deployment validation failed":"Deployment is healthy",body:failed.length?`Required checks failed: ${failed.map(item=>item.checkType).join(", ")}.`:"HD SEO completed health, Lighthouse, SEO, schema, sitemap, robots.txt, indexing-readiness, and drift validation.",status:"sent",sent_at:new Date().toISOString(),metadata:{deploymentId:deployment.id,url:deployment.url,summary}});
  if(failed.length&&deployment.environment==="production"&&(client.data?.automation_config as {autoRollback?:boolean}|undefined)?.autoRollback&&previous.data)await db.rpc("enqueue_rollback_job",{p_agency_id:deployment.agency_id,p_source_deployment_id:deployment.id,p_target_deployment_id:previous.data.id,p_requested_by:null,p_idempotency_key:`auto-rollback:${deployment.id}:${previous.data.id}`});
}

async function rollbackDeployment(job:BackgroundJob){if(!job.deployment_id)throw new ApiError("Rollback job is incomplete.",500,"OPERATION_FAILED");const{db,deployment,project}=await deploymentContext(job.deployment_id),targetId=deployment.previous_deployment_id as string|null;if(!targetId)throw new ApiError("Rollback target is missing.",409,"CONFLICT");const target=await db.from("deployments").select("external_deployment_id,url").eq("id",targetId).single();if(!target.data?.external_deployment_id)throw new ApiError("Rollback target is not a Vercel production deployment.",409,"CONFLICT");await db.from("deployments").update({status:"rolling_back",started_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",deployment.id);await setRun(job.automation_run_id,"running","deployment.rollback");const credentials=await loadVercelCredentials(project.connection_id,job.agency_id);await rollbackVercelProject(credentials,project.vercel_project_id,target.data.external_deployment_id,`HD SEO rollback ${deployment.id}`);await db.from("deployments").update({status:"rolled_back",url:target.data.url,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",deployment.id);if(deployment.rollback_of_id)await db.from("deployments").update({status:"rolled_back",updated_at:new Date().toISOString()}).eq("id",deployment.rollback_of_id);await setRun(job.automation_run_id,"succeeded","completed");await addLog(deployment.id,"vercel","warn","Production traffic was rolled back to a prior healthy deployment.",{targetDeploymentId:targetId,targetProviderDeploymentId:target.data.external_deployment_id});}

const handlers:Record<string,(job:BackgroundJob)=>Promise<void>>={"deployment.create":createDeployment,"deployment.poll":pollDeployment,"deployment.validate":validateDeployment,"deployment.rollback":rollbackDeployment};
export async function processDeploymentBatch(size=env.AUTOMATION_JOB_BATCH_SIZE,workerId=`automation:${crypto.randomUUID()}`){const db=requireAdminDb(),claimed=await db.rpc("claim_background_jobs",{p_worker_id:workerId,p_batch_size:size,p_lock_seconds:300,p_queue:"deployments"});if(claimed.error)throw new Error("Background jobs could not be claimed.");const jobs=(claimed.data??[]) as BackgroundJob[],results=[];for(const job of jobs){const handler=handlers[job.job_type];try{if(!handler)throw new ApiError(`Unknown background job type: ${job.job_type}`,500,"OPERATION_FAILED");await handler(job);await db.from("background_jobs").update({status:"succeeded",completed_at:new Date().toISOString(),worker_id:null,locked_at:null,lock_expires_at:null,updated_at:new Date().toISOString()}).eq("id",job.id);results.push({jobId:job.id,status:"succeeded"});logEvent("automation_job_completed",{jobId:job.id,agencyId:job.agency_id,status:"succeeded",stage:job.job_type})}catch(error){const safe=safeError(error),retryable=(safe.status===429||safe.status>=500)&&job.attempt_count<job.max_attempts,delay=Math.min(900_000,15_000*2**Math.max(0,job.attempt_count-1))+Math.floor(Math.random()*5000),status=retryable?"retry_scheduled":job.attempt_count>=job.max_attempts?"dead_letter":"failed";await db.from("background_jobs").update({status,available_at:new Date(Date.now()+delay).toISOString(),last_error_code:safe.body.error.code,last_error_message:safe.body.error.message,worker_id:null,locked_at:null,lock_expires_at:null,updated_at:new Date().toISOString()}).eq("id",job.id);if(!retryable)await setRun(job.automation_run_id,"failed",job.job_type,{code:safe.body.error.code,message:safe.body.error.message});results.push({jobId:job.id,status,error:safe.body.error});logEvent("automation_job_failed",{jobId:job.id,agencyId:job.agency_id,status,errorCode:safe.body.error.code,stage:job.job_type})}}return{claimed:jobs.length,results}}
