import { z } from "zod";
import { ApiError,jsonError } from "@/lib/api/errors";
import { parseJson } from "@/lib/api/request";
import { auditEvent } from "@/lib/automation/control-plane";
import { requireLiveAgencyProject } from "@/lib/auth/live-tenant";
import { googleAccess,loadGoogleConnection,publicGoogleConnection } from "@/lib/google/connection";
import { listSearchConsoleProperties,propertyMatchesDomain } from "@/lib/google/search-console";

const schema=z.object({projectId:z.string().uuid(),property:z.string().min(4).max(500)});
export async function GET(request:Request){try{const projectId=new URL(request.url).searchParams.get("projectId");if(!projectId)throw new ApiError("Project is required.",400,"VALIDATION_ERROR");const context=await requireLiveAgencyProject({projectId,permission:"integrations.manage"}),connection=await loadGoogleConnection(context.db,{agencyId:context.agencyId,clientId:context.clientId,projectId}),accessToken=await googleAccess(context.db,connection),properties=await listSearchConsoleProperties(accessToken);return Response.json({ok:true,connection:publicGoogleConnection({...connection,metadata:{...connection.metadata,properties}}),properties});}catch(error){return jsonError(error);}}
export async function PUT(request:Request){try{const input=await parseJson(request,z.object({projectId:z.string().uuid()})),context=await requireLiveAgencyProject({projectId:input.projectId,permission:"integrations.manage"}),connection=await loadGoogleConnection(context.db,{agencyId:context.agencyId,clientId:context.clientId,projectId:input.projectId}),accessToken=await googleAccess(context.db,connection),properties=await listSearchConsoleProperties(accessToken),selected=connection.selected_resource??properties.find(item=>propertyMatchesDomain(item.siteUrl,context.project.domain))?.siteUrl??(properties.length===1?properties[0].siteUrl:null),now=new Date().toISOString(),metadata={...connection.metadata,properties,health:selected?"ready":"property_selection_required",propertiesRefreshedAt:now},saved=await context.db.from("integration_connections").update({selected_resource:selected,status:"active",last_verified_at:now,metadata,updated_at:now}).eq("id",connection.id).eq("agency_id",context.agencyId);if(saved.error)throw new ApiError("The authorized Search Console properties could not be saved.",500,"DATABASE_BINDING_FAILED");await auditEvent({agencyId:context.agencyId,actorUserId:context.userId,action:selected&&!connection.selected_resource?"google.search_console.property_auto_selected":"google.search_console.properties_refreshed",resourceType:"integration_connection",resourceId:connection.id,afterState:{projectId:input.projectId,selectedProperty:selected,propertyCount:properties.length},request});return Response.json({ok:true,selectedProperty:selected,properties,message:selected?`Search Console property ${selected} is ready.`:properties.length?"Choose an authorized Search Console property.":"No authorized Search Console properties were found for this Google account."});}catch(error){return jsonError(error);}}
export async function POST(request:Request){try{const input=await parseJson(request,schema),context=await requireLiveAgencyProject({projectId:input.projectId,permission:"integrations.manage"}),connection=await loadGoogleConnection(context.db,{agencyId:context.agencyId,clientId:context.clientId,projectId:input.projectId}),accessToken=await googleAccess(context.db,connection),properties=await listSearchConsoleProperties(accessToken);if(!properties.some(item=>item.siteUrl===input.property))throw new ApiError("The selected Search Console property is not authorized for this Google account.",403,"PROPERTY_NOT_AUTHORIZED");const now=new Date().toISOString(),saved=await context.db.from("integration_connections").update({selected_resource:input.property,status:"active",last_verified_at:now,metadata:{...connection.metadata,properties,health:"ready"},updated_at:now}).eq("id",connection.id).eq("agency_id",context.agencyId);if(saved.error)throw new ApiError("The Search Console property could not be saved.",500,"DATABASE_BINDING_FAILED");await auditEvent({agencyId:context.agencyId,actorUserId:context.userId,action:"google.search_console.property_selected",resourceType:"integration_connection",resourceId:connection.id,afterState:{projectId:input.projectId,property:input.property},request});return Response.json({ok:true,property:input.property});}catch(error){return jsonError(error);}}
